WIP: raft: automatically join group0 when upgrading the cluster and switch to raft-based schema changes
scylladb/scylladb pull request #10432
Opened 2022-04-26 09:40 UTC by ManManson

Wire in `join_group0()` to be called when enabling `SUPPORTS_RAFT_CLUSTER_MANAGEMENT` feature.

Also, fix the check for migration manager to properly switch to using raft-based schema changes: it should check that the current node is a part of group0 instead of just checking that `raft_group_registry::is_enabled()` returns `true` (which can be so even if group0 is not formed yet). 

This PR is draft, since it is dependent on https://github.com/scylladb/scylla/pull/10380

2022-04-26 12:43 UTC, scylladb-promoter commented
CI state **`SUCCESS`** - https://jenkins.scylladb.com/job/releng/job/Scylla-CI/168/

2022-04-26 13:11 UTC, kbr- requested changes

2022-04-26 13:11 UTC, kbr- commented on service/raft/raft_group_registry.cc
> +            _group0->join_group0().get();
- join_group0() currently uses the list of seeds (from scylla.yaml) to initialize discovery. But in upgrade we must ensure that **every** member of the Scylla cluster is included in the newly formed Raft cluster. We cannot create group 0 with some arbitrary subset of nodes, some of which may no longer exist (the seed list is only used for joining the cluster) and which may lead to separate group 0 clusters being formed (different nodes may use different disjoint seed lists).
- We must not block gossiper on join group 0. The listener is called from gossiper (`do_on_change_notifications`); right now the code will block gossiper (this is what caused deadlocks earlier) join_group0() may be a long operation, it needs to run the distributed discovery algorithm, all nodes must contact each other (see also first bullet).

2022-04-26 13:46 UTC, ManManson commented on service/raft/raft_group_registry.cc
> +        if (_group0) {
Indeed, this should be an assert.

2023-06-05 12:11 UTC, mykaul commented
Probably less relevant now - closing (I assume this is handled in different PR - please re-open, resolve conflicts, etc. if I'm wrong).

2023-06-05 12:11 UTC, closed without merging