utils: config_file: fix handling of workdir,W in the YAML file
scylladb/scylladb pull request #11506
Opened 2022-09-08 18:21 UTC by michoecho

Option names given in db/config.cc are handled for the command line by passing them to boost::program_options, and by YAML by comparing them with YAML keys.
boost::program_options has logic for understanding the long_name,short_name syntax, so for a "workdir,W" option both --workdir and -W worked, as intended. But our YAML config parsing doesn't have this logic and expected "workdir,W" verbatim, which is obviously not intended. Fix that.

Fixes #7478
Fixes #9500
Fixes #11503

2022-09-08 18:24 UTC, michoecho commented
Do note that this is a breaking change for people who worked around the issue by setting `workdir,W` in the YAML.

2022-09-08 20:26 UTC, nyh requested changes
Very nice! Amazing that we already had three issues about such a silly little bug :-)

If you want to support the silly "workdir,W" workaround for people with existing scylla.yaml (as you yourself suggested), how about checking `if (_name == name || long_name == name)`? This will allow both the silly "workdir,W" and the new "workdir", and the patch will be just as simple.

2022-09-08 21:42 UTC, michoecho commented
> If you want to support the silly "workdir,W" workaround for people with existing scylla.yaml (as you yourself suggested), how about checking if (_name == name || long_name == name)? This will allow both the silly "workdir,W" and the new "workdir", and the patch will be just as simple.

Good idea. Applied.

2022-09-09 02:08 UTC, scylladb-promoter commented
CI state **`SUCCESS`** - https://jenkins.scylladb.com/job/releng/job/Scylla-CI/2166/

2022-09-09 09:03 UTC, kbr- approved these changes
3 issues fixed with a single patch.
This is what I call velocity.

2022-09-09 09:06 UTC, nyh approved these changes

2022-09-10 03:37 UTC, closed without merging