test/pylib: pool: make it possible to free up space
scylladb/scylladb pull request #11558
Opened 2022-09-15 16:54 UTC by kbr-

Some tests mark clusters as 'dirty', which makes them non-reusable by
later tests; we don't want to return them to the pool of clusters.

This use-case was covered by the `add_one` function in the `Pool` class.
However, it had the unintended side effect of creating extra clusters
even if there were no more tests that were waiting for new clusters.

Rewrite the implementation of `Pool` so it provides 3 interface
functions:
- `get` borrows an object, building it first if necessary
- `put` returns a borrowed object
- `steal` is called by a borrower to free up space in the pool;
  the borrower is then responsible for cleaning up the object.

Both `put` and `steal` wake up any outstanding `get` calls. Objects are
built only in `get`, so no objects are built if none are needed.

Remove the `instance` function which was not used.

2022-09-15 16:54 UTC, kbr- commented
The branch is based on current `next` hence the big PR.
But only the last commit is part of the actual PR (https://github.com/scylladb/scylladb/pull/11558/commits/e7d561d0b08f2974dd043d3d7b396c2258465e9d)

2022-09-15 18:03 UTC, alecco requested changes
Need to revert `Pool.instance()`, please test `cql` and `cql-pytest`:
```
./test.py --mode dev cql/ cql-pytest/ 
```

Also a minor formatting style fix.

2022-09-15 19:14 UTC, scylladb-promoter commented
CI state **`FAILURE`** - https://jenkins.scylladb.com/job/releng/job/Scylla-CI/2269/

2022-09-16 05:53 UTC, denesb approved these changes
I'm not familiar with this code but the change make sense to me.
I wouldn't have used the word steal for the purpose it is used here, but it works.

2022-09-16 09:45 UTC, kbr- commented
v2:
- use lazy formatting strings
- bring `instance()` back
- modify the pool docstring

2022-09-16 14:06 UTC, scylladb-promoter commented
CI state **`SUCCESS`** - https://jenkins.scylladb.com/job/releng/job/Scylla-CI/2275/

2022-09-16 14:10 UTC, kbr- commented
@denesb in that case perhaps you would like to merge it?

2022-09-16 16:19 UTC, kbr- commented
or @nyh

2022-09-18 09:05 UTC, nyh approved these changes

2022-09-18 09:05 UTC, nyh commented on test/pylib/pool.py
> +                await pool.put(server)
I think the analogies of "getting" and "stealing" from a "pool" isn't clear.
What I missed in first reading (and only understood in second reading), is the the pool deliberately has a fixed maximum size, so if N users "borrowed" (get()) objects the next one will block until one of the existing borrowers will either return the object, or admit it was stolen (in which case a new one can be created).
But I guess we can improve the documentation later.

2022-09-18 22:13 UTC, closed without merging