Raft transport error
scylladb/scylladb pull request #11691
Opened 2022-10-03 10:39 UTC by gusev-p

The `add_entry` and `modify_config` methods sometimes do an rpc to
execute the request on the current leader. If the tcp connection
was broken, a `seastar::rpc::closed_error` would be thrown to the client.
This exception was not documented in the method comments and the
client could have missed handling it. For example, this exception
was not handled when calling `modify_config` in `raft_group0`,
which sometimes broke the removenode command.

An `intermittent_connection_error` exception was added earlier to
solve a similar problem with the `read_barrier` method. In this patch it
is renamed to `transport_error`, as it seems to better describe the
situation, and an explicit specification for this exception
was added - the rpc implementation can throw it if it is not known
whether the call reached the destination and whether any mutations were made.

In case of read_barrier it does not matter and we just retry, in case
of `add_entry` and `modify_config` we cannot retry because of possible mutations,
so we convert this exception to `commit_status_unknown`, which
the client has to handle.

Explicit comments have also been added to `raft::server` methods
describing all possible exceptions.

2022-10-03 11:04 UTC, gleb-cloudius reviewed
Looks fine except a not pick. But I would rewrite a commit message for the first patch to not mention mutations. Raft payload does not have to be a mutations and mutations are actually idempotent, so retrying them is safe.

2022-10-03 12:50 UTC, gusev-p commented
> Looks fine except a not pick. But I would rewrite a commit message for the first patch to not mention mutations. Raft payload does not have to be a mutations and mutations are actually idempotent, so retrying them is safe.

ok, will fix

2022-10-03 12:50 UTC, gusev-p commented on raft/server.cc
> +                    return _rpc->send_add_entry(leader, command)
It just seemed more convenient.

2022-10-03 12:56 UTC, gleb-cloudius commented on raft/server.cc
> +                    return _rpc->send_add_entry(leader, command)
In what way? We try to keep raft code co-routinized. There are three `then` in the whole server.cc. Two of then are used when a job has to be put in a background, so co_wait will not work there. And the last one `then_wrapped` should be replaced with `co_await` as well it seams.

2022-10-03 13:56 UTC, gusev-p commented on raft/server.cc
> +                    return _rpc->send_add_entry(leader, command)
changed to `co_await`

2022-10-03 19:43 UTC, scylladb-promoter commented
CI state **`FAILURE`** - https://jenkins.scylladb.com/job/releng/job/Scylla-CI/2507/

2022-10-05 14:03 UTC, kbr- requested changes

2022-10-05 14:03 UTC, kbr- commented on service/raft/raft_group0.cc
> +            group0_log.info("\"remove_from_raft_config({}): modify_config returned \"{}\", retrying", id, e);
Nit: this opening `\"` doesn't seem to have a corresponding closing `\"`.

2022-10-07 09:14 UTC, scylladb-promoter commented
CI state **`FAILURE`** - https://jenkins.scylladb.com/job/releng/job/Scylla-CI/2592/

2022-10-07 09:59 UTC, kbr- approved these changes
LGTM, will merge once CI passes.

2022-10-07 10:06 UTC, gusev-p commented on service/raft/raft_rpc.cc
> +            return make_exception_future<raft::add_entry_reply>(raft::transport_error(message));
`std::runtime_error` which `raft::transport_error` inherits doesn't provide a constructor with `sstring&&`, since it copies the string anyway.

2022-10-07 13:49 UTC, scylladb-promoter commented
CI state **`SUCCESS`** - https://jenkins.scylladb.com/job/releng/job/Scylla-CI/2594/

2022-10-07 15:35 UTC, kostja commented
The commit message says: 

raft_group0: retry modify_config on commit_status_unknown

modify_config can throw commit_status_unknown in case
of a leader change or when the leader is unavailable,
but the information about it has not yet reached the
current node. In this patch modify_config is run
again after some time in this case.

Please add  a few sentences clarifying why it's safe to retry:

When group0 requests a configuration change, it's a set operation: adding or removing a node to the current configurations. Raft server ids are unique, and adding or removing unique values to a set is idempotent: if the member is already in the set, it does nothing.

2022-10-07 15:43 UTC, kbr- commented
@kostja too late, already merged.
Also:

> Raft server ids are unique, and adding or removing unique values to a set is idempotent: if the member is already in the set, it does nothing.

that's not really accurate, there's also switching from voters to non-voters and vice-versa.
Repeating `modify_config` calls is not 100% safe.

2022-10-07 16:35 UTC, kostja commented
> @kostja too late, already merged. Also:
> 
> > Raft server ids are unique, and adding or removing unique values to a set is idempotent: if the member is already in the set, it does nothing.
> 
> that's not really accurate, there's also switching from voters to non-voters and vice-versa. Repeating `modify_config` calls is not 100% safe.

This switch is outside the retry loop which was added in this patch.

2022-10-08 00:29 UTC, closed without merging

2022-10-10 09:37 UTC, kbr- commented
I'm speaking in general (as your argument did), not in this particular case.