Projection field added to return from DescribeTable which describes GSIs and LSIs
scylladb/scylladb pull request #11693
Opened 2022-10-03 11:34 UTC by alexander-tur

Projection field added to return from DescribeTable which describes GSIs and LSIs.
We do not yet support all the settings Projection (see #5036), but the default which we support is ALL, and DescribeTable returns that in its description.

Fixes #11470

2022-10-03 11:55 UTC, nyh commented
Oops, sorry, my comment about the tests was wrong: Unfortunately, these two tests actually test multiple missing things - not just the Projection field - and will continue to fail after your patch.

Perhaps the best thing to do would be to live those old test functions alone, add two new test functions that unlike test_gsi_describe don't check every field - just the Projection field, and start to pass after your patch.

2022-10-03 15:36 UTC, scylladb-promoter commented
CI state **`SUCCESS`** - https://jenkins.scylladb.com/job/releng/job/Scylla-CI/2502/

2022-10-05 11:44 UTC, alexander-tur commented
> 
tests are fixed

2022-10-05 16:16 UTC, scylladb-promoter commented
CI state **`SUCCESS`** - https://jenkins.scylladb.com/job/releng/job/Scylla-CI/2559/

2022-10-06 15:35 UTC, nyh requested changes
Thanks, looks very good, just one typo in the test name.
Please send the signed contributor agreement as I noted above, and let me know when you have. Thanks!  CC @avikivity who tracks this stuff.

2022-10-09 16:31 UTC, scylladb-promoter commented
CI state **`SUCCESS`** - https://jenkins.scylladb.com/job/releng/job/Scylla-CI/2607/

2022-10-10 06:18 UTC, alexander-tur commented on test/alternator/test_gsi.py
> +def test_lsi_describe_fields(test_table_lsi_1):
test name is fixed.
and I have already signed the agreement: Alexander Turetskiy. sent 28.09. Let me know please if something is wrong.

2022-10-19 16:00 UTC, nyh approved these changes
Thanks! Sorry about the delayed review - I was on holiday. I'll merge it now.

2022-10-19 23:50 UTC, closed without merging