token_metadata: Do not use topology info for is_member check
scylladb/scylladb pull request #11936
Opened 2022-11-09 02:15 UTC by asias

Since commit a980f94 (token_metadata: impl: keep the set of normal token owners as a member), we have a set, _normal_token_owners, which contains all the nodes in the ring.

We can use _normal_token_owners to check if a node is part of the ring directly instead of going through the _toplogy indirectly.

Fixes #11935

2022-11-09 05:14 UTC, bhalevy commented
I like the direction but this doesn't work as is due to @xemul latest changes.
When testing this patch using:
```
SCYLLA_EXT_OPTS="--smp 2 --abort-on-internal-error 1 --logger-log-level table=debug:storage_service=debug"; pytest -s -vv --cassandra-dir=$scylla_dir/build/$mode update_cluster_layout_tests.py::TestUpdateClusterLayout::test_change_node_ip
```

The first node fails to boot:
```
ERROR 2022-11-09 07:04:10,601 [shard 0] token_metadata - token_metadata_impl: 127.0.1.1 must be member to update normal tokens, at: 0x148013d0 0x1ce2f7ed 0x1ce2f4ad 0x1ce31aa3 0x1ce32932 0x1bebc81e 0x1bebc10e 0x190b3ff7 0x190bd701 0x1926dace 0x1926d5de 0x1926d4d3 0x1926d348 0x19365473 0x1930adcf 0x15001b8d 0x15001968 0x1bfce07e 0x1bfd44ee 0x1bfd9152 0x1bfd6cc1 0x1bd75971 0x1bd734d5 0x14898538 0x14e071b6 0x14e070eb 0x14e06f55 0x14978a3d 0x14896ba0 /lib64/libc.so.6+0x27b74 0x147b54ad
```

Decoded:
```
[Backtrace #0]
__interceptor_backtrace.part.0 at crtstuff.c:?
void seastar::backtrace<seastar::current_backtrace_tasklocal()::$_3>(seastar::current_backtrace_tasklocal()::$_3&&) at ./build/debug/seastar/./seastar/include/seastar/util/backtrace.hh:59
seastar::current_backtrace_tasklocal() at ./build/debug/seastar/./seastar/src/util/backtrace.cc:86
seastar::current_tasktrace() at ./build/debug/seastar/./seastar/src/util/backtrace.cc:137
seastar::current_backtrace() at ./build/debug/seastar/./seastar/src/util/backtrace.cc:170
log_error_and_backtrace(seastar::logger&, std::basic_string_view<char, std::char_traits<char> >) at ./build/debug/seastar/./seastar/src/core/on_internal_error.cc:37
seastar::on_internal_error(seastar::logger&, std::basic_string_view<char, std::char_traits<char> >) at ./build/debug/seastar/./seastar/src/core/on_internal_error.cc:42
locator::token_metadata_impl::update_normal_tokens(std::unordered_set<dht::token, std::hash<dht::token>, std::equal_to<dht::token>, std::allocator<dht::token> >, gms::inet_address) at ./locator/token_metadata.cc:426
locator::token_metadata::update_normal_tokens(std::unordered_set<dht::token, std::hash<dht::token>, std::equal_to<dht::token>, std::allocator<dht::token> >, gms::inet_address) at ./locator/token_metadata.cc:990
operator() at ./service/storage_service.cc:544
seastar::future<void> std::__invoke_impl<seastar::future<void>, service::storage_service::join_token_ring(cdc::generation_service&, seastar::sharded<db::system_distributed_keyspace>&, seastar::sharded<service::storage_proxy>&, std::unordered_set<gms::inet_address, std::hash<gms::inet_address>, std::equal_to<gms::inet_address>, std::allocator<gms::inet_address> >, std::unordered_set<gms::inet_address, std::hash<gms::inet_address>, std::equal_to<gms::inet_address>, std::allocator<gms::inet_address> >, std::unordered_map<gms::inet_address, seastar::basic_sstring<char, unsigned int, 15u, true>, std::hash<gms::inet_address>, std::equal_to<gms::inet_address>, std::allocator<std::pair<gms::inet_address const, seastar::basic_sstring<char, unsigned int, 15u, true> > > >, std::chrono::duration<long, std::ratio<1l, 1000l> >)::$_2&, seastar::lw_shared_ptr<locator::token_metadata> >(std::__invoke_other, service::storage_service::join_token_ring(cdc::generation_service&, seastar::sharded<db::system_distributed_keyspace>&, seastar::sharded<service::storage_proxy>&, std::unordered_set<gms::inet_address, std::hash<gms::inet_address>, std::equal_to<gms::inet_address>, std::allocator<gms::inet_address> >, std::unordered_set<gms::inet_address, std::hash<gms::inet_address>, std::equal_to<gms::inet_address>, std::allocator<gms::inet_address> >, std::unordered_map<gms::inet_address, seastar::basic_sstring<char, unsigned int, 15u, true>, std::hash<gms::inet_address>, std::equal_to<gms::inet_address>, std::allocator<std::pair<gms::inet_address const, seastar::basic_sstring<char, unsigned int, 15u, true> > > >, std::chrono::duration<long, std::ratio<1l, 1000l> >)::$_2&, seastar::lw_shared_ptr<locator::token_metadata>&&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:61
std::enable_if<is_invocable_r_v<seastar::future<void>, service::storage_service::join_token_ring(cdc::generation_service&, seastar::sharded<db::system_distributed_keyspace>&, seastar::sharded<service::storage_proxy>&, std::unordered_set<gms::inet_address, std::hash<gms::inet_address>, std::equal_to<gms::inet_address>, std::allocator<gms::inet_address> >, std::unordered_set<gms::inet_address, std::hash<gms::inet_address>, std::equal_to<gms::inet_address>, std::allocator<gms::inet_address> >, std::unordered_map<gms::inet_address, seastar::basic_sstring<char, unsigned int, 15u, true>, std::hash<gms::inet_address>, std::equal_to<gms::inet_address>, std::allocator<std::pair<gms::inet_address const, seastar::basic_sstring<char, unsigned int, 15u, true> > > >, std::chrono::duration<long, std::ratio<1l, 1000l> >)::$_2&, seastar::lw_shared_ptr<locator::token_metadata> >, seastar::future<void> >::type std::__invoke_r<seastar::future<void>, service::storage_service::join_token_ring(cdc::generation_service&, seastar::sharded<db::system_distributed_keyspace>&, seastar::sharded<service::storage_proxy>&, std::unordered_set<gms::inet_address, std::hash<gms::inet_address>, std::equal_to<gms::inet_address>, std::allocator<gms::inet_address> >, std::unordered_set<gms::inet_address, std::hash<gms::inet_address>, std::equal_to<gms::inet_address>, std::allocator<gms::inet_address> >, std::unordered_map<gms::inet_address, seastar::basic_sstring<char, unsigned int, 15u, true>, std::hash<gms::inet_address>, std::equal_to<gms::inet_address>, std::allocator<std::pair<gms::inet_address const, seastar::basic_sstring<char, unsigned int, 15u, true> > > >, std::chrono::duration<long, std::ratio<1l, 1000l> >)::$_2&, seastar::lw_shared_ptr<locator::token_metadata> >(service::storage_service::join_token_ring(cdc::generation_service&, seastar::sharded<db::system_distributed_keyspace>&, seastar::sharded<service::storage_proxy>&, std::unordered_set<gms::inet_address, std::hash<gms::inet_address>, std::equal_to<gms::inet_address>, std::allocator<gms::inet_address> >, std::unordered_set<gms::inet_address, std::hash<gms::inet_address>, std::equal_to<gms::inet_address>, std::allocator<gms::inet_address> >, std::unordered_map<gms::inet_address, seastar::basic_sstring<char, unsigned int, 15u, true>, std::hash<gms::inet_address>, std::equal_to<gms::inet_address>, std::allocator<std::pair<gms::inet_address const, seastar::basic_sstring<char, unsigned int, 15u, true> > > >, std::chrono::duration<long, std::ratio<1l, 1000l> >)::$_2&, seastar::lw_shared_ptr<locator::token_metadata>&&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:114
std::_Function_handler<seastar::future<void> (seastar::lw_shared_ptr<locator::token_metadata>), service::storage_service::join_token_ring(cdc::generation_service&, seastar::sharded<db::system_distributed_keyspace>&, seastar::sharded<service::storage_proxy>&, std::unordered_set<gms::inet_address, std::hash<gms::inet_address>, std::equal_to<gms::inet_address>, std::allocator<gms::inet_address> >, std::unordered_set<gms::inet_address, std::hash<gms::inet_address>, std::equal_to<gms::inet_address>, std::allocator<gms::inet_address> >, std::unordered_map<gms::inet_address, seastar::basic_sstring<char, unsigned int, 15u, true>, std::hash<gms::inet_address>, std::equal_to<gms::inet_address>, std::allocator<std::pair<gms::inet_address const, seastar::basic_sstring<char, unsigned int, 15u, true> > > >, std::chrono::duration<long, std::ratio<1l, 1000l> >)::$_2>::_M_invoke(std::_Any_data const&, seastar::lw_shared_ptr<locator::token_metadata>&&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:290
std::function<seastar::future<void> (seastar::lw_shared_ptr<locator::token_metadata>)>::operator()(seastar::lw_shared_ptr<locator::token_metadata>) const at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:590
service::s [...]

2022-11-09 06:29 UTC, asias commented
> I like the direction but this doesn't work as is due to @xemul latest changes. When testing this patch using:
> 
> ```
> export SCYLLA_EXT_OPTS="--smp 2 --abort-on-internal-error 1 --logger-log-level table=debug:storage_service=debug"; pytest -s -vv --cassandra-dir=$scylla_dir/build/$mode update_cluster_layout_tests.py::TestUpdateClusterLayout::test_change_node_ip
> ```
> 
> The first node fails to boot:
> 
> ```
> ERROR 2022-11-09 07:04:10,601 [shard 0] token_metadata - token_metadata_impl: 127.0.1.1 must be member to update normal tokens, at: 0x148013d0 0x1ce2f7ed 0x1ce2f4ad 0x1ce31aa3 0x1ce32932 0x1bebc81e 0x1bebc10e 0x190b3ff7 0x190bd701 0x1926dace 0x1926d5de 0x1926d4d3 0x1926d348 0x19365473 0x1930adcf 0x15001b8d 0x15001968 0x1bfce07e 0x1bfd44ee 0x1bfd9152 0x1bfd6cc1 0x1bd75971 0x1bd734d5 0x14898538 0x14e071b6 0x14e070eb 0x14e06f55 0x14978a3d 0x14896ba0 /lib64/libc.so.6+0x27b74 0x147b54ad
> ```
> 
> Decoded:
> 
> ```
> [Backtrace #0]
> __interceptor_backtrace.part.0 at crtstuff.c:?
> void seastar::backtrace<seastar::current_backtrace_tasklocal()::$_3>(seastar::current_backtrace_tasklocal()::$_3&&) at ./build/debug/seastar/./seastar/include/seastar/util/backtrace.hh:59
> seastar::current_backtrace_tasklocal() at ./build/debug/seastar/./seastar/src/util/backtrace.cc:86
> seastar::current_tasktrace() at ./build/debug/seastar/./seastar/src/util/backtrace.cc:137
> seastar::current_backtrace() at ./build/debug/seastar/./seastar/src/util/backtrace.cc:170
> log_error_and_backtrace(seastar::logger&, std::basic_string_view<char, std::char_traits<char> >) at ./build/debug/seastar/./seastar/src/core/on_internal_error.cc:37
> seastar::on_internal_error(seastar::logger&, std::basic_string_view<char, std::char_traits<char> >) at ./build/debug/seastar/./seastar/src/core/on_internal_error.cc:42
> locator::token_metadata_impl::update_normal_tokens(std::unordered_set<dht::token, std::hash<dht::token>, std::equal_to<dht::token>, std::allocator<dht::token> >, gms::inet_address) at ./locator/token_metadata.cc:426
> locator::token_metadata::update_normal_tokens(std::unordered_set<dht::token, std::hash<dht::token>, std::equal_to<dht::token>, std::allocator<dht::token> >, gms::inet_address) at ./locator/token_metadata.cc:990
> operator() at ./service/storage_service.cc:544
> seastar::future<void> std::__invoke_impl<seastar::future<void>, service::storage_service::join_token_ring(cdc::generation_service&, seastar::sharded<db::system_distributed_keyspace>&, seastar::sharded<service::storage_proxy>&, std::unordered_set<gms::inet_address, std::hash<gms::inet_address>, std::equal_to<gms::inet_address>, std::allocator<gms::inet_address> >, std::unordered_set<gms::inet_address, std::hash<gms::inet_address>, std::equal_to<gms::inet_address>, std::allocator<gms::inet_address> >, std::unordered_map<gms::inet_address, seastar::basic_sstring<char, unsigned int, 15u, true>, std::hash<gms::inet_address>, std::equal_to<gms::inet_address>, std::allocator<std::pair<gms::inet_address const, seastar::basic_sstring<char, unsigned int, 15u, true> > > >, std::chrono::duration<long, std::ratio<1l, 1000l> >)::$_2&, seastar::lw_shared_ptr<locator::token_metadata> >(std::__invoke_other, service::storage_service::join_token_ring(cdc::generation_service&, seastar::sharded<db::system_distributed_keyspace>&, seastar::sharded<service::storage_proxy>&, std::unordered_set<gms::inet_address, std::hash<gms::inet_address>, std::equal_to<gms::inet_address>, std::allocator<gms::inet_address> >, std::unordered_set<gms::inet_address, std::hash<gms::inet_address>, std::equal_to<gms::inet_address>, std::allocator<gms::inet_address> >, std::unordered_map<gms::inet_address, seastar::basic_sstring<char, unsigned int, 15u, true>, std::hash<gms::inet_address>, std::equal_to<gms::inet_address>, std::allocator<std::pair<gms::inet_address const, seastar::basic_sstring<char, unsigned int, 15u, true> > > >, std::chrono::duration<long, std::ratio<1l, 1000l> >)::$_2&, seastar::lw_shared_ptr<locator::token_metadata>&&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:61
> std::enable_if<is_invocable_r_v<seastar::future<void>, service::storage_service::join_token_ring(cdc::generation_service&, seastar::sharded<db::system_distributed_keyspace>&, seastar::sharded<service::storage_proxy>&, std::unordered_set<gms::inet_address, std::hash<gms::inet_address>, std::equal_to<gms::inet_address>, std::allocator<gms::inet_address> >, std::unordered_set<gms::inet_address, std::hash<gms::inet_address>, std::equal_to<gms::inet_address>, std::allocator<gms::inet_address> >, std::unordered_map<gms::inet_address, seastar::basic_sstring<char, unsigned int, 15u, true>, std::hash<gms::inet_address>, std::equal_to<gms::inet_address>, std::allocator<std::pair<gms::inet_address const, seastar::basic_sstring<char, unsigned int, 15u, true> > > >, std::chrono::duration<long, std::ratio<1l, 1000l> >)::$_2&, seastar::lw_shared_ptr<locator::token_metadata> >, seastar::future<void> >::type std::__invoke_r<seastar::future<void>, service::storage_service::join_token_ring(cdc::generation_service&, seastar::sharded<db::system_distributed_keyspace>&, seastar::sharded<service::storage_proxy>&, std::unordered_set<gms::inet_address, std::hash<gms::inet_address>, std::equal_to<gms::inet_address>, std::allocator<gms::inet_address> >, std::unordered_set<gms::inet_address, std::hash<gms::inet_address>, std::equal_to<gms::inet_address>, std::allocator<gms::inet_address> >, std::unordered_map<gms::inet_address, seastar::basic_sstring<char, unsigned int, 15u, true>, std::hash<gms::inet_address>, std::equal_to<gms::inet_address>, std::allocator<std::pair<gms::inet_address const, seastar::basic_sstring<char, unsigned int, 15u, true> > > >, std::chrono::duration<long, std::ratio<1l, 1000l> >)::$_2&, seastar::lw_shared_ptr<locator::token_metadata> >(service::storage_service::join_token_ring(cdc::generation_service&, seastar::sharded<db::system_distributed_keyspace>&, seastar::sharded<service::storage_proxy>&, std::unordered_set<gms::inet_address, std::hash<gms::inet_address>, std::equal_to<gms::inet_address>, std::allocator<gms::inet_address> >, std::unordered_set<gms::inet_address, std::hash<gms::inet_address>, std::equal_to<gms::inet_address>, std::allocator<gms::inet_address> >, std::unordered_map<gms::inet_address, seastar::basic_sstring<char, unsigned int, 15u, true>, std::hash<gms::inet_address>, std::equal_to<gms::inet_address>, std::allocator<std::pair<gms::inet_address const, seastar::basic_sstring<char, unsigned int, 15u, true> > > >, std::chrono::duration<long, std::ratio<1l, 1000l> >)::$_2&, seastar::lw_shared_ptr<locator::token_metadata>&&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:114
> std::_Function_handler<seastar::future<void> (seastar::lw_shared_ptr<locator::token_metadata>), service::storage_service::join_token_ring(cdc::generation_service&, seastar::sharded<db::system_distributed_keyspace>&, seastar::sharded<service::storage_proxy>&, std::unordered_set<gms::inet_address, std::hash<gms::inet_address>, std::equal_to<gms::inet_address>, std::allocator<gms::inet_address> >, std::unordered_set<gms::inet_address, std::hash<gms::inet_address>, std::equal_to<gms::inet_address>, std::allocator<gms::inet_address> >, std::unordered_map<gms::inet_address, seastar::basic_sstring<char, unsigned int, 15u, true>, std::hash<gms::inet_address>, std::equal_to<gms::inet_address>, std::allocator<std::pair<gms::inet_address const, seastar::basic_sstring<char, unsigned int, 15u, true> > > >, std::chrono::duration<long, std::ratio<1l, 1000l> >)::$_2>::_M_invoke(std::_Any_data const&, seastar::lw_shared_ptr<locator::token_metadata>&&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:290
> std::function<seastar::future<void> (seastar::lw_shared_ptr<locator::token_metadata>)>::operator()(seastar::lw_shared_ptr<locator::token_metadata>) const at /usr/lib/gcc/x86_64-redhat- [...]

2022-11-09 06:35 UTC, asias commented
Changes in v2:
- Modify token_metadata_impl::update_normal_tokens to check the topology directly

2022-11-09 08:14 UTC, bhalevy approved these changes
LGTM

@xemul please review too

2022-11-09 09:52 UTC, scylladb-promoter commented
CI state **`SUCCESS`** - https://jenkins.scylladb.com/job/releng/job/Scylla-CI/2907/

2022-11-09 11:23 UTC, xemul commented
Do `token_metadata::_normal_token_owners` and  `topology::_current_locations` contain identical set of endpoints? According to this PR they do. In this case -- why should the former be preferred? I'd rather drop this set and stick to using the latter.

2022-11-09 11:40 UTC, asias commented
> Do `token_metadata::_normal_token_owners` and `topology::_current_locations` contain identical set of endpoints? According to this PR they do. In this case -- why should the former be preferred? I'd rather drop this set and stick to using the latter.

They might be the same or not be the same. It depends on how  strict we maintain the topology info. For example, a node might not be in the token ring, but we still have the dc/rack info in topology.

The point is we should prefer the source of truth. For checking if a node is part of the ring or not, _normal_token_owners (which follows _token_to_endpoint_map) is the source of truth.

2022-11-09 12:34 UTC, xemul commented
> They might be the same or not be the same.

So does this change actually _changes_ something? The old check could report `true` but new one would return `false` or vice-versa?

> It depends on how strict we maintain the topology info. For example, a node might not be in the token ring, but we still have the dc/rack info in topology.

For those there a thing called `_pending_locations` in topology, so it clearly distinguishes nodes that are in the ring from those that are entering/leaving it. Why is normal-token-owners better?

> 
> The point is we should prefer the source of truth. 

Agree.

> For checking if a node is part of the ring or not, _normal_token_owners (which follows _token_to_endpoint_map) is the source of truth.

Why? Current state of art is that `is_member()` looks up the topology for the answer and thus it's de-facto source of truth. 

This PR makes this place to look up somewhere else -- in "normal-token-owners". If this change is idempotent, then it's a replacement of the current source of truth with something else for no reason. If this change really changes something, then it should either fix a BUG or introduce a regression. So what does it do?

2022-11-09 13:49 UTC, asias commented
> > They might be the same or not be the same.
> 
> So does this change actually _changes_ something? The old check could report `true` but new one would return `false` or vice-versa?
> 
> > It depends on how strict we maintain the topology info. For example, a node might not be in the token ring, but we still have the dc/rack info in topology.
> 
> For those there a thing called `_pending_locations` in topology, so it clearly distinguishes nodes that are in the ring from those that are entering/leaving it. Why is normal-token-owners better?

Because if we look up normal-token-owners, it always gives the correct answer, no matter if topology is updated correctly or not. 

> 
> > The point is we should prefer the source of truth.
> 
> Agree.
> 
> > For checking if a node is part of the ring or not, _normal_token_owners (which follows _token_to_endpoint_map) is the source of truth.
> 
> Why? Current state of art is that `is_member()` looks up the topology for the answer and thus it's de-facto source of truth.

The reason is_member() looked at topology is simply because there was no efficient way to do the look up (we only have _token_to_endpoint_map). The wrong decision in the past is not going to make it the source of truth. 

> This PR makes this place to look up somewhere else -- in "normal-token-owners". If this change is idempotent, then it's a replacement of the current source of truth with something else for no reason. If this change really changes something, then it should either fix a BUG or introduce a regression. So what does it do?

The is_member check has nothing to do with topology. The patch corrects it.

2022-11-09 14:58 UTC, xemul commented
> > For those there a thing called `_pending_locations` in topology, so it clearly distinguishes nodes that are in the ring from those that are entering/leaving it. Why is normal-token-owners better?
> 
> Because if we look up normal-token-owners, it always gives the correct answer, no matter if topology is updated correctly or not.

Is topology missing an info for an endpoint in normal_token_owners? Or does it contain info (in current_locations) for an endpoint that's not on normal_token_owners? Is there an issue for it?

In fact, if a code looked up an endpoint, from gossiper or from normal-token-owners, then chances that dc/rack will be asked for that node immediately is quite high, so the topology info mustn't be incorrect or outdated.

> > > For checking if a node is part of the ring or not, _normal_token_owners (which follows _token_to_endpoint_map) is the source of truth.
> > 
> > 
> > Why? Current state of art is that `is_member()` looks up the topology for the answer and thus it's de-facto source of truth.
> 
> The reason is_member() looked at topology is simply because there was no efficient way to do the look up (we only have _token_to_endpoint_map). The wrong decision in the past is not going to make it the source of truth.
 _and_ own normal tokens 

I don't get why it is wrong now. The topology stores all the nodes that are in the cluster in current-locations. Other nodes that might be accessed, but not owning normal tokens are in the pending-locations.

> > This PR makes this place to look up somewhere else -- in "normal-token-owners". If this change is idempotent, then it's a replacement of the current source of truth with something else for no reason. If this change really changes something, then it should either fix a BUG or introduce a regression. So what does it do?
> 
> The is_member check has nothing to do with topology. The patch corrects it.

That's what I'm asking -- why does it have nothing to do with topology? As far as I can tell, topology is populated "in-sync" with tokens, if there's any place that makes it out-of-sync, please tell where it is.

2022-11-10 01:14 UTC, asias commented
> > > For those there a thing called `_pending_locations` in topology, so it clearly distinguishes nodes that are in the ring from those that are entering/leaving it. Why is normal-token-owners better?
> > 
> > 
> > Because if we look up normal-token-owners, it always gives the correct answer, no matter if topology is updated correctly or not.
> 
> Is topology missing an info for an endpoint in normal_token_owners? Or does it contain info (in current_locations) for an endpoint that's not on normal_token_owners? Is there an issue for it?
> 
> In fact, if a code looked up an endpoint, from gossiper or from normal-token-owners, then chances that dc/rack will be asked for that node immediately is quite high, so the topology info mustn't be incorrect or outdated.
> 
> > > > For checking if a node is part of the ring or not, _normal_token_owners (which follows _token_to_endpoint_map) is the source of truth.
> > > 
> > > 
> > > Why? Current state of art is that `is_member()` looks up the topology for the answer and thus it's de-facto source of truth.
> > 
> > 
> > The reason is_member() looked at topology is simply because there was no efficient way to do the look up (we only have _token_to_endpoint_map). The wrong decision in the past is not going to make it the source of truth.
> > _and_ own normal tokens
> 
> I don't get why it is wrong now. The topology stores all the nodes that are in the cluster in current-locations. Other nodes that might be accessed, but not owning normal tokens are in the pending-locations.
> 
> > > This PR makes this place to look up somewhere else -- in "normal-token-owners". If this change is idempotent, then it's a replacement of the current source of truth with something else for no reason. If this change really changes something, then it should either fix a BUG or introduce a regression. So what does it do?
> > 
> > 
> > The is_member check has nothing to do with topology. The patch corrects it.
> 
> That's what I'm asking -- why does it have nothing to do with topology? As far as I can tell, topology is populated "in-sync" with tokens, if there's any place that makes it out-of-sync, please tell where it is.


Let me explain. The dc and rack info in topology is a property of the nodes.
It is not something that decides if a node is part of the ring or not. The fact
today the topology happens to be in sync does not justify we should check
topology to get the answer if a node is part of the ring.

For example, in theory, we could leave the removed node in _topology and not
remove it immediately. We relax the "in-sync" requirement. This is supposed to
be correct, because we should only care about if we could find the dc / rack
info for the node that is part of the ring. It does not matter if there are dc
/ rack info for more nodes than necessary.

Another example, with SimpleStrategy, we do not even need the dc / rack info in
topology. No need to consult _topology for part of the ring check. 
    
Suppose we need to maintain another property of nodes in addition to the dc / rack:

```
std::unordered_map<gms::inet_address, float> _load
```
    
in token_metadata. This _load is implemented as in-sync with the membership. 

Now should we do:
    
```
bool is_member(node) {
   _load.contains(node)
}
```


Oh, I just saw that you added _pending_locations to topology. This is a bigger
problem. This whole pending in topology logic is unnecessary to me. Topology
containing the rack / dc should not be aware of the pending at all. The pending
stuff in topology is due to fact that we try to maintain the ring membership
in topology which is unnecessary.

2022-11-11 12:54 UTC, xemul commented
@asias , what you say makes perfect sense.

> Suppose we need to maintain another property of nodes in addition to the dc / rack:
> 
>      std::unordered_map<gms::inet_address, float> _load
> 
> in token_metadata. This _load is implemented as in-sync with the membership.

Note, that the same can be applied even to tokens. Like this

"
  Suppose we need to maintain another property of nodes in addition to the dc / rack:

     std::unordered_map<gms::inet_address, std::set<dht::token>> _tokens

 in token_metadata. This _tokens is implemented as in-sync with the membership.
"

This makes sense too.

I agree with @bhalevy -- currently there's no good and solid source of truth about nodes membership in the cluster. This info is now scattered over and maintained by simultaneously gossiper, token-metadata, topology, e.r.m., storage_service and raft. The token_metadata is the place where node<->tokens mapping is stored, nothing more. I agree to turn "topology" (back) into to a place where node<->dc/rack mapping is stored and nothing more, but this still calls for correct cluster layout management service/component.

2022-11-14 02:13 UTC, asias commented
> @asias , what you say makes perfect sense.
> 
> > Suppose we need to maintain another property of nodes in addition to the dc / rack:
> > ```
> >  std::unordered_map<gms::inet_address, float> _load
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > in token_metadata. This _load is implemented as in-sync with the membership.
> 
> Note, that the same can be applied even to tokens. Like this
> 
> " Suppose we need to maintain another property of nodes in addition to the dc / rack:
> 
> ```
>  std::unordered_map<gms::inet_address, std::set<dht::token>> _tokens
> ```
> 
> in token_metadata. This _tokens is implemented as in-sync with the membership. "
> 
> This makes sense too.
> 
> I agree with @bhalevy -- currently there's no good and solid source of truth about nodes membership in the cluster. This info is now scattered over and maintained by simultaneously gossiper, token-metadata, topology, e.r.m., storage_service and raft. The token_metadata is the place where node<->tokens mapping is stored, nothing more. I agree to turn "topology" (back) into to a place where node<->dc/rack mapping is stored and nothing more, but this still calls for correct cluster layout management service/component.

Yes. Right now, gossip learns the topology, then it updates token metadata. token_metadata is the source of truth about the node membership. We do have multiple representations in token_metadata_impl::{_token_to_endpoint_map, _normal_token_owners, _endpoint_to_host_id_map, _sorted_tokens} for different reasons,  which makes token_metadata complicated. 

We can do two things:

1) Improve token_metadata itself to organize membership better
2) Turn all other places use the token_metadata for membership directly

For example, we do have helpers in other places like: get_live_token_owners and get_unreachable_token_owners from gossip. In https://github.com/scylladb/scylladb/pull/11952, I am trying to make it use token_metadata directly.

2022-11-14 08:16 UTC, bhalevy requested changes
LGTM overall, just please add documentation in token_metadata.hh for is_member
(and as a followup we need better documentation for is_leaving)

2022-11-14 11:30 UTC, xemul commented
> Yes. Right now, gossip learns the topology, then it updates token metadata. token_metadata is the source of truth about the node membership. We do have multiple representations in token_metadata_impl::{_token_to_endpoint_map, _normal_token_owners, _endpoint_to_host_id_map, _sorted_tokens} for different reasons, which makes token_metadata complicated.
> 
> We can do two things:
> 
>     Improve token_metadata itself to organize membership better
>     Turn all other places use the token_metadata for membership directly
> 
> For example, we do have helpers in other places like: get_live_token_owners and get_unreachable_token_owners from gossip. In https://github.com/scylladb/scylladb/pull/11952, I am trying to make it use token_metadata directly.

BTW, if this set renamed `token_metadata::is_member()` into `token_metadata::is_normal_token_owner` I'd just go ahead and merge it :) as the new name would give a clear message that it's just normal token owners, and cluster membership _might_ be not just that. 

Current attempt to make the topology object be the membership tracker is of-course not finished. Maybe the "ownership tracker" @bhalevy is talking about should be not topology, but something else (I don't think token_metadata is the one though). Anyway, this set makes this incompleteness worse. I propose to either rename the `is_member()` as I suggested above, or take `token_metadata::_normal_token_owners` and `topology::_pending_locations` and leave only one of them. I've a draft branch that does the latter, that I didn't have enough time to test. But I won't mind if `topology::_pending_locations` would be removed -- it would be step backward, but _the_ _whole_ step backward, not half-step.

2022-11-14 11:42 UTC, bhalevy commented
> > Yes. Right now, gossip learns the topology, then it updates token metadata. token_metadata is the source of truth about the node membership. We do have multiple representations in token_metadata_impl::{_token_to_endpoint_map, _normal_token_owners, _endpoint_to_host_id_map, _sorted_tokens} for different reasons, which makes token_metadata complicated.
> > We can do two things:
> > ```
> > Improve token_metadata itself to organize membership better
> > Turn all other places use the token_metadata for membership directly
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > For example, we do have helpers in other places like: get_live_token_owners and get_unreachable_token_owners from gossip. In #11952, I am trying to make it use token_metadata directly.
> 
> BTW, if this set renamed `token_metadata::is_member()` into `token_metadata::is_normal_token_owner` I'd just go ahead and merge it :) as the new name would give a clear message that it's just normal token owners, and cluster membership _might_ be not just that.
> 
> Current attempt to make the topology object be the membership tracker is of-course not finished. Maybe the "ownership tracker" @bhalevy is talking about should be not topology, but something else (I don't think token_metadata is the one though). Anyway, this set makes this incompleteness worse. I propose to either rename the `is_member()` as I suggested above, or take `token_metadata::_normal_token_owners` and `topology::_pending_locations` and leave only one of them. I've a draft branch that does the latter, that I didn't have enough time to test. But I won't mind if `topology::_pending_locations` would be removed -- it would be step backward, but _the_ _whole_ step backward, not half-step.

FWIW, here's my WIP branch: https://github.com/bhalevy/scylla/commits/topology-class-node
It includes the changes in this PR so that is_member will work.

Based on this infrastructure we can continue to move more state into class node
and rely on the nodes state in the topology registry to determine if nodes are normal members of the ring, or leaving / joining / left, etc.

I think this infrastructure is more suitable than today's topology state which just includes current/pending.

2022-11-14 12:16 UTC, xemul commented
I like this patch: https://github.com/bhalevy/scylla/commit/e7db0820a8328fb312c86eae0b5cd8b80a30896d :) It took me some time to remember that `class topology` didn't sit in `topology.hh`, but rather in `token_metadata.hh` :D so after it I will be able to unlearn back

2022-11-15 02:30 UTC, asias commented
> > Yes. Right now, gossip learns the topology, then it updates token metadata. token_metadata is the source of truth about the node membership. We do have multiple representations in token_metadata_impl::{_token_to_endpoint_map, _normal_token_owners, _endpoint_to_host_id_map, _sorted_tokens} for different reasons, which makes token_metadata complicated.
> > We can do two things:
> > ```
> > Improve token_metadata itself to organize membership better
> > Turn all other places use the token_metadata for membership directly
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > For example, we do have helpers in other places like: get_live_token_owners and get_unreachable_token_owners from gossip. In #11952, I am trying to make it use token_metadata directly.
> 
> BTW, if this set renamed `token_metadata::is_member()` into `token_metadata::is_normal_token_owner` I'd just go ahead and merge it :) as the new name would give a clear message that it's just normal token owners, and cluster membership _might_ be not just that.
> 
> Current attempt to make the topology object be the membership tracker is of-course not finished. Maybe the "ownership tracker" @bhalevy is talking about should be not topology, but something else (I don't think token_metadata is the one though). Anyway, this set makes this incompleteness worse. I propose to either rename the `is_member()` as I suggested above, or take `token_metadata::_normal_token_owners` and `topology::_pending_locations` and leave only one of them. I've a draft branch that does the latter, that I didn't have enough time to test. But I won't mind if `topology::_pending_locations` would be removed -- it would be step backward, but _the_ _whole_ step backward, not half-step.

I like the renaming idea, but let's do the renaming later after https://github.com/scylladb/scylladb/pull/11952 and separately to avoid unnecessary conflicts. 

I think we'd better drop the  topology::_pending_locations thing.

2022-11-15 02:39 UTC, asias commented
Changes in v2:
- Add doc for is_member to make it clear what it really checks

2022-11-15 05:34 UTC, scylladb-promoter commented
CI state **`SUCCESS`** - https://jenkins.scylladb.com/job/releng/job/Scylla-CI/2991/

2022-11-17 11:33 UTC, avikivity commented
@xemul please review. It looks okay to me but it deals with subtle topics you're more familiar with.

2022-11-17 11:33 UTC, avikivity approved these changes

2022-11-17 11:44 UTC, xemul commented
I had a concern (method name) that Asias agreed to address after #11952 gets merged. It's now in master, so I'm waiting for the update on this PR.

> I think we'd better drop the topology::_pending_locations thing.

@asias , if you could also include this in the update, that'd be awesome

2022-11-17 12:30 UTC, asias commented
> I had a concern (method name) that Asias agreed to address after #11952 gets merged. It's now in master, so I'm waiting for the update on this PR.

I will send a separate PR for the renaming. 

> 
> > I think we'd better drop the topology::_pending_locations thing.
> 
> @asias , if you could also include this in the update, that'd be awesome

Since Benny is working on the refactor, I am not going to do that.

2022-11-17 12:43 UTC, xemul commented
> I will send a separate PR for the renaming.

Please, do it here, the renaming is related to the is_member()'s body change

2022-11-18 01:30 UTC, asias commented
Changes in v3:
- Rename is_member to is_normal_token_owner
- Rebase

2022-11-18 01:31 UTC, asias commented
> > I will send a separate PR for the renaming.
> 
> Please, do it here, the renaming is related to the is_member()'s body change

OK. See v3.

2022-11-18 06:17 UTC, scylladb-promoter commented
CI state **`SUCCESS`** - https://jenkins.scylladb.com/job/releng/job/Scylla-CI/3058/

2022-11-18 23:00 UTC, closed without merging