alternator: fix hangs related to TTL scanning
scylladb/scylladb pull request #12152
Opened 2022-11-30 15:35 UTC by nyh

The first patch in this small series fixes a hang during shutdown when the expired-item scanning thread can hang in a retry loop instead of quitting.  These hangs were seen in some test runs (issue #12145).

The second patch is a failsafe against additional bugs like those solved by the first patch: If any bugs causes the same page fetch to repeatedly time out, let's stop the attempts after 10 retries instead of retrying for ever. When we stop the retries, a warning will be printed to the log, Scylla will wait until the next scan period and start a new scan from scratch - from a random position in the database, instead of hanging potentially-forever waiting for the same page.

2022-11-30 15:36 UTC, nyh commented
@bhalevy the first patch should fix your https://github.com/scylladb/scylladb/issues/12145.
@nuivall the second patch is inspired by your review comment that an infinite retry is not a good idea. And indeed it wasn't.

2022-11-30 15:59 UTC, bhalevy requested changes

2022-11-30 15:59 UTC, bhalevy commented on alternator/ttl.cc
> +            if (abort_source.abort_requested()) {
co_await sleep_abortable will throw if timed out so the if statement won't be executed...

See https://github.com/scylladb/seastar/blob/96e566bdfee7fff493c7e25c869a2c252aabfac7/include/seastar/core/sleep.hh#L80

2022-11-30 16:44 UTC, nyh commented
v2: as @bhalevy noticed, it's enough to call sleep_abortable(), no need to separately check the abort source. If the abort source is triggered before or during the sleep, sleep_abortable will throw an exception, which will cause the current scan to stop.

2022-11-30 20:33 UTC, avikivity approved these changes

2022-11-30 21:51 UTC, scylladb-promoter commented
CI state **`SUCCESS`** - https://jenkins.scylladb.com/job/releng/job/Scylla-CI/3288/

2022-12-01 07:13 UTC, bhalevy approved these changes

2022-12-01 11:50 UTC, nuivall approved these changes

2022-12-05 21:13 UTC, nyh commented
ping @scylladb/scylla-maint - it seems everyone approved this patch, but nobody merged it :-)

2022-12-06 04:44 UTC, denesb approved these changes

2022-12-06 11:54 UTC, merged