Task manager api
scylladb/scylladb pull request #12338
Opened 2022-12-16 10:56 UTC by Deexie

The PR introduces changes to task manager api:
- extends tasks' list returned with get_tasks with task type,
   keyspace, table, entity, and sequence number
- extends status returned with get_task_status and wait_task
   with a list of children's ids

2022-12-16 15:27 UTC, scylladb-promoter commented
CI state **`SUCCESS`** - https://jenkins.scylladb.com/job/releng/job/Scylla-CI/3529/

2022-12-18 07:56 UTC, bhalevy commented
Please provide a more descriptive title for this PR.

2022-12-18 08:00 UTC, bhalevy requested changes
Looks good overall.  I've had only some minor comments

2022-12-19 13:35 UTC, Deexie commented
- changed child_tasks description
- child_tasks -> children_ids

2022-12-19 14:19 UTC, bhalevy approved these changes
LGTM overall.
Just please provide a more meaningful title to the GH issue

2022-12-19 17:05 UTC, scylladb-promoter commented
CI state **`SUCCESS`** - https://jenkins.scylladb.com/job/releng/job/Scylla-CI/3544/

2022-12-20 06:13 UTC, bhalevy commented
@scylladb/scylla-maint please consider merging

2022-12-20 15:07 UTC, avikivity commented
Dequeued, doesn't build. Try rebasing.

2022-12-21 10:02 UTC, Deexie commented
- rebased on master

2022-12-21 16:13 UTC, scylladb-promoter commented
CI state **`SUCCESS`** - https://jenkins.scylladb.com/job/releng/job/Scylla-CI/3569/

2022-12-29 14:31 UTC, bhalevy commented
@scylladb/scylla-maint please requeue the rebased branch

2023-01-04 14:28 UTC, closed without merging