docs/operating-scylla: add a document on diagnostic tools
scylladb/scylladb pull request #12503
Opened 2023-01-12 09:05 UTC by denesb

ScyllaDB has wide variety of tools and source of information useful for diagnosing problems. These are scattered all over the place and although most of these are documented, there is currently no document listing all the relevant tools and information sources when it comes to diagnosing a problem.
This patch adds just that: a document listing the different tools and information sources, with a brief description of how they can help in diagnosing problems, and a link to the releveant dedicated documentation pages.

2023-01-12 09:06 UTC, denesb commented
@annastuchlik I get this when doing `make preview`:
```
pickling environment... done                                                                                                   
checking consistency... /home/bdenes/ScyllaDB/scylla/worktree0/docs/operating-scylla/diagnostics.rst: WARNING: document isn't included in any toctree                                                                                                         
done
```
Not sure what to do to solve this.

2023-01-12 09:07 UTC, denesb commented
In this PR I used `ScyllaDB` everywhere, but I noticed that in `docs/operating-scylla/index.rst` we still use the old terminology (`Scylla`).  With my changes we now have both in the same document. Should I add a patch which brings this document up-to-date, so it is consistent?

2023-01-17 08:16 UTC, denesb commented
@annastuchlik  ping.

2023-01-27 12:53 UTC, denesb commented
@annastuchlik ping.

2023-01-31 07:02 UTC, denesb commented
ping

2023-01-31 07:30 UTC, tzach reviewed
Few minor comments.

General comment (not a showstopper):
The content is very useful, but the wording is more like a (long) blog post and less like a dry document reference (which we prefere on docs)

2023-01-31 07:30 UTC, tzach commented on docs/operating-scylla/diagnostics.rst
> +For the purpose of this document we will consider any tool or source of information, be that built-in or separate, that can be of help to diagnose a problem with ScyllaDB as a diagnostic tool.
```suggestion
For this document, we will consider any tool or source of information, be that built-in or separate, that can help to diagnose a problem with ScyllaDB as a diagnostic tool.
```

2023-01-31 07:30 UTC, tzach commented on docs/operating-scylla/diagnostics.rst
> +For the purpose of this document we will consider any tool or source of information, be that built-in or separate, that can be of help to diagnose a problem with ScyllaDB as a diagnostic tool.
Removing redudent wording

2023-01-31 07:30 UTC, tzach commented on docs/operating-scylla/diagnostics.rst
> +Note that by default monitoring shows information about the entire cluster and even when selecting a certain node, it aggeregates the counters from the node's shards.
```suggestion
Note that by default monitoring shows information about the entire cluster and even when selecting a certain node, it aggregates the counters from the node's shards.
```

2023-01-31 07:30 UTC, tzach commented on docs/operating-scylla/diagnostics.rst
> +Sometimes counter values aggerageted over all the shards or even over multiple or all nodes is what you want.
```suggestion
Sometimes counter values aggregated over all the shards or even over multiple or all nodes is what you want.
```

2023-01-31 07:30 UTC, tzach commented on docs/operating-scylla/diagnostics.rst
> +It however requires intimate knowledge of ScyllaDB internals to be really useful.
```suggestion
It however requires intimate knowledge of ScyllaDB internals to be  useful.
```

2023-01-31 08:29 UTC, denesb commented
v2:
* applied review suggestions
* rebased

2023-01-31 08:57 UTC, denesb commented
v3:
* added diagnostics.rst to toctree in operating-scylla/index.rst

2023-02-03 10:44 UTC, annastuchlik commented
@denesb I'm VERY sorry it took me so long to review this PR. And thank you for adding the content - I find it very useful. 

The article is very clear and well-organized, so I wouldn't change anything major. I'm just going to add several comments (as suggestions so that they can be easily applied) about the language.

2023-02-03 10:46 UTC, annastuchlik commented on docs/operating-scylla/diagnostics.rst
> +ScyllaDB has a wide selection of tools and information-sources available when it comes to diagnosing problems.
```suggestion
ScyllaDB has a wide selection of tools and information sources available for diagnosing problems.
```

2023-02-03 10:49 UTC, annastuchlik commented on docs/operating-scylla/diagnostics.rst
> +For this document, we will consider any tool or source of information, be that built-in or separate, that can help to diagnose a problem with ScyllaDB as a diagnostic tool.
```suggestion
This document covers both built-in and standalone tools that can help you diagnose a problem with ScyllaDB.
```

2023-02-03 10:52 UTC, annastuchlik commented on docs/operating-scylla/diagnostics.rst
> +On production systems ScyllaDB logs to syslog, thus logs can usually be viewed via ``journalctl``.
```suggestion
On production systems, ScyllaDB logs to syslog; thus logs can usually be viewed via ``journalctl``.
```

2023-02-03 10:54 UTC, annastuchlik commented on docs/operating-scylla/diagnostics.rst
> +Note that setting the log-level of even a single logger to ``debug`` or below, might generate a huge amount of log trafic.
```suggestion
Note that setting the log-level of even a single logger to ``debug`` or below might generate a huge amount of log traffic.
```

2023-02-03 10:57 UTC, annastuchlik commented on docs/operating-scylla/diagnostics.rst
> +Try to time the log-level bump to when an even of interest start and revert it quickly after, to avoid saturating your log.
```suggestion
Try to time the log-level bump to when an event of interest start and revert it quickly afterward to avoid saturating your log.
```

2023-02-03 10:58 UTC, annastuchlik commented on docs/operating-scylla/diagnostics.rst
> +That said, when it comes to diagnosing problems with a certain query, tracing is an excellent tool, allowing you to have a peak at what happens when that query is processed, including the timestamp o
```suggestion
That said, when it comes to diagnosing problems with a certain query, tracing is an excellent tool, allowing you to have a peek at what happens when that query is processed, including the timestamp of each event.
```

2023-02-03 10:59 UTC, annastuchlik commented on docs/operating-scylla/diagnostics.rst
> +It however requires intimate knowledge of ScyllaDB internals to be useful.
```suggestion
However, it requires intimate knowledge of ScyllaDB internals to be useful.
```

2023-02-03 11:00 UTC, annastuchlik commented on docs/operating-scylla/diagnostics.rst
> +ScyllaDB has a comprehensive monitoring and alerting solution, displaying the different counters from ScyllaDB and the underlying OS, as well as alerts for common problems and pit-falls.
```suggestion
ScyllaDB has a comprehensive monitoring and alerting solution, displaying the different counters from ScyllaDB and the underlying OS, as well as alerts for common problems and pitfalls.
```

2023-02-03 11:02 UTC, annastuchlik requested changes
I've left some suggestions for language improvements.

2023-02-06 07:13 UTC, denesb commented
v4:
* Applied suggestion from @annastuchlik

2023-02-06 11:02 UTC, annastuchlik approved these changes
LGTM

2023-02-09 08:48 UTC, denesb commented
@scylladb/scylla-maint ping.

2023-02-10 15:06 UTC, kbr-scylla approved these changes

2023-02-13 04:58 UTC, denesb commented
@scylladb/scylla-maint merge ping, bot @tzach and @annastuchlik approved.

2023-02-13 09:36 UTC, kbr-scylla commented
Shit, I merged locally but forgot to push next.

2023-02-13 09:37 UTC, kbr-scylla commented
Now it's queued :D

2023-02-14 03:12 UTC, closed without merging