dbuild: fix path in example in README
scylladb/scylladb pull request #12631
Opened 2023-01-24 13:27 UTC by nyh

The dbuild README has an example how to enable ccache, and required modifying the PATH. Since recently, our docker image includes required commands (cxxbridge) in /usr/local/bin, so the build will fail if that directory isn't also in the path - so add it in the example.

Signed-off-by: Nadav Har'El <nyh@scylladb.com>

2023-01-24 14:34 UTC, wmitros commented
I see recently there was a discussion about the PATH variable in dbuild at https://github.com/scylladb/scylladb/pull/10939.
Even though its main focus was using ccache by default, I see that we raised an issue there about hard-coding the PATH and @michoecho came up with [solutions](https://github.com/scylladb/scylladb/pull/10939#pullrequestreview-1027922217) that would help with it, but they ended up ignored/unnoticed.
Maybe it's worth considering that patch again, so that we don't have to make adjustments like this again

2023-01-24 16:12 UTC, mykaul commented
I (naively?) use '-e PATH=/usr/lib64/ccache/:$PATH' - isn't it good enough?

2023-01-24 16:27 UTC, michoecho commented
> I (naively?) use '-e PATH=/usr/lib64/ccache/:$PATH' - isn't it good enough?

I mean, if it works, it works, so it is "good enough". But in this case the $PATH is expanded to _your_ PATH, not the container's PATH. So your way is overriding whatever PATH is set by the default inside the container (and/or tweaked by dbuild).

Because your PATH is close enough to the PATH expected by the container, it works. But in principle you don't want to override with a container's internal PATH (except prepending/appending to it), it should be a black box.

2023-01-24 16:34 UTC, mykaul commented
Correct, both are F37.
Another thought - fix PATH via an ENV directive in the Dockerfile?

2023-01-24 16:49 UTC, michoecho commented
> Another thought - fix PATH via an ENV directive in the Dockerfile?

That works too. The choice depends on whether you want to "bake in" the ccache env into the image, or append it at invocation time.

2023-01-25 09:13 UTC, nyh commented
> I see recently there was a discussion about the PATH variable in dbuild at #10939. Even though its main focus was using ccache by default, I see that we also raised an issue there about hard-coding the PATH and @michoecho came up with [solutions](https://github.com/scylladb/scylladb/pull/10939#pullrequestreview-1027922217) that would help with it, but they ended up ignored/unnoticed. Maybe it's worth considering that patch again, so that we don't have to make adjustments like this again

I agree, but I think this is perhaps slightly too weird and complicated to be part of a README?

I think we should:
1. Apply my patch now - just because it corrects an existing error in the README. Maybe it's not the perfect solution, but at least it will prevent people from copying non-working ideas from the README.
2. Go back to doing something like https://github.com/scylladb/scylladb/pull/10939 (the second patch, with @michoecho 's suggested improvement) to always use ccache without copying tricks from the README. We can also have the dbuild detect automatically whether it should use ccache and not do it unconditionally - i.e., use ccache only if the host build machine uses it (i.e., if "clang" on the build machines points to ccache, we should also use ccache in the container). If there's interest let me know and I'll do it.

2023-01-25 11:23 UTC, wmitros approved these changes

2023-01-25 11:26 UTC, michoecho requested changes

2023-01-25 11:58 UTC, nyh commented on tools/toolchain/README.md
> +SCYLLADB_DBUILD=(-e PATH=/usr/lib64/ccache:/usr/bin:/usr/local/bin -v /home/nyh/.ccache:/home/nyh/.ccache:z)
Oops ;-) I see it was like this already and nobody noticed... I'll send a new version.

2023-01-25 12:04 UTC, nyh commented
Pushed a new version with one pre-existing use of /home/nyh to $HOME (matching the second example which already had $HOME).

2023-01-26 07:25 UTC, closed without merging