db/virtual_table: mark final class with `final`
scylladb/scylladb pull request #12879
Opened 2023-02-15 15:00 UTC by tchaikov

as `my_result_collector` has virtual function,
and its dtor is not marked virtual, Clang complains. let's mark it final to be clear that it does not
have derived classes.

```
/home/kefu/.local/bin/../lib/gcc/x86_64-pc-linux-gnu/13.0.1/../../../../include/c++/13.0.1/bits/unique_ptr.h:100:2: error: delete called on non-final 'my_result_collector' that has virtual functions but non-virtual destructor [-Werror,-Wdelete-non-abstract-non-virtual-dtor]
        delete __ptr;
        ^
/home/kefu/.local/bin/../lib/gcc/x86_64-pc-linux-gnu/13.0.1/../../../../include/c++/13.0.1/bits/unique_ptr.h:405:4: note: in instantiation of member function 'std::default_delete<my_result_collector>::operator()' requested here
          get_deleter()(std::move(__ptr));
          ^
/home/kefu/dev/scylladb/db/virtual_table.cc:134:25: note: in instantiation of member function 'std::unique_ptr<my_result_collector>::~unique_ptr' requested here
        auto consumer = std::make_unique<my_result_collector>(s, permit, &pr, std::move(reader_and_handle.second));
                        ^
```

2023-02-15 19:11 UTC, scylladb-promoter commented
CI state **`SUCCESS`** - https://jenkins.scylladb.com/job/releng/job/Scylla-CI/4393/

2023-02-16 08:19 UTC, denesb approved these changes

2023-02-16 08:21 UTC, denesb requested changes
Actually, the fix here is to add a virtual destructor to `result_collector`.
Marking `my_result_collector` is correct, but the above class should have had a virtual destructor.

2023-02-16 12:55 UTC, tchaikov commented
@denesb at first glance, yes, we should mark the dtor its parent as `virtual`. but that's not necessary. as we don't use/destruct  `my_result_collector` via its parent. anyway, if you still think that we should mark go with its parent, i am happy to do so. as it's less confusing this way.

2023-02-16 12:58 UTC, denesb commented
We don't currently, but this can change. Better go for the safe way.

2023-02-16 15:14 UTC, tchaikov commented
@denesb Botend, updated accordingly. could you take another look?

2023-02-16 17:27 UTC, scylladb-promoter commented
CI state **`FAILURE`** - https://jenkins.scylladb.com/job/releng/job/Scylla-CI/4429/

2023-02-16 22:59 UTC, scylladb-promoter commented
CI state **`SUCCESS`** - https://jenkins.scylladb.com/job/releng/job/Scylla-CI/4433/

2023-02-17 10:28 UTC, closed without merging