treewide: do not define/capture unused variables
scylladb/scylladb pull request #12880
Opened 2023-02-15 15:02 UTC by tchaikov

these warnings are found by Clang-17 after removing `-Wno-unused-lambda-capture` and `-Wno-unused-variable` from the list of disabled warnings in `configure.py`.

2023-02-15 15:03 UTC, tchaikov commented
i am happy to chop this change into smaller pieces if this helps with review.

2023-02-15 15:11 UTC, scylladb-promoter commented
CI state **`FAILURE`** - https://jenkins.scylladb.com/job/releng/job/Scylla-CI/4394/

2023-02-15 16:25 UTC, avikivity approved these changes

2023-02-15 16:26 UTC, nyh requested changes
Looks good, though I can't say with 100% certainty I didn't miss everything. I think I found one typo.
By the way, now that you don't need these options in config.py, don't you want to also remove them?

2023-02-15 16:32 UTC, tchaikov commented on api/compaction_manager.cc
> +        return ctx.db.map_reduce0([&](replica::database& db) {
it is indeed a typo.  fixed and repushed.

2023-02-15 16:33 UTC, tchaikov commented
changelog :

-  s/&//: it was a typo.

2023-02-15 16:35 UTC, tchaikov commented
> Looks good, though I can't say with 100% certainty I didn't miss everything. I think I found one typo.
> By the way, now that you don't need these options in config.py, don't you want to also remove them?

good point. i do want to remove them. as they help to improve the code to help us to identify potential bugs. will drop them in another commit in this changeset.

2023-02-15 16:37 UTC, nyh approved these changes

2023-02-15 16:40 UTC, tchaikov commented
i will remove `-Wno-unused-variable` and `-Wno-unused-lambda-capture` in a follow-up change. also, i noticed there are a handful warnings not fixed by this changeset. will fix them in anther PR.

2023-02-15 20:50 UTC, scylladb-promoter commented
CI state **`SUCCESS`** - https://jenkins.scylladb.com/job/releng/job/Scylla-CI/4398/

2023-02-16 07:45 UTC, denesb approved these changes

2023-02-16 07:48 UTC, denesb commented
This PR was queued as 0cb842797a104e922fcb81a27ad749d560d9af75 but it doesn't have the `Closes` reference.

2023-02-16 12:46 UTC, tchaikov commented
@denesb ack! thanks for the reminder. i will rebase this changeset once the test completes.

2023-02-16 13:19 UTC, denesb commented
The "Closes" tag should have been added automatically by our merge script. Not sure what went wrong.

2023-02-16 15:34 UTC, avikivity commented
Committed as 0cb842797a104e922fcb81a27ad749d560d9af75

2023-02-16 15:34 UTC, closed without merging