commitlog: Fix updating of total_size_on_disk on segment alloc when o_dsync is off
scylladb/scylladb pull request #12950
Opened 2023-02-21 15:29 UTC by elcallio

Fixes #12810
    
We did not update total_size_on_disk in commitlog totals when use o_dsync was off.
This means we essentially ran with no registered footprint, also causing broken comparisons in delete_segments.

2023-02-21 15:41 UTC, avikivity commented
@michoecho please review

2023-02-21 16:03 UTC, michoecho requested changes
LGTM, but with a nitpick about the comment.

The patch aside, it's not good that a commitlog bug (thus: a local bug) was only detected by dtest.

2023-02-21 16:32 UTC, elcallio commented
Benign, as in very slow potential leak. But can add up to many sectors over nodes life time.

2023-02-21 16:38 UTC, elcallio commented
But the code nowadays should never (tm) write larger than max_size, since it only adds terminator block on sizes smaller than this.

2023-02-21 20:33 UTC, scylladb-promoter commented
CI state **`SUCCESS`** - https://jenkins.scylladb.com/job/releng/job/Scylla-CI/4546/

2023-02-26 07:53 UTC, bhalevy approved these changes
LGTM

2023-03-02 09:37 UTC, bhalevy commented
@scylladb/scylla-maint merge ping

2023-03-02 20:22 UTC, merged