reader_concurrency_semaphore: don't evict inactive readers needlessly
scylladb/scylladb pull request #13286
Opened 2023-03-22 13:36 UTC by denesb

Inactive readers should only be evicted to free up resources for waiting readers. Evicting them when waiters are not admitted for any other reason than resources is wasteful and leads to extra load later on when these evicted readers have to be recreated end requeued. This patch changes the logic on both the registering path and the admission path to not evict inactive readers unless there are readers actually waiting on resources.
A unit-test is also added, reproducing the overly-agressive eviction and checking that it doesn't happen anymore.

Fixes: #11803

2023-03-23 06:37 UTC, denesb commented
Don't merge yet, I want to extend the tests a bit, there will be a v2.

2023-03-23 09:13 UTC, denesb commented
New in v2:
* Extend tests:
    - extend the existing negative tests
    - add positive tests too
* Don't evict inactive reads when resources are right on the limit, but there is no demand (found by extended tests).

2023-03-23 12:04 UTC, scylladb-promoter commented
CI state **`FAILURE`** - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/258/

2023-03-23 12:27 UTC, denesb commented
New in v2.1:
* Added a thread::yield() to allow debug build to schedule fiber evicting inactive reads again.

2023-03-23 15:01 UTC, avikivity approved these changes
Tricky stuff

2023-03-23 16:55 UTC, scylladb-promoter commented
CI state **`SUCCESS`** - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/263/

2023-03-27 05:33 UTC, denesb commented
Ping.

2023-03-29 13:11 UTC, denesb commented
Ping.

2023-03-30 03:45 UTC, tchaikov requested changes

2023-03-30 03:45 UTC, tchaikov commented on test/boost/reader_concurrency_semaphore_test.cc
> +    auto permit1 = semaphore.obtain_permit(nullptr, get_name(), 1024, db::no_timeout).get();
in #13255, we [changed](https://github.com/scylladb/scylladb/pull/13255/commits/156e5d346d427abc4c79075cb2e71d68ed35d703#diff-46ce50f665ed19eaed28937148d633880d420c375fa7fbed2cb9261047a57ca9R389) the function signature to pass `trace_state` down to semaphore, so might want to update this caller accordingly.

2023-03-30 04:30 UTC, denesb commented
Dequeued, breaks the build.

2023-03-30 05:18 UTC, denesb commented
Rebased and fixed the build.

2023-03-30 08:49 UTC, scylladb-promoter commented
CI state **`FAILURE`** - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/381/

2023-03-30 13:03 UTC, denesb commented
> CI state **`FAILURE`** - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/381/

https://github.com/scylladb/scylladb/issues/13211

Re-kicked

2023-04-03 10:56 UTC, denesb commented
Ping.

2023-04-10 04:24 UTC, yaronkaikov commented
@denesb @avikivity Can we merge this?

2023-04-11 04:48 UTC, denesb commented
> @denesb @avikivity Can we merge this?

I cannot merge my own PR. We need another @scylladb/scylla-maint maintainer to merge it.

2023-04-13 12:02 UTC, denesb commented
@scylladb/scylla-maint ping. This PR is holding up a release, for weeks now.

2023-04-13 12:18 UTC, nyh commented
@avikivity already approved it, so I'll merge. I hope the CI run is not stale :-(

2023-04-13 12:25 UTC, denesb commented
> @avikivity already approved it, so I'll merge. I hope the CI run is not stale :-( (I'll verify it still compiles before merging).

Thanks!

2023-04-14 03:09 UTC, closed without merging