replica: Make compaction_group responsible for deleting off-strategy compaction input
scylladb/scylladb pull request #13432
Opened 2023-04-03 19:22 UTC by raphaelsc

Compaction group is responsible for deleting SSTables of "in-strategy" compactions, i.e. regular, major, cleanup, etc.

Both in-strategy and off-strategy compaction have their completion handled using the same compaction group interface, which is 
```
compaction::table_state::on_compaction_completion(...,
				sstables::offstrategy offstrategy)
```

So it's important to bring symmetry there, by moving the responsibility of deleting off-strategy input, from manager to group.

2023-04-03 19:25 UTC, raphaelsc commented
Another important advantage is that off-strategy deletion is now throttled and gated, allowing for better control and table waiting for it on shutdown. Will update the commit message.

2023-04-03 19:26 UTC, raphaelsc commented
v2: updated commit message.

2023-04-03 20:18 UTC, bhalevy requested changes
although the mutable lambdas problem is preexisting it's a good opportunity to fix it.

2023-04-03 20:18 UTC, bhalevy commented on replica/table.cc
> +        return with_semaphore(_t._sstable_deletion_sem, 1, [sstables_to_remove = std::move(sstables_to_remove)] {
need to make both lambdas `mutable` otherwise `std::move` will copy the const vector.

2023-04-03 22:10 UTC, raphaelsc commented
> although the mutable lambdas problem is preexisting it's a good opportunity to fix it.

Agreed. Will fix. Thanks

2023-04-03 22:38 UTC, scylladb-promoter commented
CI state **`FAILURE`** - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/451/

2023-04-03 23:56 UTC, raphaelsc commented
v3: make lambdas mutable, to guarantee move semantics rather than copy. suggested by @bhalevy

2023-04-04 03:12 UTC, scylladb-promoter commented
CI state **`SUCCESS`** - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/452/

2023-04-04 07:19 UTC, bhalevy commented on replica/table.cc
> +        co_await std::move(f);
sorry, but wouldn't it be simpler to just use .handle_exception, like:
```c++
    return seastar::try_with_gate(_t._sstable_deletion_gate, [this, sstables_to_remove = std::move(sstables_to_remove)] () mutable {
        return with_semaphore(_t._sstable_deletion_sem, 1, [sstables_to_remove = std::move(sstables_to_remove)] () mutable {
            return sstables::sstable_directory::delete_atomically(std::move(sstables_to_remove));
       });
    }).handle_exception([] (std::exception_ptr ex) {
       // There is nothing more we can do here.
       // Any remaining SSTables will eventually be re-compacted and re-deleted.
       tlogger.error("Compacted SSTables deletion failed: {}. Ignored.", std::move(ex));
    });
```

The hybrid continuation chain co_await'ed in a try/catch block seems odd.

2023-04-04 12:14 UTC, raphaelsc commented
v4: fix mix of coroutine and continuation style when deleting sstables

2023-04-04 13:18 UTC, bhalevy approved these changes
LGTM, thanks

2023-04-04 15:06 UTC, scylladb-promoter commented
CI state **`SUCCESS`** - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/464/

2023-04-05 05:37 UTC, denesb approved these changes

2023-04-06 22:52 UTC, closed without merging