doc: document `tombstone_gc` as not experimental
scylladb/scylladb pull request #13469
Opened 2023-04-10 20:25 UTC by annastuchlik

The tombstone_gc option was documented as experimental in version 5.0. It is no longer experimental in version 5.2.
This commit updates the information about the option in release 5.2.

This means that the commit must be merged to master and backported to branch-5.2.

2023-04-17 08:39 UTC, annastuchlik commented on docs/cql/ddl.rst
> +You can enable or disable the after-repair tombstone GC by enabling or disabling the ``repair`` mode using
I've already rewritten the sentence to remove "disable" and "disabled" before I asked you to re-review. I'm not sure what else is there to do.
Could you review the current version?

2023-04-18 09:32 UTC, annastuchlik commented on docs/cql/ddl.rst
> +You can enable or disable the after-repair tombstone GC by enabling or disabling the ``repair`` mode using
@yarongilor Please help, as this PR should be merged asap (and backported to branch-5.2).

2023-04-19 08:30 UTC, roydahan commented on docs/cql/ddl.rst
> +You can enable or disable the after-repair tombstone GC by enabling or disabling the ``repair`` mode using
I think it's ok now, but I'll let @yarongilor to verify.

2023-04-19 08:30 UTC, roydahan approved these changes

2023-04-19 12:32 UTC, yarongilor approved these changes
LGTM

2023-04-19 13:05 UTC, annastuchlik commented
@scylladb/scylla-maint Please merge.

2023-04-19 14:17 UTC, tgrabiec requested changes

2023-04-19 14:17 UTC, tgrabiec commented on docs/cql/ddl.rst
> +     - Tombstone GC is performed after repair is run (default).
The default is still `timeout`:

```

const ::tombstone_gc_options& schema::tombstone_gc_options() const {
    static const ::tombstone_gc_options default_tombstone_gc_options;
    const auto& schema_extensions = _raw._extensions;

    if (auto it = schema_extensions.find(tombstone_gc_extension::NAME); it != schema_extensions.end()) {
        return dynamic_pointer_cast<tombstone_gc_extension>(it->second)->get_options();
    }
    return default_tombstone_gc_options;
}
```

```

class tombstone_gc_options {
private:
    tombstone_gc_mode _mode = tombstone_gc_mode::timeout;

```

2023-04-20 07:18 UTC, annastuchlik commented
I'm totally confused. First, the PR had several review iterations, and the default looked was approved (it's mentioned twice, in the table and on line 818). @roydahan When you test the feature, do you have to change the default?
Second, if the default is still timeout, what's the difference between release 5.2 and the previous releases? 

@tzach Are there any product expectations regarding the default?

2023-04-21 02:17 UTC, roydahan commented
> I'm totally confused. First, the PR had several review iterations, and the default looked was approved (it's mentioned twice, in the table and on line 818). @roydahan When you test the feature, do you have to change the default? Second, if the default is still timeout, what's the difference between release 5.2 and the previous releases?
> 
> @tzach Are there any product expectations regarding the default?

@tgrabiec is correct, the default is still the same (I missed that in my review).
The change is that now it's supported officially and announced as such.

2023-04-22 14:00 UTC, closed without merging

2023-04-24 07:55 UTC, annastuchlik commented
@scylladb/scylla-maint Please backport to branch-5.2.
This change was introduced in version 5.2.

2023-04-24 08:55 UTC, denesb commented
Backport queued to next-5.2 as a6188d6abced781916392b0076f0cacb965136d2.