Fixing broken links to ScyllaDB University lessons, Scylla University…
scylladb/scylladb pull request #14385
Opened 2023-06-25 06:10 UTC by guy9

… -> ScyllaDB University

2023-06-25 06:11 UTC, guy9 commented
Fixes https://github.com/scylladb/scylladb/issues/14350#issuecomment-1602145493
@annastuchlik please review

2023-06-26 15:45 UTC, annastuchlik commented on docs/operating-scylla/procedures/backup-restore/index.rst
> +* Also covered in the `Cluster Backup Using ScyllaDB Manager lesson <hhttps://university.scylladb.com/courses/scylla-operations/lessons/scylla-manager-repair-and-tombstones/topic/cluster-backup-using
```suggestion
* Also covered in the `Cluster Backup Using ScyllaDB Manager lesson <https://university.scylladb.com/courses/scylla-operations/lessons/scylla-manager-repair-and-tombstones/topic/cluster-backup-using-scylla-manager/>`_ on ScyllaDB University.
```

2023-06-26 15:46 UTC, annastuchlik requested changes
A minor change is required to make one of the links work.

2023-06-27 09:23 UTC, guy9 commented
Thanks @annastuchlik , fixed.

2023-06-27 10:02 UTC, annastuchlik approved these changes
LGTM

2023-06-27 10:03 UTC, annastuchlik commented
@scylladb/scylla-maint Please merge.

2023-06-27 13:49 UTC, merged