test/pylib: allow run minio_server.py as a stand-alone tool
scylladb/scylladb pull request #14485
Opened 2023-07-03 08:27 UTC by tchaikov

this would allow developer to run a minio server for testing, for instance, s3_test.

2023-07-03 08:33 UTC, tchaikov commented
@xemul hi Pavel, could you help review this change as well?

2023-07-03 10:04 UTC, scylladb-promoter commented
CI state **`SUCCESS`** - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/2196/

2023-07-03 11:16 UTC, xemul requested changes
Please, add the shell command example how to launch the thing standalone. E.g. in patch comment. Otherwise it's awesome

2023-07-04 05:18 UTC, tchaikov commented
v2
- revise the commit message to demonstrate how the script can be used as a stand-alone tool.
- add another commit to make the script more user friendly

@xemul hi Pavel, thank you for your review. i think i've addressed your comment. could you please take another look?

2023-07-04 06:49 UTC, scylladb-promoter commented
CI state **`SUCCESS`** - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/2222/

2023-07-04 18:34 UTC, closed without merging