raft: move group0_state_machine::merger to its own header and add unit test for it
scylladb/scylladb pull request #14682
Opened 2023-07-13 10:52 UTC by margdoc

Move `merger` to its own header file. Leave the logic of applying commands to `group0_state_machine`. Remove `group0_state_machine` dependencies from `merger` to make it an independent module.

Add a test that checks if `group0_state_machine_merger` preserves timeuuid monotonicity. `last_id()` should be equal to the largest timeuuid, based on its timestamps.

This test combines two commands in the reverse order of their timeuuids. The timeuuids yield different results when compared in both timeuuid order and uuid order. Consequently, the resulting command should have a more recent timeuuid.

Closes #14568

2023-07-13 12:30 UTC, scylladb-promoter commented
CI state **`SUCCESS`** - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/2465/

2023-07-13 15:23 UTC, kbr-scylla commented on service/raft/group0_state_machine.cc
> +    co_await apply_command(std::move(cmd), std::move(history));
subjective nit: I would inline `apply_command` here, since it's the only use of it.

2023-07-13 15:23 UTC, kbr-scylla commented on test/boost/group0_cmd_merge_test.cc
> +    // https://github.com/scylladb/scylladb/issues/14568
We usually just reference the issue number with `#`, like this:
```
Ref #14568
```

and below:
```
From #7729
```

2023-07-13 15:23 UTC, kbr-scylla commented on test/boost/group0_cmd_merge_test.cc
> +    // https://github.com/scylladb/scylladb/issues/14568
Also, a better issue (or issues -- there are two in this case) to reference is those that described the bugs which were then solved, and this test is a regression test for the two issues. (The comment should explicitly say that this is a regression test for #X and #Y)

2023-07-14 10:33 UTC, margdoc commented
v2:
* inlined `apply_command`
* added comments

2023-07-14 12:31 UTC, scylladb-promoter commented
CI state **`SUCCESS`** - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/2484/

2023-07-17 13:55 UTC, margdoc commented
v3:
* fixed documentation
* added `static` and `const` comments
* made `group0_state_machine_merger` a `class` instead of `struct`
* added information about merger refactoring in the commit message
* rebased on `master`

2023-07-17 16:51 UTC, scylladb-promoter commented
CI state **`SUCCESS`** - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/2530/

2023-07-18 10:55 UTC, kbr-scylla requested changes

2023-07-18 10:55 UTC, kbr-scylla commented on service/raft/group0_state_machine_merger.hh
> +    // and the size of the batch will not exceed the limit. Empties the current batch.
I don't think `can_merge` empties the current batch.

2023-07-18 10:55 UTC, kbr-scylla commented
@kostja @tgrabiec please review

2023-07-18 15:41 UTC, tgrabiec approved these changes

2023-07-18 15:44 UTC, kbr-scylla commented
Queued.
There was a minor problem with one comment, I fixed it during merge.

2023-07-18 22:21 UTC, merged