test: raft: do not update raft address map with obsolete gossip data
scylladb/scylladb pull request #14728
Opened 2023-07-17 13:29 UTC by margdoc

Regression test for #14257.

It starts two nodes. It introduces a sleep in raft_group_registry::on_alive (in raft_group_registry.cc) when receiving a gossip notification about HOST_ID update from the second node. Then it restarts the second node with a different IP. Due to the sleep, the old notification from the old IP arrives after the second node has restarted. If the bug is present, this notification overrides the address map entry and the second read barrier times out, since the first node cannot reach the second node with the old IP.

Closes #14609.

2023-07-17 16:57 UTC, scylladb-promoter commented
CI state **`SUCCESS`** - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/2528/

2023-07-18 10:44 UTC, kbr-scylla requested changes

2023-07-18 10:44 UTC, kbr-scylla commented on service/raft/raft_group_registry.cc
> +                co_await handler.wait_for_message(std::chrono::steady_clock::now() + std::chrono::seconds{6});
Please increase this timeout to 1 minute, we don't want the test to be flaky on slow machines.

2023-07-18 10:44 UTC, kbr-scylla commented on test/topology_custom/test_change_ip_repro.py
> +async def test_change_ip_repro(manager: ManagerClient) -> None:
Please change the name of the test (and the file) to be more specific.
For example: `test_old_ip_notification_repro`

2023-07-18 10:47 UTC, margdoc commented
Without #14329 this test fails with a timeout (after about 200s).

2023-07-19 07:49 UTC, margdoc commented
v2:
* `test_change_ip_repro` => `test_old_ip_notification_repro`
* changed the timeout to 1 minute

2023-07-19 08:30 UTC, kbr-scylla approved these changes

2023-07-19 09:38 UTC, scylladb-promoter commented
CI state **`SUCCESS`** - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/2566/

2023-07-19 10:27 UTC, avikivity commented
Use Fixes, not Closes, as our automation is cued to Fixes.

2023-07-19 16:13 UTC, closed without merging