test: pylib: ensure ScyllaCluster.add_server does not start a second cluster
scylladb/scylladb pull request #14804
Opened 2023-07-24 11:58 UTC by patjed41

Fixes #12438 

If the cluster isn't empty and all servers are stopped, calling `ScyllaCluster.add_server` can start a new cluster. That's because `ScyllaCluster._seeds` uses the running servers to calculate the seed node list, so if all nodes are down, the new node would select only itself as a seed, starting a new cluster.

As a single `ScyllaCluster` should describe a single cluster, we make `ScyllaCluster.add_server` fail when called on a non-empty cluster with all its nodes stopped.

2023-07-24 12:10 UTC, alecco approved these changes

2023-07-24 12:11 UTC, piodul requested changes
Could you add a regression test?

2023-07-24 12:31 UTC, kbr-scylla commented
> Could you add a regression test?

Meh, it's a low-impact change, the test would only test the framework and not Scylla itself, I think it's not worth it.

I think it's enough to confirm that you tested manually that the fix work.

2023-07-24 13:38 UTC, scylladb-promoter commented
CI state **`SUCCESS`** - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/2644/

2023-07-27 11:26 UTC, kbr-scylla approved these changes

2023-07-28 14:21 UTC, closed without merging