doc: update the Seastar Perftune page
scylladb/scylladb pull request #14879
Opened 2023-07-28 15:20 UTC by annastuchlik

This commit updates the description of perftune.py. It is based on the information in the reported issue (below), the contents of help for perftune.py, and the input from @vladzcloudius.

Fixes https://github.com/scylladb/scylladb/issues/14233

2023-07-28 15:43 UTC, annastuchlik commented
Preview
![image](https://github.com/scylladb/scylladb/assets/37244380/665ebfa7-358f-4e3f-92e6-5f8405669a9b)
![image](https://github.com/scylladb/scylladb/assets/37244380/d7c67be0-6e57-4c08-a3f5-75c450ff68da)
![image](https://github.com/scylladb/scylladb/assets/37244380/2f976d57-2045-43b3-a2f4-ce3e1b1372b0)
![image](https://github.com/scylladb/scylladb/assets/37244380/8e9d2f01-676f-4b50-9672-3a4c84af5403)

2023-07-28 15:44 UTC, annastuchlik commented
@vladzcloudius Please review this PR.

2023-07-31 12:38 UTC, annastuchlik commented
@asias @syuu1228 Could you review this PR, too?
Also, could you explain to @tzach and me how the user can run the script? We thought it was run from scylla_setup, but it seems it's run by the scylla-server service. Is that correct?

What are the steps the user needs to take to run perftune.py?

2023-07-31 19:51 UTC, vladzcloudius requested changes

2023-07-31 19:51 UTC, vladzcloudius commented on docs/operating-scylla/admin-tools/perftune.rst
> +         * ``disk`` - Enables tuning the disks.
It's `disks` not `disk`

2023-07-31 20:26 UTC, vladzcloudius requested changes

2023-07-31 20:26 UTC, vladzcloudius requested changes
On top of my other comments - some examples of perftune.py usage would be nice.

2023-08-01 09:34 UTC, annastuchlik commented on docs/operating-scylla/admin-tools/perftune.rst
> +The ``perftune.yaml`` file is generated by the ``perftune.py`` script.The script determines
I'll replace it with the information that perfrune.yaml is the output file of perftune.py (with the --dump-options-file enabled).
Would that be sufficient?

2023-08-10 11:05 UTC, annastuchlik commented
@vladzcloudius @asias @syuu1228 Cloud you review this PR? I've applied the suggestions from @vladzcloudius.

@vladzcloudius If you provide some real-life examples, I'll be happy to add them. Alternatively, we can merge this PR to have the page improved asap, and add the examples later.

2023-08-15 20:44 UTC, vladzcloudius approved these changes
I think it looks good to merge.

I agree about examples - let's merge this and then work on a follow up.

2023-08-16 07:13 UTC, annastuchlik commented
@scylladb/scylla-maint Please merge.

2023-08-22 03:04 UTC, closed without merging