gossiper: mark_dead: lock_endpoint
scylladb/scylladb pull request #15001
Opened 2023-08-09 14:37 UTC by bhalevy

mark_dead may be called with null_permit_id
(from convict), and in this case, by contract,
it should lock the endpoint.

This change somehow escaped #14845
so it amend it and

Fixes #14838

2023-08-09 14:56 UTC, tgrabiec requested changes

2023-08-09 19:28 UTC, bhalevy commented on gms/gossiper.cc
> +    pid = permit.id();
good point.

2023-08-10 00:51 UTC, scylladb-promoter commented
CI state **`ABORTED`** - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/2975/

2023-08-10 05:19 UTC, bhalevy commented
In v2:
- Move lock_endpoint to `convict`
- Verify the permit_id on all private functions.

2023-08-10 07:56 UTC, scylladb-promoter commented
CI state **`SUCCESS`** - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/2982/

2023-08-10 11:07 UTC, tgrabiec approved these changes

2023-08-10 11:08 UTC, kbr-scylla approved these changes

2023-08-11 07:16 UTC, merged