token_metadata: get_endpoint_to_host_id_map_for_reading: just warn if normal node has null host_id
scylladb/scylladb pull request #15184
Opened 2023-08-27 14:58 UTC by bhalevy

It is too early to require that all nodes in normal state have a non-null host_id.

The assertion was added in 44c14f3e2b779409d9c73e4cddd32d0c741bc14c but unfortunately there are several call sites where we add the node as normal, but without a host_id
and we patch it in later on.

In the future we should be able to require that
once we identify nodes by host_id over gossiper
and in token_metadata.

Fixes scylladb/scylladb#15181

2023-08-27 18:49 UTC, scylladb-promoter commented
CI state **`SUCCESS`** - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/3286/

2023-08-28 14:14 UTC, nyh requested changes
If your conclusion is that this host_id *may* be null, I think "warn" is excessive - it can scare users, and dtests may complain about it (some dtests, I'm not sure that all, don't allow unknown warnings to appear).
So I think it should be "info", not "warn".

2023-08-28 14:31 UTC, bhalevy commented
> If your conclusion is that this host_id _may_ be null, I think "warn" is excessive - it can scare users, and dtests may complain about it (some dtests, I'm not sure that all, don't allow unknown warnings to appear). So I think it should be "info", not "warn".

Dtests fail on unexpected ERRORs, not WARNings, so this is not an issue, but scaring uses might be.
Let's demote it to info then.  It is printed only when invoked from the api anyhow, so info makes sense.

2023-08-28 14:36 UTC, bhalevy commented
- demoted log message to info level
- rebased

2023-08-28 18:29 UTC, scylladb-promoter commented
CI state **`SUCCESS`** - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/3305/

2023-08-28 18:40 UTC, nyh approved these changes

2023-08-29 05:04 UTC, closed without merging