cql3: fix bad optional access when executing fromJson function
scylladb/scylladb pull request #15481
Opened 2023-09-20 02:21 UTC by michaelhly

We use "null" as the default value when unwrapping optionals to avoid bad optional access errors.

Fixes: #7912
Closes: #15474

2023-09-20 02:21 UTC, scylladb-promoter commented
@scylladb/scylla-maint please review and trigger CI for this pull request
**CI Build:** https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/parambuild/?PR_NUMBER=15481

2023-09-20 02:22 UTC, scylladb-promoter commented
@scylladb/scylla-maint please review and trigger CI for this pull request
**CI Build:** https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/parambuild/?PR_NUMBER=15481

2023-09-20 03:03 UTC, scylladb-promoter commented
@scylladb/scylla-maint please review and trigger CI for this pull request
**CI Build:** https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/parambuild/?PR_NUMBER=15481

2023-09-20 08:55 UTC, nyh requested changes
Looks very good, thanks!

Just one small small request: We also have a test for #7912 in cassandra_tests/validation/entities/json_test.py - a large test `testFromJsonFct` translated from Cassandra. The test still fails despite your patch because of other issues (Cassandra's tests are long and often expose multiple bugs...) but please remove the "#7912" from the "xfail" line. Please don't remove the mentions of 7912 in that file in comments - it's still useful to know that a test can reproduce old issues, even if they are fixed.

Also two tiny comments about the commit message:
1. You don't need to add the "closes" line for the PR, we do this automatically when committing the patch (we have a script to do it). It doesn't hurt, but you don't have to bother to do it.
2. Seeing the test passing isn't very useful in the commit message. At most you can mention that they pass. But even that is redundant, because we have CI which won't let any patch that doesn't pass the tests go into master.

2023-09-20 10:35 UTC, scylladb-promoter commented
CI state **`FAILURE`** - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/3796/

2023-09-20 12:47 UTC, nyh commented
> CI state **`FAILURE`** - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/3796/

```Cannot contact spider2.cloudius-systems.com```
Probably hardware failure (we had the electricity grid going down a few times). I'll restart the CI.

2023-09-20 15:09 UTC, scylladb-promoter commented
CI state **`SUCCESS`** - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/3806/

2023-09-20 15:58 UTC, scylladb-promoter commented
@scylladb/scylla-maint please review and trigger CI for this pull request
**CI Build:** https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/parambuild/?PR_NUMBER=15481

2023-09-21 12:26 UTC, nyh approved these changes
Looks good, thanks.
@avikivity asked that you state your full name, not just gmail handle, in the "From". Please do this also in the "Signed-off-by" line. Thanks.

While you're modifying the commit message, please consider describing the actual bug which you fix and not (just) **how** you fixed it. E.g., something like:
"Fix fromJson(null) to return null, not a error as it did before this patch".

2023-09-21 14:21 UTC, scylladb-promoter commented
CI state **`SUCCESS`** - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/3842/

2023-09-21 17:18 UTC, avikivity commented
@benipeled please enable auto-CI for this contributor

2023-09-21 19:30 UTC, closed without merging