cql-pytest: Dont flush out/err between fork and exec
scylladb/scylladb pull request #15568
Opened 2023-09-27 15:44 UTC by xemul

When fork+exec-ing a process with stdio redirection it's recommended to flush stdout/err in-memory buffers not to make child and parent processes produce buffered message twice. This recommendation applies to fork() -- this is where buffers are duplicated and have chances to get pronted twise. Flushing after fork() only makes sense to make sure anything that was printed before exec() finds its way to the descriptor, but it's not the case here.

2023-09-27 18:37 UTC, scylladb-promoter commented
CI state **`SUCCESS`** - https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/3959/

2023-09-27 19:42 UTC, nyh requested changes
You did not explain **why** you wanted to "fix" these flush calls. Did they cause you any problems? Or did they just bother you when you noticed them in a code review?

In any case, these specific flush calls which you want to remove were intentional - although I agree not terribly important: As you rightly noticed, their raison d'etre wasn't the fork (those are the flushes _before_ the fork). Instead, in this place we are about to use the low-level os.close() function, and it's possible that in the short time in the child after the fork, the child printed something - e.g., maybe the run_dir_generator() printed some output? I wanted all the this output printed by Python, as opposed to going to the log file which is supposed to contain only the output of the execve'd program. So I wanted to flush this theoretically-possible output the original output - not to the redirected file.

2023-09-28 07:09 UTC, xemul commented
> You did not explain why you wanted to "fix" these flush calls. Did they cause you any problems? Or did they just bother you when you noticed them in a code review?

Kefu was fixing similar place in object_store test (#15560), reviewing it I noticed that the similar flush() calls were redundant. Then we found out that the commit that brought those flushes to object_store test picked them from cql-pytest/run.py. So I decided that flushes are redundant in cql-pytest/run too and here's the PR removing them

2023-09-28 07:41 UTC, nyh commented
> So I decided that flushes are redundant in cql-pytest/run too and here's the PR removing them

After my explanation above, do you still think they are redundant (in run.py) and should be removed?

2023-09-28 07:45 UTC, nyh commented
By the way, when I wrote this code, I didn't realize that Python's sys.stdout can be changed and doesn't necessarily correspond to file descriptor 1 which we close. This code assumes sys.stdout is the default sys.__stdout, which does correspond to file descriptor 1 - otherwise it doesn't make sense to flush sys.stdout before closing file descriptor 1. In the case of test/cql-pytest/run et al., this is true - we don't modify the Python variable sys.stdout. I saw in https://github.com/scylladb/scylladb/pull/15560 some mention that this isn't true in test.py - I don't understand how or why.

2023-09-28 07:54 UTC, xemul commented
> By the way, when I wrote this code, I didn't realize that Python's sys.stdout can be changed and doesn't necessarily correspond to file descriptor 1 which we close.

But this doesn't matter methinks. This code prepares stdios for the target process which "knows" that they are 1 and 2. So the child process should close them and dup log into it, so this place is correct.

> After my explanation above, do you still think they are redundant (in run.py) and should be removed?

No, I no longer think they are redundant. All the more so I found that scylla cmd generator does print() something and that must be flushed

2023-09-28 07:54 UTC, closed without merging