schema_tables: turn view schema fixing code into a sanity check
scylladb/scylladb pull request #15695
Opened 2023-10-11 13:11 UTC by kbr-scylla

The purpose of `maybe_fix_legacy_secondary_index_mv_schema` was to deal
with legacy materialized view schemas used for secondary indexes,
schemas which were created before the notion of "computed columns" was
introduced. Back then, secondary index schemas would use a regular
"token" column. Later it became a computed column and old schemas would
be migrated during rolling upgrade.

The migration code was introduced in 2019
(db8d4a0cc649c74e30198dd83b082b0ad50b1314) and then fixed in 2020
(d473bc9b0669e9d3879ff0f329a9ed16378dd569).

The fix was present in Enterprise 2022.1 and in OSS 4.5. So, assuming
that users don't try crazy things like upgrading from 2021.X to 2023.X
(which we do not support), all clusters will have already executed the
migration code once they upgrade to 2023.X, meaning we can get rid of
it.

The main motivation of this PR is to get rid of the
`db::schema_tables::merge_schema` call in `parse_schema_tables`. In Raft
mode this was the only call to `merge_schema` outside "group 0 code" and
in fact it is unsafe -- it uses locally generated mutations with locally
generated timestamp (`api::new_timestamp()`), so if we actually did it,
we would permanently diverge the group 0 state machine across nodes
(the schema pulling code is disabled in Raft mode). Fortunately, this
should be dead code by now, as explained in the previous paragraph.

The migration code is now turned into a sanity check, if the users
try something crazy, they will get an error instead of silent data
corruption.

2023-10-11 13:13 UTC, kbr-scylla commented
I stumbled on this when looking for calls to `make_update_view_mutations` when trying to develop a fix for the issue described here: https://github.com/scylladb/scylladb/pull/15687#issuecomment-1755861099

I think that getting rid of this unsafe (in Raft mode) `merge_schema` call first is a prerequisite.

2023-10-11 15:32 UTC, kbr-scylla commented
`test_schema_digest_does_not_change_without_digest_feature` and `test_schema_digest_does_not_change` are now failing because they would disable the `COMPUTED_COLUMNS` schema feature (which is made impossible by the first commit) and depend on the fact that with the feature disabled, digests would be calculated differently than with enabled.

Need to regenerate the digests.

2023-10-11 19:27 UTC, avikivity commented
> `test_schema_digest_does_not_change_without_digest_feature` and `test_schema_digest_does_not_change` are now failing because they would disable the `COMPUTED_COLUMNS` schema feature (which is made impossible by the first commit) and depend on the fact that with the feature disabled, digests would be calculated differently than with enabled.
> 
> Need to regenerate the digests.

The test is there to make sure the digests don't change.

2023-10-11 19:28 UTC, avikivity commented
> > `test_schema_digest_does_not_change_without_digest_feature` and `test_schema_digest_does_not_change` are now failing because they would disable the `COMPUTED_COLUMNS` schema feature (which is made impossible by the first commit) and depend on the fact that with the feature disabled, digests would be calculated differently than with enabled.
> > Need to regenerate the digests.
> 
> The test is there to make sure the digests don't change.

Oh, you removed an obsolete setting. You can just remove the test for that setting, since it's impossible to be in a cluster with that feature disabled.

2023-10-12 16:47 UTC, scylladb-promoter commented
#### :red_circle: CI State: FAILURE

:x: - Build
#### Build Details:
- Build URL: https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/4192/
- Duration: 32 min
- Builder: monster

2023-10-13 08:40 UTC, kbr-scylla commented
> 18:43:30  clang-16: error: unable to execute command: Bus error
> 18:43:30  clang-16: error: linker command failed due to signal (use -v to see invocation)

restarting

2023-10-13 11:12 UTC, scylladb-promoter commented
#### :green_circle: CI State: SUCCESS

:white_check_mark: - Build
:white_check_mark: - Sanity Tests
:white_check_mark: - Unit Tests
#### Build Details:
- Build URL: https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/4195/
- Duration: 2 hr 32 min
- Builder: spider4.cloudius-systems.com

2023-10-16 14:16 UTC, kbr-scylla commented
@eliransin @nyh ping, please review.

2023-10-17 09:37 UTC, kbr-scylla commented
@eliransin @nyh ping, please review.

2023-10-17 15:37 UTC, avikivity approved these changes
Changes in this area are scary, but this series makes everything clear so it looks good to me.

2023-10-18 08:24 UTC, kbr-scylla commented
@eliransin @nyh ping, please review.

2023-10-19 08:36 UTC, kbr-scylla commented
@eliransin @nyh ping, please review.

2023-10-20 13:52 UTC, kbr-scylla commented
@eliransin @nyh ping, please review.

2023-10-23 12:08 UTC, nyh commented
> Unfortunately, all digest tests contain at least one digest that was calculated with the COMPUTED_COLUMNS feature disabled, so if I wanted to get rid of the `schema_feature`, I'd have to regenerate those digests.
> 
> Simpler to leave the `schema_feature` in and allow tests to continue disabling it for digest calculation.

This is simpler, but makes those tests even further removed from what happens in practice :-(

I didn't understand why you and Avi decided it wasn't a good idea to change the digest... That's always the nature of "approval testing" (like this test, or @kostja 's test/cql) - after thinking very hard (?) that a change is good, you enshrine the new behavior, and the test ensures it doesn't change again by chance. This probably isn't the last time we want to change the digests or obsolete old features, will we end up with 10 year old digests in this this test and twisting our code to fit it?

Anyway, I'm not against this approach even if it's not my favorite, so I'll review the rest and hopefully merge this. But @kbr-scylla there are conflicts - please rebase.

2023-10-23 12:28 UTC, nyh approved these changes
Looks good. @kbr-scylla please rebase as there are conflicts.

2023-10-23 12:28 UTC, nyh commented on db/schema_tables.cc
> +        on_internal_error(slogger, format(
nitpick: maybe this should have been a normal exception, which will prevent boot, and not an "on_internal_error"?

2023-10-23 15:43 UTC, avikivity commented
> > Unfortunately, all digest tests contain at least one digest that was calculated with the COMPUTED_COLUMNS feature disabled, so if I wanted to get rid of the `schema_feature`, I'd have to regenerate those digests.
> > Simpler to leave the `schema_feature` in and allow tests to continue disabling it for digest calculation.
> 
> This is simpler, but makes those tests even further removed from what happens in practice :-(
> 
> I didn't understand why you and Avi decided it wasn't a good idea to change the digest... That's always the nature of "approval testing" (like this test, or @kostja 's test/cql) - after thinking very hard (?) that a change is good, you enshrine the new behavior, and the test ensures it doesn't change again by chance. This probably isn't the last time we want to change the digests or obsolete old features, will we end up with 10 year old digests in this this test and twisting our code to fit it?

Those old digests test our compatibility with older versions. If we regenerate the digests we have no idea if we are still compatible or not. If we regenerate them, we'll know that even newer versions are compatible with this point in time, but we won't know if this point in time is compatible with those older versions.

We can add new digests with the feature enabled, and perhaps remove the old ones much later, but to have proof that the change doesn't affect the digests in unintended ways we must keep the old digests for a while.

2023-10-24 07:56 UTC, eliransin commented
> I didn't understand why you and Avi decided it wasn't a good idea to change the digest... That's always the nature of "approval testing" (like this test, or @kostja 's test/cql) - after thinking very hard (?) that a change is good, you enshrine the new behavior, and the test ensures it doesn't change again by chance. This probably isn't the last time we want to change the digests or obsolete old features, will we end up with 10 year old digests in this this test and twisting our code to fit it?

I am with @nyh on this, if we have an expected behavior (in the face of either, error or success), we should test it as this is part of the advantages of the in-code testing.

2023-10-24 08:01 UTC, eliransin commented
Just one final word about this change:
I think that the upgrade path is not a big deal since a users that doesn't follow the correct upgrade procedure are rare, also the procedure is well defined so no harm there (maybe in the future we should enforce this further by not allowing a node that is "too new" to join the cluster at all.

The only place that I can think of that such problems may arise are restoring from an old backup. Our restore process is not perfect as it is but I think it deserves some consideration what will happen if someone tries to restore some old backup. I don't remember all of the details but I remember it involves exporting the schema, but maybe then the rebuild  of the schema happens transparently.

2023-10-24 08:03 UTC, eliransin requested changes

2023-10-24 10:12 UTC, kbr-scylla commented
@eliransin I can change to `on_fatal_internal_error`

2023-10-24 14:00 UTC, scylladb-promoter commented
#### :red_circle: CI State: FAILURE

:white_check_mark: - Build
:x: - Sanity Tests
:white_check_mark: - Unit Tests
#### Failed Tests (1/21010):
- [test_lcs_table_promotion_major_compaction](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/4357/testReport/junit/compaction_additional_test/TestLCSSSTablePromotion/Tests___Sanity_Tests___test_lcs_table_promotion_major_compaction) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_lcs_table_promotion_major_compaction)
#### Build Details:
- Build URL: https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/4357/
- Duration: 2 hr 23 min
- Builder: spider7.cloudius-systems.com

2023-10-24 14:01 UTC, kbr-scylla commented
> [test_lcs_table_promotion_major_compaction](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/4357/testReport/junit/compaction_additional_test/TestLCSSSTablePromotion/Tests___Sanity_Tests___test_lcs_table_promotion_major_compaction) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_lcs_table_promotion_major_compaction)

https://github.com/scylladb/scylladb/issues/15714
restarting CI

2023-10-24 16:11 UTC, scylladb-promoter commented
#### :red_circle: CI State: FAILURE

:white_check_mark: - Build
:x: - Sanity Tests
:white_check_mark: - Unit Tests
#### Failed Tests (1/21010):
- [test_lcs_table_promotion_major_compaction](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/4367/testReport/junit/compaction_additional_test/TestLCSSSTablePromotion/Tests___Sanity_Tests___test_lcs_table_promotion_major_compaction) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_lcs_table_promotion_major_compaction)
#### Build Details:
- Build URL: https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/4367/
- Duration: 2 hr 9 min
- Builder: spider7.cloudius-systems.com

2023-10-24 16:49 UTC, avikivity commented
@raphaelsc @fruch any  idea why test_lcs_table_promotion_major_compaction fails so often? do we have a major regression here?

2023-10-24 18:29 UTC, nyh commented
> Those old digests test our compatibility with older versions. If we regenerate the digests we have no idea if we are still compatible or not. If we regenerate them, we'll know that even newer versions are compatible with this point in time, but we won't know if this point in time is compatible with those older versions.
> 
> We can add new digests with the feature enabled, and perhaps remove the old ones much later, but to have proof that the change doesn't affect the digests in unintended ways we must keep the old digests for a while.

So if we generated these digets in 2020, will we in 2030 still have this test whose purpose is to check that we're still compatible - if we fake-unset a dozen variables that a normal user can't unset - with the code from 2020? Isn't it more important to check in 2030 that nothing we had in 2029 got broken by the new patch?

We can have both, of course, but if we need to choose one, I think we're choosing the wrong one.

2023-10-24 19:16 UTC, avikivity commented
> > Those old digests test our compatibility with older versions. If we regenerate the digests we have no idea if we are still compatible or not. If we regenerate them, we'll know that even newer versions are compatible with this point in time, but we won't know if this point in time is compatible with those older versions.
> > We can add new digests with the feature enabled, and perhaps remove the old ones much later, but to have proof that the change doesn't affect the digests in unintended ways we must keep the old digests for a while.
> 
> So if we generated these digets in 2020, will we in 2030 still have this test whose purpose is to check that we're still compatible - if we fake-unset a dozen variables that a normal user can't unset - with the code from 2020? Isn't it more important to check in 2030 that nothing we had in 2029 got broken by the new patch?
> 
> We can have both, of course, but if we need to choose one, I think we're choosing the wrong one.

We should have both for a time, then delete the old one.

When you regenerate digests you lose the proof that you didn't regress.

2023-10-25 12:42 UTC, kbr-scylla commented
> We should have both for a time, then delete the old one.

We have digests both with and without the feature since the very moment the feature was first introduced.

2023-10-25 14:57 UTC, scylladb-promoter commented
#### :red_circle: CI State: FAILURE

:white_check_mark: - Build
:x: - Sanity Tests
:white_check_mark: - Unit Tests
#### Failed Tests (1/21010):
- [test_simple_kill_node_while_decommissioning](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/4386/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/Tests___Sanity_Tests___test_simple_kill_node_while_decommissioning) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_simple_kill_node_while_decommissioning)
#### Build Details:
- Build URL: https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/4386/
- Duration: 2 hr 17 min
- Builder: spider1.cloudius-systems.com

2023-10-25 15:49 UTC, avikivity commented
> > We should have both for a time, then delete the old one.
> 
> We have digests both with and without the feature since the very moment the feature was first introduced.

Ah, in that case we can delete the without case.

2023-10-26 10:42 UTC, kbr-scylla commented
> [test_simple_kill_node_while_decommissioning](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/4386/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/Tests___Sanity_Tests___test_simple_kill_node_while_decommissioning) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_simple_kill_node_while_decommissioning)

flaky test, seen recently: https://github.com/scylladb/scylladb/issues/15146#issuecomment-1758928371
Restarting CI

2023-10-26 13:09 UTC, scylladb-promoter commented
#### :red_circle: CI State: FAILURE

:white_check_mark: - Build
:x: - Sanity Tests
:white_check_mark: - Unit Tests
#### Failed Tests (1/21011):
- [test_replace_stopped_node[use_endpoint-rbo_disabled]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/4402/testReport/junit/replace_address_test/TestReplaceAddress/Tests___Sanity_Tests___test_replace_stopped_node_use_endpoint_rbo_disabled_) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_replace_stopped_node[use_endpoint-rbo_disabled])
#### Build Details:
- Build URL: https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/4402/
- Duration: 2 hr 27 min
- Builder: spider3.cloudius-systems.com

2023-10-26 13:11 UTC, kbr-scylla commented
> [test_replace_stopped_node[use_endpoint-rbo_disabled]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/4402/testReport/junit/replace_address_test/TestReplaceAddress/Tests___Sanity_Tests___test_replace_stopped_node_use_endpoint_rbo_disabled_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_replace_stopped_node%5Buse_endpoint-rbo_disabled%5D)

https://github.com/scylladb/scylladb/issues/15786
restarting CI

2023-10-26 16:25 UTC, scylladb-promoter commented
#### :green_circle: CI State: SUCCESS

:white_check_mark: - Build
:white_check_mark: - Sanity Tests
:white_check_mark: - Unit Tests
#### Build Details:
- Build URL: https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/4410/
- Duration: 2 hr 25 min
- Builder: spider7.cloudius-systems.com

2023-10-27 09:33 UTC, kbr-scylla commented
> Ah, in that case we can delete the without case.

We can't, because a large part of the tests depend on the "without" case but don't have a "with" counterpart. So to be precise -- we have both "without" digests and "with" digests, but at the same time other variables are changing. We can't just delete the "without" digests without sacrificing some coverage -- to keep these cases, we'd have to regenerate the digests. This is why the tests have the "regenerate" option in the first place.

Anyway, the PR is ready to merge.

2023-10-30 10:08 UTC, kbr-scylla commented
@scylladb/scylla-maint please merge

2023-10-30 12:19 UTC, avikivity commented
dequeued due to terrible state of next

2023-10-31 09:12 UTC, kbr-scylla commented
@avikivity please requeue

2023-10-31 11:23 UTC, avikivity commented
> @avikivity please requeue

done

2023-10-31 15:42 UTC, merged