rust: update dependencies
scylladb/scylladb pull request #16378
Opened 2023-12-12 10:02 UTC by wmitros

The currently used versions of "time" and "rustix" depencies had minor security vulnerabilities. This patch updates them to versions with the issues corrected.

Fixes #15772

2023-12-12 15:46 UTC, scylladb-promoter commented
#### :green_circle: CI State: SUCCESS

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/5186/)
:white_check_mark: - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/6582/)
:white_check_mark: - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/5186/)
#### Build Details:
- Duration: 5 hr 42 min
- Builder: monster

2023-12-12 20:52 UTC, nyh requested changes
For the Rust ignorants among us (like me), can you please update the commit message with a slightly more detailed explanation of what you did here? Did you run some command to do all these changes automatically (which command?) - or was some of it manual editing?

In particular, I didn't understand:
1. It looks like the "time" package isn't updated like the commit message claims - instead it looks like it's removed.
2. Why do you need all those new windows (!?) libraries - is this something brought in by other dependencies and we can't avoid them?

2023-12-16 13:19 UTC, wmitros commented
> For the Rust ignorants among us (like me), can you please update the commit message with a slightly more detailed explanation of what you did here? Did you run some command to do all these changes automatically (which command?) - or was some of it manual editing?
> 
> In particular, I didn't understand:
> 
> 1. It looks like the "time" package isn't updated like the commit message claims - instead it looks like it's removed.
> 2. Why do you need all those new windows (!?) libraries - is this something brought in by other dependencies and we can't avoid them?

I added more info to the commit message, please check if it's clear enough now.
I didn't answer the question 2. in the commit message, these new dependencies were a side effect of the performed updates on the problematic packages and sadly there's no way to avoid them (to my knowledge) - it's an issue we have since https://github.com/scylladb/scylladb/pull/13804#discussion_r1195230525

2023-12-16 15:18 UTC, scylladb-promoter commented
#### :green_circle: CI State: SUCCESS

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/5274/)
:white_check_mark: - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/6678/)
:white_check_mark: - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/5274/)
#### Build Details:
- Duration: 2 hr 4 min
- Builder: spider3.cloudius-systems.com

2023-12-17 11:17 UTC, nyh approved these changes

2023-12-17 14:25 UTC, closed without merging

2023-12-26 14:21 UTC, nyh commented
> sadly there's no way to avoid them

A quote from https://tonsky.me/blog/disenchantment/:

> And dependencies? People easily add overengineered “full package solutions” to solve the simplest problems without considering their costs. And those dependencies bring other dependencies. You end up with a tree that is something in between of horror story (OMG so big and full of conflicts) and comedy (there’s no reason we include these, yet here they are

2023-12-26 14:35 UTC, mykaul commented
> > sadly there's no way to avoid them
> 
> A quote from https://tonsky.me/blog/disenchantment/:
> 
> > And dependencies? People easily add overengineered “full package solutions” to solve the simplest problems without considering their costs. And those dependencies bring other dependencies. You end up with a tree that is something in between of horror story (OMG so big and full of conflicts) and comedy (there’s no reason we include these, yet here they are

You should be thankful you don't use NodeJS. I've never seen more deps-over-deps-over-deps than theirs.

2023-12-26 14:41 UTC, nyh commented
> You should be thankful you don't use NodeJS. I've never seen more deps-over-deps-over-deps than theirs.

Maybe nodejs is worst, but Python, Rust and even Yum, is getting worse all the time. We just got Windows (!) dependencies in to Scylla in this patch. Why? Nobody cares any more :-( I think this is a big mistake that will bite all of us (not just at Scylla, the whole world) in a decade, if not sooner. Everybody who complained about C++ not having a package manager will have to eat their hats ;-)