test.py: always override env when executing scylla subprocess
scylladb/scylladb pull request #16577
Opened 2023-12-27 20:45 UTC by kostja

test.py inherits its env from the user, which is the right thing: some python modules, e.g. logging, do accept env-based configuration.

However, test.py also starts subprocesses, i.e. tests, which start other subprocesses, e.g. scylladb instances. And when the instance is started without an explicit configuration file, SCYLLA_CONF from user environment can be used.

If this scylla.conf contains funny parameters, e.g. unsupported configuration options, the tests may break in an unexpected way.

Avoid that by overriding the env in all scylla subprocess invocations (test/pylib/scylla_cluster.py is already clean in that regard).

Fixes all the patched tests on my machine.

2023-12-27 21:46 UTC, nyh requested changes
I think this patch is subtly wrong. As you said, it is the **right thing** that the environment is inherited to subprocesses. Maybe this system needs LD_LIBRARY_PATH to be passed to Scylla to run it correctly correctly? Maybe some subprocess uses shell or Python and needs PYTONPATH or PATH to be set?

If I understand correctly, the only thing that bothered you is that Scylla goes crazy when given SCYLLA_CONF. So I have three answers:

1. You can use in test.py  os.unsetenv() and/or del os.environ['SCYLLA_CONF'] to delete this specific environment variable in, and none of its children will inherit this variable. You don't need to kill the entire environment to remove on variable, and you don't need to do it in 20 different places.
2. You can think maybe it's **wrong** for you to have SCYLLA_CONF in your own environment, because by design, it affects every run of Scylla, which as you noted, is not a good idea. It's almost like setting your PATH to crap, and then being surprised when it affects script that you run and their own sub-scripts.
3. Maybe running Scylla manually requires an option like "--config /dev/null" to avoid any default configuration. If this is the case (?) we can add this option to all Scylla invocation. Or unset SCYLLA_HOME in all these places. It's not the same as erasing the entire environment just to get rid of SCYLLA_HOME.

2023-12-27 22:22 UTC, scylladb-promoter commented
#### :green_circle: CI State: SUCCESS

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/5455/)
:white_check_mark: - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/5455/)
#### Build Details:
- Duration: 1 hr 35 min
- Builder: spider1.cloudius-systems.com

2023-12-28 12:02 UTC, kostja commented
OK, I thikn it's actually a good idea to unset SCYLLA_CONF in test.py once and for all.
Will you accept this approach?

2023-12-28 12:04 UTC, nyh commented
Yes, I think that would be easiest.

2023-12-29 12:43 UTC, kostja commented
Done.

2023-12-29 14:14 UTC, scylladb-promoter commented
#### :green_circle: CI State: SUCCESS

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/5461/)
:white_check_mark: - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/5461/)
#### Build Details:
- Duration: 1 hr 31 min
- Builder: spider6.cloudius-systems.com

2023-12-31 11:02 UTC, nyh approved these changes
Looks good to me, but there's a typo in the commit message (wrong issue number) so I'll fix it myself before merging.
By the way, after this patch, maybe (?) you can remove the "env=" stuff from cluster.py.

2023-12-31 12:53 UTC, closed without merging