Point to KB about RF update from ALTER KEYSPACE reference
scylladb/scylladb pull request #17638
Opened 2024-03-05 19:21 UTC by tzach

This PR adds a two disclaimers to ALTER KEYSPCAE regarding RF update:
- Update RF by one per DC at a time
- Point to KB article How to Safely Increase the Replication Factor

related to https://github.com/scylladb/scylladb/issues/12224

2024-03-05 19:23 UTC, scylladb-promoter commented
## Docs Preview :book:
Docs Preview for this pull request is available [here](http://previews.docs.scylladb.com/scylladb/17638)

**Changed Files:**
- [cql/ddl](http://previews.docs.scylladb.com/scylladb/17638/cql/ddl)
- [kb/rf-increase](http://previews.docs.scylladb.com/scylladb/17638/kb/rf-increase)

**Note:** This preview will be available for 30 days and will be automatically deleted after that period. You can manually trigger a new build by committing changes.

2024-03-06 06:40 UTC, tzach commented on docs/cql/ddl.rst
> +
Ouch. I will fix this ASAP

2024-03-06 08:00 UTC, nyh requested changes
The commit message is incomplete - it talks about adding a link, but the commit is actually adding what seems like new advice (to change RF in steps of 1) - without an explanation (either in the text or the commit message) why this new advice is true.

2024-03-06 08:34 UTC, tzach commented on docs/kb/rf-increase.rst
> +It is recommended to increment RF per a DC by **one** at a time.
Good question.
Demoting this PR to draft till we understand if it makes sense

2026-09-09 09:48 UTC, closed without merging