utils/logalloc: do not allocate memory in reclaim_timer::report()
scylladb/scylladb pull request #18100
Opened 2024-03-29 10:44 UTC by tchaikov

before this change, `reclaim_timer::report()` calls

```c++
fmt::format(", at {}", current_backtrace())
```

which allocates a `std::string` on heap, so it can fail and throw. in that case, `std::terminate()` is called. but at that moment, the reason why `reclaim_timer::report()` gets called is that we fail to reclaim memory for the caller. so we are more likely to run into this issue. anyway, we should not allocate memory in this path.

in this change, a dedicated printer is created so that we don't format to a temporary `std::string`, and instead write directly to the buffer of logger. this avoids the memory allocation.

Fixes #18099
Signed-off-by: Kefu Chai <kefu.chai@scylladb.com>

2024-03-29 11:01 UTC, denesb approved these changes

2024-03-29 11:13 UTC, michoecho requested changes

2024-03-29 11:13 UTC, michoecho commented on utils/logalloc.cc
> +            return fmt::format_to(ctx.out(), ", at{}", msg.backtrace);
You missed a space: `", at{}"` -> `", at {}"`.

2024-03-29 11:13 UTC, michoecho commented on utils/logalloc.cc
> +// for printing extra message in reclaim_timer::report when stall is detected
Please add a comment explaining *why* this struct/formatter is needed.

The purpose is to ensure no dynamic allocations in a function involved in handling OOMs. This code doesn't make this obvious to the reader.

2024-03-29 11:18 UTC, michoecho approved these changes

2024-03-29 11:18 UTC, tchaikov commented
@michoecho hi Michał, thank you again for your review and suggestion.

v2:

- add a missing space in the formatter
- add a comment explaining the rationales why this helper struct and its formatter are introduced.

2024-03-29 13:52 UTC, scylladb-promoter commented
#### :red_circle: CI State: ABORTED

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/7795/)
:white_check_mark: - [Container Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/7795/)
:white_check_mark: - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/8793/)
:white_check_mark: - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/766/)
:white_check_mark: - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/7795/)
#### Build Details:
- Duration: 3 hr 6 min
- Builder: spider5.cloudius-systems.com

2024-03-29 14:02 UTC, scylladb-promoter commented
#### :red_circle: CI State: FAILURE

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/7797/)
:white_check_mark: - [Container Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/7797/)
:x: - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/767/)
:white_check_mark: - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/8794/)
:white_check_mark: - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/7797/)
#### Build Details:
- Duration: 2 hr 44 min
- Builder: spider6.cloudius-systems.com

2024-03-29 18:46 UTC, scylladb-promoter commented
#### :green_circle: CI State: SUCCESS

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/7803/)
:white_check_mark: - [Container Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/7803/)
:white_check_mark: - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/8800/)
:white_check_mark: - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/773/)
:white_check_mark: - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/7803/)
#### Build Details:
- Duration: 2 hr 42 min
- Builder: spider7.cloudius-systems.com

2024-04-01 04:38 UTC, tchaikov commented
> #### 🔴 CI State: FAILURE
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/7797/) ✅ - [Container Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/7797/) ❌ - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/767/) ✅ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/8794/) ✅ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/7797/)
> 
> #### Build Details:
> * Duration: 2 hr 44 min
> * Builder: spider6.cloudius-systems.com

we had a coredump from `repair_additional_test.py::TestRepairAdditional::test_repair_kill_1`. and we don't keep an executable / debuginfo for debugging the coredump. and none of the log files under https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/767/artifact/logs-full.release.001/1711717297927_repair_additional_test.py%3A%3ATestRepairAdditional%3A%3Atest_repair_kill_1/  shows anything suspicious.

2024-04-01 04:42 UTC, tchaikov commented
@scylladb/scylla-maint hello maintainers, could you help queue this change?

2024-04-01 08:01 UTC, nyh approved these changes

2024-04-01 12:03 UTC, closed without merging