cql: verify tuples length in multi-column IN restriction
scylladb/scylladb pull request #18407
Opened 2024-04-24 16:13 UTC by ptrsmrn

This is a port of https://github.com/soft-stech/scylladb/commit/79c9ba76884d6a9630044ba3b5f5dfa68b9c500b

Fixes #13241

2024-04-24 23:55 UTC, scylladb-promoter commented
#### :green_circle: CI State: SUCCESS

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/8261/)
:white_check_mark: - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/8261/)
**The following new/updated tests ran 100 times for each mode:**
:small_blue_diamond: cql-pytest/test_filtering
:small_blue_diamond: cql-pytest/test_restrictions
:white_check_mark: - [Container Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/8261/)
:white_check_mark: - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/1171/)
:white_check_mark: - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/9193/)
:white_check_mark: - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/8261/)
#### Build Details:
- Duration: 2 hr 29 min
- Builder: spider2.cloudius-systems.com

2024-04-25 14:18 UTC, denesb commented
> This is a port of [soft-stech@79c9ba7](https://github.com/soft-stech/scylladb/commit/79c9ba76884d6a9630044ba3b5f5dfa68b9c500b)

Please reference existing commits in the scylla.git repository. The above commit is from a fork and is not part of any branch.

2024-04-25 14:30 UTC, denesb commented
Ah, I just realized this is not a backport, but a cherry-pick of a commit from a fork (a change which was not submitted to scylla.git).

@avikivity what is the procedure in this case?

2026-04-22 09:36 UTC, ptrsmrn commented
UPDATE: 
- rebased on top of the latest master
- reworked commit's msg to include full description of the fix, credits.

2026-04-22 13:30 UTC, ptrsmrn commented
> #### 🔴 CI State: FAILURE
> Mode	Stage	Status	Queue Time	Run Time	Node
> [Checkout](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/28712//pipeline-overview)	✅		2m	spider9.cloudius-systems.com
> [Framework test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/28712//pipeline-overview)	✅		0m	spider9.cloudius-systems.com
> [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/28712//pipeline-overview)	✅	29m	55m	spider13.cloudius-systems.com
> dev	[test.py](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/28712//pipeline-overview)	✅		20m	spider13.cloudius-systems.com
> [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/28712//pipeline-overview)
> 🔹 test_multi_column_relation_wrong_number_of_items_in_tuple
> 🔹 test/cqlpy/test_restrictions.py	✅	0m	2m	spider13.cloudius-systems.com
> release	[test.py](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/28712//pipeline-overview)	❌		39m	spider13.cloudius-systems.com
> #### Failed Tests (1/36293):
> * [test_sstable_write_large_row.release.2](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/28712/testReport/junit/boost.sstable_3_x_test/cc/test_py___release___test_sstable_write_large_row_release_2) [🔍](https://github.com/scylladb/scylladb/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen+test_sstable_write_large_row.release.2)
> 
> 📄 Elasticsearch analysis for **test_sstable_write_large_row**
> Period	CI Failures / Total	CI Pass Rate (%)	Next Failures / Total	Next Pass Rate (%)
> Week (7d)	1/1742	99.94	0/905	100.0
> Month (30d)	1/5719	99.98	0/3524	100.0
> Quarter (90d)	1/14304	99.99	0/8310	100.0
> #### Recent 10 Failures
> Test Name	Arch	Mode	Jenkins Node	Jenkins Job	Ref	Timestamp	Days Ago
> test_sstable_write_large_row.release.2	x86_64	release	spider13.cloudius-systems.com	scylla-master/scylla-ci	PR#18407	2026-04-22 11:23	today
> #### Build Details:
> * Total Queue: 29m
> * Total Run: 2h 29m
> 
> **Note:** To re-trigger CI for this PR, comment: `@scylladbbot trigger-ci`

Reported https://scylladb.atlassian.net/browse/SCYLLADB-1685

2026-04-22 13:30 UTC, ptrsmrn commented
@scylladbbot trigger-ci

2026-04-23 07:12 UTC, ptrsmrn commented
@avikivity @denesb can you please re-review? I know that there's a merge conflict, but I'd like to resolve it together with other comments, if any.

2026-04-23 08:44 UTC, avikivity commented
> This is a port of [soft-stech@79c9ba7](https://github.com/soft-stech/scylladb/commit/79c9ba76884d6a9630044ba3b5f5dfa68b9c500b)
> 
> Fixes #13241

1. This is not an acceptable cover letter.
2. Do we have permission to use this patch.

2026-04-23 08:48 UTC, ptrsmrn commented
> > This is a port of [soft-stech@79c9ba7](https://github.com/soft-stech/scylladb/commit/79c9ba76884d6a9630044ba3b5f5dfa68b9c500b)
> > Fixes #13241
> 
> 1. This is not an acceptable cover letter.

@avikivity Last time you asked for a proper description https://github.com/scylladb/scylladb/pull/18407#issuecomment-2077523746 and I provided one in the commit msg, and thought the cover letter provides some extra info on top of that, and so I left it not to repeat the same in the PR description and in the commit description. But I can change the PR description to have similar info to the one in the commit msg. 

> 2. Do we have permission to use this patch.

@avikivity you said we have: https://github.com/scylladb/scylladb/pull/18407#issuecomment-2077536085.

2026-04-23 08:49 UTC, ptrsmrn commented
> > > This is a port of [soft-stech@79c9ba7](https://github.com/soft-stech/scylladb/commit/79c9ba76884d6a9630044ba3b5f5dfa68b9c500b)
> > > Fixes #13241
> > 
> > 
> > 
> > 1. This is not an acceptable cover letter.
> 
> @avikivity Last time you asked for a proper description [#18407 (comment)](https://github.com/scylladb/scylladb/pull/18407#issuecomment-2077523746) and I provided one in the commit msg, and thought the cover letter provides some extra info on top of that, and so I left it not to repeat the same in the PR description and in the commit description. But I can change the PR description to have similar info to the one in the commit msg.

Done.

> 
> > 2. Do we have permission to use this patch.
> 
> @avikivity you said we have: [#18407 (comment)](https://github.com/scylladb/scylladb/pull/18407#issuecomment-2077536085).

2026-04-23 16:41 UTC, denesb reviewed
> Co-authored-by: Alexander Turetskiy <someone.tur@gmail.com>

Has he signed a CLA?

2026-04-23 16:41 UTC, denesb commented on cql3/expr/restrictions.cc
> +                        valid_size, expr_size, expr));
Wild formatting, we use double indent for broken lines. But in any case, you can just join this all up in a single line.

2026-04-24 06:59 UTC, ptrsmrn commented
> > Co-authored-by: Alexander Turetskiy [someone.tur@gmail.com](mailto:someone.tur@gmail.com)
> 
> Has he signed a CLA?

@denesb yes: https://github.com/scylladb/scylladb/pull/18407#issuecomment-2077536085

2026-04-24 07:00 UTC, ptrsmrn commented on cql3/expr/restrictions.cc
> +                        valid_size, expr_size, expr));
ok, will do when resolving merge conflicts. Other than that, is it approved?

2026-04-24 13:28 UTC, andrzej-jackowski-scylladb approved these changes

2026-04-24 13:28 UTC, andrzej-jackowski-scylladb commented on cql3/expr/restrictions.cc
> +    for (auto expr : elements) {
Isn't it an unneeded copy that we can avoid by using auto&?

2026-04-27 12:32 UTC, nyh requested changes
Looks good, I left a few tiny comments, but I'm asking "request changes" because you forgot the most important thing - to remove the "skip_bug" from test/cqlpy/cassandra_tests/validation/operations/select_multi_column_relation_test.py. I'm calling it "most important" because that test is how I actually discovered #13241 in the first place, when this test reproduced a crash (not every time, but often). We need to verify that this crash was fixed.

The test (testMultiClusteringInvalidQueries) is expected to continue to fail due to  https://github.com/scylladb/scylladb/issues/4244 - so the "xfail" will remain, but the "skip" will be gone, and the xfail will run the test without crashing.

2026-04-27 12:32 UTC, nyh commented on cql3/expr/restrictions.cc
> +    for (auto expr : elements) {
Yes, `const auto&` usually.

2026-04-27 12:32 UTC, nyh commented on cql3/expr/restrictions.cc
> +            if (is<collection_constructor>(binop.rhs)) {
nitpick: it feels like you put half the expression-unwrapping code here, and half inside validate_tuples_size() function. It feels to me like the validate_tuples_size() could just take rhs and have all this extra layer of unwrapping it.

2026-04-27 12:32 UTC, nyh commented on test/cqlpy/test_filtering.py
> +        with pytest.raises(InvalidRequest, match='Expected 3 elements in value tuple, but got 5'):
I think that this test (before your patch) was written while I wasn't paying attention :-(

Please verify that after your patch, the test also passes on Cassandra (`test/cqlpy/run-cassandra test_filtering.py::test_multi_column_relation_wrong_number_of_items_in_tuple`), I don't know what the error messages look like in Cassandra.

2026-04-27 12:33 UTC, nyh commented on cql3/expr/restrictions.cc
> +    for (auto expr : elements) {
Third person (in this case, artificial person ;-)) to make the same suggestion.

2026-04-28 08:03 UTC, ptrsmrn commented on test/cqlpy/test_filtering.py
> +        with pytest.raises(InvalidRequest, match='Expected 3 elements in value tuple, but got 5'):
Right. Cassandra cross-check passes.

2026-04-28 08:05 UTC, ptrsmrn commented on cql3/expr/restrictions.cc
> +    for (auto expr : elements) {
Switched to const auto&

2026-04-28 08:06 UTC, ptrsmrn commented on cql3/expr/restrictions.cc
> +                        valid_size, expr_size, expr));
Done, joined into a single line.

2026-04-28 08:07 UTC, ptrsmrn commented on cql3/expr/restrictions.cc
> +                }
You're right — that branch was unreachable safely (a constant is not a collection_constructor, so it would have thrown bad_variant_access if ever hit). Removed it as part of the refactor that consolidates rhs unwrapping inside validate_tuples_size. A serialized list constant can't reach this validator pre-prepare anyway, and post-prepare arity has already been checked elsewhere.

2026-04-28 08:07 UTC, ptrsmrn commented on cql3/expr/restrictions.cc
> +    for (auto expr : elements) {
Already addressed.

2026-04-28 08:07 UTC, ptrsmrn commented on cql3/expr/restrictions.cc
> +            if (is<collection_constructor>(binop.rhs)) {
Done. validate_tuples_size now takes (const expression& rhs, size_t valid_size) and does the unwrapping itself. The call site in preliminary_binop_validation_checks is now a single line. As a side benefit, this also eliminates the buggy as<collection_constructor>(constant) branch that Copilot flagged.

2026-04-28 08:09 UTC, ptrsmrn commented
UPDATE 1:
- rebased on top of latest master
- removed skip pytest mark from a test highlighting this issue
- refactored the code per comments
- tested against C*

2026-04-28 08:57 UTC, nyh approved these changes
Very nice. Thanks.
I can't merge yet because we're in a merge freeze.

2026-05-11 08:11 UTC, ptrsmrn commented
@scylladbbot trigger-ci

2026-05-11 08:13 UTC, ptrsmrn commented
@scylladb/releng seems like, after force pushing changes, Ci job did run, but didn't post a summary once completed, perhaps cause it failed on a flaky test.

2026-05-11 08:17 UTC, ptrsmrn commented
Opened https://scylladb.atlassian.net/browse/SCYLLADB-1911 against the flaky test.

2026-05-11 08:18 UTC, ptrsmrn commented
> Very nice. Thanks. I can't merge yet because we're in a merge freeze.

Thanks @nyh . I needed to re-rerun the CI, will let you know once it's green.

2026-05-11 13:20 UTC, ptrsmrn commented
@scylladb/scylla-maint please consider merging

2026-05-11 21:33 UTC, closed without merging