service/storage_proxy: add useful version of base write throttle metrics
scylladb/scylladb pull request #18435
Opened 2024-04-26 08:07 UTC by denesb

There are two metrics to help observe base-write throttling:
* current_throttled_base_writes
* last_mv_flow_control_delay

Both show a snapshot of what is happening right at the time of querying these metrincs. This doesn't work well when one wants to investigate the role throttling is playing in occasional write timeouts.s Prometheus scrapes metrics in multi-second intervals, and the probability of that instant catching the throttling at play is very small (almost zero). Add two new metrics:
* throttled_base_writes
* mv_flow_control_delay

These accumulate all values, allowing graphana to derive the values and extract information about throttle events that happened in the past (but not necessarily at the instant of the scrape). Note that dividing the two values, will yield the average delay for a throttle, which is also useful.

- [ ] ** Backport reason (please explain below if this patch should be backported or not) **

2024-04-26 12:50 UTC, scylladb-promoter commented
#### :green_circle: CI State: SUCCESS

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/8324/)
:white_check_mark: - [Container Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/8324/)
:white_check_mark: - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/9239/)
:white_check_mark: - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/1217/)
:white_check_mark: - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/8324/)
#### Build Details:
- Duration: 4 hr 42 min
- Builder: i-07a748b8ca5c9e3fa (m5ad.12xlarge)

2024-04-26 12:52 UTC, amnonh requested changes
Please make the following changes:
* Make them both counters
* Their name end with the _total suffix
* Add _skip_when_empty() to the metrics

2024-04-30 06:00 UTC, denesb commented
New in v2:
* Rebased
* Added `_total` suffix to new metrics, make them counters and add `set_skip_when_empty()` to them.

2024-04-30 06:13 UTC, amnonh approved these changes
I lean towards OK it because we're not as strict about metric names as we should be. This means that one day, we'll need to change all those metrics (including this one) to use base units if possible (in this case seconds) and at least have the name reflect the used unit.

This is just FYI,  as this is just one more such metric., I'm ok, if you want to keep it this way.
If you want to make any changes (up to you) add a few words in the descriptions, on what those metrics value indicates especially (such as when the value is growing/non zero etc')

2024-04-30 06:43 UTC, denesb commented
> If you want to make any changes (up to you) add a few words in the descriptions, on what those metrics value indicates especially (such as when the value is growing/non zero etc')

I added a few more words, but trying to explain these in the description, quickly makes the text explode and we are sending these on every scrape...

2024-04-30 06:54 UTC, amnonh commented
> > If you want to make any changes (up to you) add a few words in the descriptions, on what those metrics value indicates especially (such as when the value is growing/non zero etc')
> 
> I added a few more words, but trying to explain these in the description, quickly makes the text explode and we are sending these on every scrape...

We don't have to, our Prometheus implementation supports "quite" mode, you can request the metrics without the help messages

2024-04-30 07:10 UTC, denesb commented
> We don't have to, our Prometheus implementation supports "quite" mode, you can request the metrics without the help messages

Ok, good to know, I expanded the description a bit more. Is it ok to cross-reference metrics (in their description)?

2024-04-30 07:14 UTC, amnonh commented
@denesb This is very good, it gives the exact information someone needs when they try to use the metrics.

LGTM

2024-04-30 21:09 UTC, vladzcloudius approved these changes
Looks very good. Thanks, Botond!

2024-05-01 05:52 UTC, denesb commented
@scylladb/scylla-maint ping.

2024-05-13 11:23 UTC, denesb commented
@scylladb/scylla-maint ping.

2024-05-14 02:40 UTC, closed without merging