compaction_strategy.cc: typo -> "performanceimproves" -> "performance…
scylladb/scylladb pull request #18629
Opened 2024-05-12 11:26 UTC by mykaul

… improves"

- [ ] ** Benign typo, no need to backport **

2024-05-12 11:29 UTC, avikivity approved these changes

2024-05-12 13:51 UTC, tchaikov requested changes
@mykaul hi Yaniv, you might want to drop the submodule changes in this PR. i guess they were included by accident.

2024-05-12 14:48 UTC, mykaul commented
> @mykaul hi Yaniv, you might want to drop the submodule changes in this PR. i guess they were included by accident.

Indeed :(

2024-05-12 14:50 UTC, mykaul commented
> > @mykaul hi Yaniv, you might want to drop the submodule changes in this PR. i guess they were included by accident.
> 
> Indeed :(

Fixed.

2024-05-12 20:47 UTC, scylladb-promoter commented
#### :green_circle: CI State: SUCCESS

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/8731/)
:white_check_mark: - [Container Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/8731/)
:white_check_mark: - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/9552/)
:white_check_mark: - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/1530/)
:white_check_mark: - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/8731/)
#### Build Details:
- Duration: 5 hr 56 min
- Builder: i-0f27ebc5d43ed1b98 (m5ad.8xlarge)

2024-05-13 01:58 UTC, tchaikov approved these changes
lgtm

2024-05-13 05:43 UTC, denesb approved these changes

2024-05-13 05:44 UTC, mykaul commented
> > > @mykaul hi Yaniv, you might want to drop the submodule changes in this PR. i guess they were included by accident.
> > 
> > 
> > Indeed :(
> 
> Fixed.

I do wonder why it happens all the time - that I got those submodule updates. My fault for pushing them into the commit, but I'm not sure why they are always modified.

2024-05-13 05:48 UTC, denesb commented
> I do wonder why it happens all the time - that I got those submodule updates. My fault for pushing them into the commit, but I'm not sure why they are always modified.

Submodules are rarely updated (maybe ~1/week), but they do require you running `git submodule update` so they do not appear as changes in your local repo (and hence can be accidentally added to commits).
I recommend running `git submodule update` every time you pull the latest master. That way you will avoid rouge submodule updates in your commits.

2024-05-13 10:56 UTC, avikivity commented
Also, use `git add -p` to see what you are committing.

2024-05-13 16:45 UTC, closed without merging