doc: add the tablets limitation to the nodetool describering command
scylladb/scylladb pull request #18940
Opened 2024-05-28 15:37 UTC by annastuchlik

This PR adds a note to the `nodetool describering` command that the command cannot be used with tablets.

Refs https://github.com/scylladb/scylladb/pull/17163

Backport to branch-6.0 required. This PR adds tablet-related information valid since 6.0.

2024-05-28 16:13 UTC, bhalevy commented
@denesb added a parameter to specify the table when the keyspace is tablets-aware, but the docs weren't updated.

See https://github.com/scylladb/scylladb/pull/17163#issuecomment-1945769453

2024-05-28 17:29 UTC, tzach approved these changes

2024-05-29 07:20 UTC, denesb commented
> @denesb Could you suggest improvements to this PR or open another PR to document how the command works with tablets?

For a tablet keyspace, one just has to also provide a tablet parameter. That is the only difference.

2024-05-29 07:21 UTC, denesb commented
> > @denesb Could you suggest improvements to this PR or open another PR to document how the command works with tablets?
> 
> For a tablet keyspace, one just has to also provide a tablet parameter. That is the only difference.

If invoked on a tablet keyspace, without a table param, it will raise an error.

2024-05-29 11:28 UTC, bhalevy approved these changes
LGTM

2024-05-29 11:30 UTC, denesb requested changes

2024-05-29 11:30 UTC, denesb commented on docs/operating-scylla/nodetool-commands/describering.rst
> +The command displays the description of all tables in the keyspace.
The command doesn't describe the tables, it describes the keyspace's ring.

2024-05-29 11:30 UTC, denesb commented on docs/operating-scylla/nodetool-commands/describering.rst
> +the description of the table.
The command will display the ring of the table.

2024-05-29 12:31 UTC, denesb approved these changes

2024-05-29 20:32 UTC, closed without merging