fix uninitialized LWT write contention counter
scylladb/scylladb pull request #19625
Opened 2024-07-05 13:18 UTC by wprzytula

When debugging the issue of high LWT write contention metric, we (the drivers team) discovered that at least 3 drivers (Go, Java, Rust) cause high numbers in that metrics in LWT workloads - we doubted that all those drivers route LWT queries badly. We tried to understand that metric and its semantics. It took 3 people over 10 hours to figure out what it is supposed to count and why the numbers are so unexpected.

People from core team were confident that it must be drivers sending requests to different shards, causing contention. Then we ran the workload against a single node single shard cluster... and observed contention. Finally, we looked into the Scylla code and saw it.

**Uninitialized stack value.**

The core member was shocked. But we, the drivers people, felt we always knew it. It's yet another time that we are blamed for a server-side issue. We rebuilt scylla with the variable initialized to 0 and the metric kept being 0.

To prevent such errors in the future, let's consider some lints that warn against uninitialized variables. This is such an obvious feature of e.g. Rust, and yet this has shown to be cause a painful bug in 2024.

2024-07-05 13:34 UTC, kbr-scylla requested changes
- the contention counter is using for reads too, not only for writes, so you can generalize the commit message a bit
- please include `storage_proxy: ` prefix in the commit title following our convention

2024-07-05 13:42 UTC, kbr-scylla approved these changes

2024-07-05 13:46 UTC, kbr-scylla commented
Note: we don't have automation for this, but we'll have to backport it to 2023.1 too once it gets into `enterprise` branch

2024-07-05 13:52 UTC, nyh commented
Nice (and sad) catch.

While a Rust fan might indeed conclude that we need a better compiler or linter to catch these bugs for us, a unit test fan like myself would suggest that this bug means that someone added a metric without writing a test for it. Ideally, a test for this metric would check that the metric increases when it should, and doesn't increase when it shouldn't.
True, in this case a better compiler might have caught this bug without writing a test. But we can have more subtle bugs and not adding features without tests (including "small" features like metrics) can help avoid these bugs.

2024-07-05 14:17 UTC, kostja commented
It's a good catch but I would remove from the commit message any mention of the misrouting, since it's irrelevant. We know misrouting is the case from the paxos level trace logs, not from the metrics. We, however, still have not identified that it's not their misconfiguration or wrong consistency level, or what not. So your help with the enterprise issue is still needed and would be greatly appreciated.

2024-07-05 14:22 UTC, kostja commented
It's apparently a regression that crept in during coroutinization of this code.

2024-07-07 08:19 UTC, gleb-cloudius approved these changes
clang is usually good at warning about  potential use of non initialized value, but here the code seams to be to complicated of it to trigger.

2024-07-08 08:41 UTC, kbr-scylla commented
CI run died: https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/10238/ (cc @yaronkaikov)
restarting

2024-07-08 11:42 UTC, roydahan commented
We re-ran the CI here: https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/10262/
(Networking issue in Israeli office terminated the original one)

2024-07-08 13:41 UTC, scylladb-promoter commented
#### :green_circle: CI State: SUCCESS

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/10262/)
:white_check_mark: - [Container Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/10262/)
:white_check_mark: - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/2503/)
:white_check_mark: - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/10528/)
:white_check_mark: - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/10262/)
#### Build Details:
- Duration: 2 hr 25 min
- Builder: spider2.cloudius-systems.com

2024-07-08 13:53 UTC, avikivity commented
> It's apparently a regression that crept in during coroutinization of this code.

Why didn't ubsan catch it?

2024-07-08 14:49 UTC, nyh commented
> > It's apparently a regression that crept in during coroutinization of this code.
> 
> Why didn't ubsan catch it?

I don't think -fsanitize=undefined does this, there is a separate -fsanitize=memory that does this (https://clang.llvm.org/docs/MemorySanitizer.html).

2024-07-08 15:08 UTC, avikivity commented
> > > It's apparently a regression that crept in during coroutinization of this code.
> > 
> > 
> > Why didn't ubsan catch it?
> 
> I don't think -fsanitize=undefined does this, there is a separate -fsanitize=memory that does this (https://clang.llvm.org/docs/MemorySanitizer.html).

Ouch. I see it's impractical to enable it, since it requires that libraries be sanitized too.

2024-07-08 15:18 UTC, avikivity commented
@wprzytula please file a  bug and add a Fixes line to the commit changelog.

2024-07-08 15:26 UTC, nyh commented
> Ouch. I see it's impractical to enable it, since it requires that libraries be sanitized too.

I think in general this is true - if you have an uninitialized variable and pass it to a function, the sanitizer doesn't want to complain yet because maybe the function doesn't use this uninitialized parameter (e.g., the C library function open() only uses its "mode" parameter if the file is actually created - depending on other parameters). However, in our case, the "counter++" operation happens in our own code, so the memory sanitizer should have caught it (I think, I never tried it myself).

2024-07-08 15:42 UTC, avikivity commented
> @wprzytula please file a bug and add a Fixes line to the commit changelog.

It's not enough to update the cover letter, please update the commit changelog too.

Single-patch pull requests dump the cover letter and only include the commit changelog.

2024-07-08 15:43 UTC, avikivity commented
> > Ouch. I see it's impractical to enable it, since it requires that libraries be sanitized too.
> 
> I think in general this is true - if you have an uninitialized variable and pass it to a function, the sanitizer doesn't want to complain yet because maybe the function doesn't use this uninitialized parameter (e.g., the C library function open() only uses its "mode" parameter if the file is actually created - depending on other parameters). However, in our case, the "counter++" operation happens in our own code, so the memory sanitizer should have caught it (I think, I never tried it myself).

I don't think we want to enable the memory sanitizer in order to catch this already-fixed bug but emit thousands of false positives due to variables initialized in libraries.

2024-07-08 17:10 UTC, closed without merging

2024-07-08 18:49 UTC, scylladb-promoter commented
#### :green_circle: CI State: SUCCESS

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/10270/)
:white_check_mark: - [Container Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/10270/)
:white_check_mark: - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/10533/)
:white_check_mark: - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/2508/)
:white_check_mark: - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/10270/)
#### Build Details:
- Duration: 2 hr 38 min
- Builder: spider1.cloudius-systems.com