[Backport 6.0] db/hints: Add logging when ignoring hint directories
scylladb/scylladb pull request #19892
Opened 2024-07-26 11:15 UTC by dawmd

In 2446cce, we stopped trying to attempt to create endpoint managers for invalid hint directories
even when their names represented IP addresses or
host IDs. In this commit, we add logging informing the user about it.

Refs scylladb/scylladb#19173

(cherry picked from commit a5528a2)

2024-07-26 11:16 UTC, dawmd commented
Needed by scylladb/scylla-dtest#4656

2024-07-26 12:04 UTC, tchaikov requested changes
@dawmd hi Dawid, could you cherry-pick the original commit using `git cherry-pick -x a5528a209340fc2badee5b5e62ef2de5af1d94a8` ? it's weird that the cover letter of this PR does look right, but the commit message is missing the line of 
```
(cherry picked from commit a5528a209340fc2badee5b5e62ef2de5af1d94a8)
```

2024-07-26 13:14 UTC, tchaikov approved these changes
lgtm

2024-08-07 08:54 UTC, piodul approved these changes

2024-08-07 08:55 UTC, piodul commented
Queued

2024-08-18 10:20 UTC, mykaul commented
https://github.com/scylladb/scylladb/commit/d065d6f05de3a72f92ae0c93e7c78e37a136cdca

2024-08-18 10:20 UTC, closed without merging