doc: add the 6.0-to-6.1 upgrade guide
scylladb/scylladb pull request #19983
Opened 2024-08-01 13:58 UTC by annastuchlik

This PR adds the 6.0-to-6.1 upgrade guide (including metrics) and removes the 5.4-to-6.0 upgrade guide.

Compared 5.4-to-6.0, the the 6.0-to-6.1 guide:

- Added the "Ensure Consistent Topology Changes Are Enabled" prerequisite.
- Removed the "After Upgrading Every Node" section. Both Raft-based schema changes and topology updates
  are mandatory in 6.1 and don't require any user action after upgrading to 6.1.
- Removed the "Validate Raft Setup" section. Raft was enabled in all 6.0 clusters (for schema management),
  so now there's no scenario that would require the user to follow the validation procedure.
- Removed the references to the Enable Consistent Topology Updates page (which was in version 6.0 and is removed with this PR) across the docs.

See the individual commits for more details.

Fixes https://github.com/scylladb/scylladb/issues/19853
Fixes https://github.com/scylladb/scylladb/issues/19933

This PR must be backported to branch-6.1 as it is critical in version 6.1.

2024-08-01 14:01 UTC, scylladb-promoter commented
## Docs Preview :book:
Docs Preview for this pull request is available [here](http://previews.docs.scylladb.com/scylladb/19983)

**Changed Files:**
- [alternator/compatibility](http://previews.docs.scylladb.com/scylladb/19983/alternator/compatibility)
- [architecture/_common/consistent-topology-with-raft-upgrade-info](http://previews.docs.scylladb.com/scylladb/19983/architecture/_common/consistent-topology-with-raft-upgrade-info)
- [architecture/raft](http://previews.docs.scylladb.com/scylladb/19983/architecture/raft)
- [operating-scylla/procedures/cluster-management/_common/membership-change-failures-note](http://previews.docs.scylladb.com/scylladb/19983/operating-scylla/procedures/cluster-management/_common/membership-change-failures-note)
- [operating-scylla/procedures/cluster-management/_common/system-auth-alter-info](http://previews.docs.scylladb.com/scylladb/19983/operating-scylla/procedures/cluster-management/_common/system-auth-alter-info)
- [operating-scylla/procedures/cluster-management/_common/upgrade-note-add-new-dc](http://previews.docs.scylladb.com/scylladb/19983/operating-scylla/procedures/cluster-management/_common/upgrade-note-add-new-dc)
- [operating-scylla/procedures/cluster-management/_common/upgrade-note-add-new-node](http://previews.docs.scylladb.com/scylladb/19983/operating-scylla/procedures/cluster-management/_common/upgrade-note-add-new-node)
- [operating-scylla/procedures/cluster-management/_common/upgrade-note-remove-node](http://previews.docs.scylladb.com/scylladb/19983/operating-scylla/procedures/cluster-management/_common/upgrade-note-remove-node)
- [operating-scylla/procedures/cluster-management/_common/upgrade-note-replace-node](http://previews.docs.scylladb.com/scylladb/19983/operating-scylla/procedures/cluster-management/_common/upgrade-note-replace-node)
- [operating-scylla/procedures/cluster-management/_common/upgrade-warning-add-new-node-or-dc](http://previews.docs.scylladb.com/scylladb/19983/operating-scylla/procedures/cluster-management/_common/upgrade-warning-add-new-node-or-dc)
- [operating-scylla/procedures/cluster-management/_common/upgrade-warning-remove-node](http://previews.docs.scylladb.com/scylladb/19983/operating-scylla/procedures/cluster-management/_common/upgrade-warning-remove-node)
- [operating-scylla/procedures/cluster-management/_common/upgrade-warning-replace-node](http://previews.docs.scylladb.com/scylladb/19983/operating-scylla/procedures/cluster-management/_common/upgrade-warning-replace-node)
- [operating-scylla/procedures/cluster-management/add-dc-to-existing-dc](http://previews.docs.scylladb.com/scylladb/19983/operating-scylla/procedures/cluster-management/add-dc-to-existing-dc)
- [operating-scylla/procedures/cluster-management/add-node-to-cluster](http://previews.docs.scylladb.com/scylladb/19983/operating-scylla/procedures/cluster-management/add-node-to-cluster)
- [operating-scylla/procedures/cluster-management/remove-node](http://previews.docs.scylladb.com/scylladb/19983/operating-scylla/procedures/cluster-management/remove-node)
- [operating-scylla/procedures/cluster-management/replace-dead-node](http://previews.docs.scylladb.com/scylladb/19983/operating-scylla/procedures/cluster-management/replace-dead-node)
- [operating-scylla/procedures/cluster-management/update-topology-strategy-from-simple-to-network](http://previews.docs.scylladb.com/scylladb/19983/operating-scylla/procedures/cluster-management/update-topology-strategy-from-simple-to-network)
- [operating-scylla/security/_common/upgrade-note-authentication](http://previews.docs.scylladb.com/scylladb/19983/operating-scylla/security/_common/upgrade-note-authentication)
- [operating-scylla/security/_common/upgrade-note-runtime-authentication](http://previews.docs.scylladb.com/scylladb/19983/operating-scylla/security/_common/upgrade-note-runtime-authentication)
- [operating-scylla/security/_common/upgrade-warning-authentication](http://previews.docs.scylladb.com/scylladb/19983/operating-scylla/security/_common/upgrade-warning-authentication)
- [operating-scylla/security/_common/upgrade-warning-runtime-authentication](http://previews.docs.scylladb.com/scylladb/19983/operating-scylla/security/_common/upgrade-warning-runtime-authentication)
- [operating-scylla/security/authentication](http://previews.docs.scylladb.com/scylladb/19983/operating-scylla/security/authentication)
- [operating-scylla/security/runtime-authentication](http://previews.docs.scylladb.com/scylladb/19983/operating-scylla/security/runtime-authentication)
- [troubleshooting/_common/enable-consistent-topology](http://previews.docs.scylladb.com/scylladb/19983/troubleshooting/_common/enable-consistent-topology)
- [troubleshooting/_common/enabling-consistent-topology-failure](http://previews.docs.scylladb.com/scylladb/19983/troubleshooting/_common/enabling-consistent-topology-failure)
- [troubleshooting/_common/system-auth-name-info](http://previews.docs.scylladb.com/scylladb/19983/troubleshooting/_common/system-auth-name-info)
- [troubleshooting/password-reset](http://previews.docs.scylladb.com/scylladb/19983/troubleshooting/password-reset)
- [upgrade/upgrade-opensource/index.html](http://previews.docs.scylladb.com/scylladb/19983/upgrade/upgrade-opensource/index.html)
- [upgrade/upgrade-opensource/upgrade-guide-from-5.4-to-6.0/enable-consistent-topology](http://previews.docs.scylladb.com/scylladb/19983/upgrade/upgrade-opensource/upgrade-guide-from-5.4-to-6.0/enable-consistent-topology)
- [upgrade/upgrade-opensource/upgrade-guide-from-5.4-to-6.0/index.html](http://previews.docs.scylladb.com/scylladb/19983/upgrade/upgrade-opensource/upgrade-guide-from-5.4-to-6.0/index.html)

**Note:** This preview will be available for 30 days and will be automatically deleted after that period. You can manually trigger a new build by committing changes.

2024-08-05 13:00 UTC, kbr-scylla requested changes

2024-08-05 13:23 UTC, kbr-scylla commented on docs/operating-scylla/procedures/cluster-management/_common/membership-change-failures-note.rst
> +    * `Manually enabled consistent topology updates <https://opensource.docs.scylladb.com/stable/upgrade/upgrade-opensource/upgrade-guide-from-5.4-to-6.0/enable-consistent-topology.html>`_
>  I'll replace the stable links with links to the branch-6.0:

OK

2024-08-05 14:35 UTC, kbr-scylla commented on docs/upgrade/upgrade-opensource/upgrade-guide-from-6.0-to-6.1/upgrade-guide-from-6.0-to-6.1-generic.rst
> +  the `Enable Consistent Topology Updates <https://opensource.docs.scylladb.com/stable/upgrade/upgrade-opensource/upgrade-guide-from-5.4-to-6.0/enable-consistent-topology.html>`_
Missed this one @annastuchlik

2024-08-05 14:36 UTC, kbr-scylla commented on docs/operating-scylla/procedures/cluster-management/_common/membership-change-failures-note.rst
> +    * `Manually enabled consistent topology updates <https://opensource.docs.scylladb.com/stable/upgrade/upgrade-opensource/upgrade-guide-from-5.4-to-6.0/enable-consistent-topology.html>`_
> Done. Can you approve now, or do you have other suggestions?

Missed one

2024-08-05 19:02 UTC, yaronkaikov approved these changes

2024-08-06 10:17 UTC, merged