repair: Add repair_hosts_filter and repair_dcs_filter
scylladb/scylladb pull request #21985
Opened 2024-12-19 13:40 UTC by asias

They will be useful for hosts and DCs selection for the repair scheduler. It is not implemented yet. Adding it earlier, so we do not need to change the system tabler later.

No backport. This code is not released in any release yet.

2024-12-19 13:42 UTC, asias commented
I marked this as release block so we can release this together with the tablet repair scheduler code.

2024-12-19 21:36 UTC, scylladb-promoter commented
#### :green_circle: CI State: SUCCESS

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/13967/)
:white_check_mark: - [Docker Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-docker/806/)
:white_check_mark: - [Offline-installer Artifact Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-offline-installer/208/)
:white_check_mark: - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/2417/)
:white_check_mark: - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/13548/)
:white_check_mark: - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/5534/)
:white_check_mark: - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/13967/)
#### Build Details:
- Duration: 7 hr 55 min
- Builder: spider7.cloudius-systems.com

2024-12-22 14:57 UTC, mykaul commented
> I marked this as release block so we can release this together with the tablet repair scheduler code.

For which version?

2024-12-23 00:13 UTC, asias commented
> > I marked this as release block so we can release this together with the tablet repair scheduler code.
> 
> For which version?

The one after 6.2. I assume it is 2025.1.0.

2025-01-09 09:46 UTC, mykaul commented
@asias - is this ready for review?

2025-01-09 09:49 UTC, asias commented
Yes.

On Thu, Jan 9, 2025, 17:46 Yaniv Kaul ***@***.***> wrote:

> @asias <https://github.com/asias> - is this ready for review?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/scylladb/scylladb/pull/21985#issuecomment-2579610856>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACOETBQFHSG4SNIKLMYIUL2JZAPVAVCNFSM6AAAAABT5ARPVCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNZZGYYTAOBVGY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2025-01-09 11:22 UTC, mykaul commented
@scylladb/scylla-maint - please review.

2025-01-09 11:52 UTC, denesb requested changes

2025-01-09 11:52 UTC, denesb commented on locator/tablets.hh
> +    sstring repair_dcs_filter;
I'm not sure this is a good idea: adding these fields here without a current use.

We can add new fields any time, no problem, but we can never remove them or change their type once added.

So even though we had a functional POC for automatic repair where these were used, I think we shouldn't add these now, instead we should wait to add them only together with the automatic repair code, once properly reviewed and agreed upon.

2025-01-09 12:46 UTC, asias commented on locator/tablets.hh
> +    sstring repair_dcs_filter;
Note, this is not adding columns in the table. It is adding a new field in the UDT of a system table.  We never do this before.  It is risky to add later. 

This has nothing to do with auto repair. It is not for auto repair at all. It is a basic config for tablet repair scheduler to allow user to select what hosts or dcs to repair. Currently, the tablet repair scheduler will always repair all replica nodes. 

We will almost certainly add this option support so we do not have function level regression from the user perceptive.  Currently, users can limit repair to a selected DCs or hosts with vnode tables. Without this, we could not do that with tablet tables.

2025-01-09 12:59 UTC, denesb approved these changes

2025-01-14 21:53 UTC, closed without merging