Introduce file stream for tablet
scylladb/scylladb pull request #22034
Opened 2024-12-24 02:24 UTC by asias

File based stream is a new feature that optimizes tablet movement significantly. It streams the entire SSTable files without deserializing SSTable files into mutation fragments and re-serializing them back into SSTables on receiving nodes. As a result, less data is streamed over the network, and less CPU is consumed, especially for data models that contain small cells.

The following patches are imported.

*) Merge 'Introduce file stream for tablet' from Asias He

    This patch uses Seastar RPC stream interface to stream sstable files on
    network for tablet migration.

    It streams sstables instead of mutation fragments. The file based
    stream has multiple advantages over the mutation streaming.

    - No serialization or deserialization for mutation fragments
    - No need to read and process each mutation fragments
    - On wire data is more compact and smaller

    In the test below, a significant speed up is observed.

    Two nodes, 1 shard per node, 1 initial_tablets:

    - Start node 1
    - Insert 10M rows of data with c-s
    - Bootstrap node 2

    Node 1 will migration data to node2 with the file stream.

    Test results:

    1) File stream: bytes on wire = 1132006250 bytes, bw = 836MB/s

    [shard 0:stre] stream_blob - stream_sstables[eadaa8e0-a4f2-4cc6-bf10-39ad1ce106b0]
	Finished sending sstable_nr=2 files_nr=18 files={} range=(-1,9223372036854775807] bytes_sent=1132006250 stream_bw=836MB/s
    [shard 0:stre] storage_service - Streaming for tablet migration of a4f68900-568a-11ee-b7b9-c2b13945eed2:1 took 1.08004s seconds

    2) Mutation stream: bytes on wire = 3030004736 bytes, bw = 125410.87 KiB/s = 128MB/s

    [shard 0:stre] stream_session - [Stream #406dc8b0-56b5-11ee-bc2d-000bf4871058]
	Streaming plan for Tablet migration-ks1-index-0 succeeded, peers={127.0.0.1}, tx=0 KiB, 0.00 KiB/s, rx=2958989 KiB, 125410.87 KiB/s
    [shard 0:stre] storage_service - Streaming for tablet migration of a4f68900-568a-11ee-b7b9-c2b13945eed2:1 took 23.5992s seconds

    Test Summary:

    File stream v.s. Mutation stream improvements

    - Stream bandwidth = 836 / 128  (MB/s)  = 6.53X

    - Stream time = 23.60 / 1.08  (Seconds) = 21.85X

    - Stream bytes on wire = 3030004736 / 1132006250 (Bytes)= 2.67X

    Closes scylladb/scylla-enterprise#3438

    * github.com:scylladb/scylla-enterprise: tests: Add file_stream_test streaming: Implement file stream for tablet

*) streaming: Use new take_storage_snapshot interface

    The new take_storage_snapshot returns a file object instead of a file
    name. This allows the file stream sender to read from the file even if
    the file is deleted by compaction.

    Closes scylladb/scylla-enterprise#3728

*) streaming: Protect unsupported file types for file stream

    Currently, we assume the file streamed over the stream_blob rpc verb is
    a sstable file. This patch rejects the unsupported file types on the
    receiver side. This allows us to stream more file types later using the
    current file stream infrastructure without worrying about old nodes
    processing the new file types in the wrong way.

    - The file_ops::noop is renamed to file_ops::stream_sstables to be explicit about the file types

    - A missing test_file_stream_error_injection is added to the idl

    Fixes: #3846
    Tests: test_unsupported_file_ops

    Closes scylladb/scylla-enterprise#3847

*) idl: Add service::session_id id to idl

    It will be used in the next patch.

    Refs #3907

*) streaming: Protect file stream with topology_guard

    Similar to "storage_service, tablets: Use session to guard tablet
    streaming", this patch protects file stream with topology_guard.

    Fixes #3907

*) streaming: Take service topology_guard under the try block

    Taking the service::topology_guard could throw. Currently, it throws
    outside the try block, so the rpc sink will not be closed, causing the
    following assertion:

    ```
    scylla: seastar/include/seastar/rpc/rpc_impl.hh:815: virtual
    seastar::rpc::sink_impl<netw::serializer,
    streaming::stream_blob_cmd_data>::~sink_impl() [Serializer =
    netw::serializer, Out = <streaming::stream_blob_cmd_data>]: Assertion
    `this->_con->get()->sink_closed()' failed.
    ```

    To fix, move more code including the topology_guard taking code to the
    try block.

    Fixes https://github.com/scylladb/scylla-enterprise/issues/4106

    Closes scylladb/scylla-enterprise#4110

*) Merge 'Preserve original SSTable state with file based tablet migration' from Raphael "Raph" Carvalho

    We're not preserving the SSTable state across file based migration, so
    staging SSTables for example are being placed into main directory, and
    consequently, we're mixing staging and non-staging data, losing the
    ability to continue from where the old replica left off.
    It's expected that the view update backlog is transferred from old
    into new replica, as migration doesn't wait for leaving replica to
    complete view update work (which can take long). Elasticity is preferred.

    So this fix guarantees that the state of the SSTable will be preserved
    by propagating it in form of subdirectory (each subdirectory is
    statically mapped with a particular state).

    The staging sstables aren't being registered into view update generator
    yet, as that's supposed to be fixed in OSS (more details can be found
    at https://github.com/scylladb/scylladb/issues/19149).

    Fixes #4265.

    Closes scylladb/scylla-enterprise#4267

    * github.com:scylladb/scylla-enterprise: tablet: Preserve original SSTable state with file based tablet migration sstables: Add get method for sstable state

*) sstable: (Re-)add shareabled_components getter

*) Merge 'File streaming sstables: Use sstable source/sink to transfer snapshots' from Calle Wilund

    Fixes #4246

    Alternative approach/better separation of concern, transport vs. sstable layer. Builds on #4472, but fancier.

    Ensures we transfer and pre-process scylla metadata for streamed
    file blobs first, then properly apply receiving nodes local config
    by using a source and sink layer exported from sstables, which
    handles things like ordering, metadata filtering (on source) as well
    as handling metadata and proper IO paths when writing data on
    receiver node (sink).

    This implementation maintains the statelessness of the current
    design, and the delegated sink side will re-read and re-write the
    metadata for each component processed. This is a little wasteful,
    but the meta is small, and it is less error prone than trying to do
    caching cross-shards etc. The transport is isolated from the
    knowledge.

    This is an alternative/complement to #4436 and #4472, fixing the
    underlying issue. Note that while the layers/API:s here allows easy
    fixing of other fundamental problems in the feature (such as
    destination location etc), these are not included in the PR, to keep
    it as close to the current behaviour as possible.

    Closes scylladb/scylla-enterprise#4646

    * github.com:scylladb/scylla-enterprise: raft_tests: Copy/add a topology test with encryption file streaming: Use sstable source/sink to transfer snapshots sstables: Add source and sink objects + producers for transfering a snapshot sstable::types: Add remove accessor for extension info in metadata

*) The change for error injection in merge commit 966ea5955dd8760:

    File streaming now has "stream_mutation_fragments" error injection points
    so test_table_dropped_during_streaming works with file streaming.

*) doc: document file-based streaming

    This commit adds a description of the file-based streaming feature to the documentation.

    It will be displayed in the docs using the scylladb_include_flag directive after
    https://github.com/scylladb/scylladb/pull/20182 is merged, backported to branch-6.0,
    and, in turn, branch-2024.2.

    Refs https://github.com/scylladb/scylla-ente [...]

2024-12-24 02:27 UTC, scylladb-promoter commented
## Docs Preview :book:
Docs Preview for this pull request is available [here](http://previews.docs.scylladb.com/scylladb/22034)

**Changed Files:**
- [architecture/tablets](http://previews.docs.scylladb.com/scylladb/22034/architecture/tablets)

**Note:** This preview will be available for 30 days and will be automatically deleted after that period. You can manually trigger a new build by committing changes.

2024-12-24 05:50 UTC, scylladb-promoter commented
#### :red_circle: CI State: FAILURE

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14050/)
:x: - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14050/)
**The following new/updated tests ran 100 times for each mode:**
:small_blue_diamond: boost/file_stream_test
:small_blue_diamond: topology_custom/test_tablets_migration
:small_blue_diamond: topology_experimental_raft/test_tablets
:small_blue_diamond: topology_experimental_raft/test_topology_ops_encrypted
#### Failed Tests (2/6732):
- [test_topology_changes.dev.10](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14050/testReport/junit/topology_experimental_raft/test_tablets/test_topology_changes_dev_10) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_topology_changes.dev.10)
- [test_topology_changes.dev.8](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14050/testReport/junit/topology_experimental_raft/test_tablets/test_topology_changes_dev_8) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_topology_changes.dev.8)
#### Build Details:
- Duration: 3 hr 25 min
- Builder: spider4.cloudius-systems.com

2024-12-24 06:20 UTC, asias commented
> #### 🔴 CI State: FAILURE
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14050/) ❌ - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14050/) **The following new/updated tests ran 100 times for each mode:** 🔹 boost/file_stream_test 🔹 topology_custom/test_tablets_migration 🔹 topology_experimental_raft/test_tablets 🔹 topology_experimental_raft/test_topology_ops_encrypted
> 
> #### Failed Tests (2/6732):
> * [test_topology_changes.dev.10](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14050/testReport/junit/topology_experimental_raft/test_tablets/test_topology_changes_dev_10) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_topology_changes.dev.10)
> * [test_topology_changes.dev.8](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14050/testReport/junit/topology_experimental_raft/test_tablets/test_topology_changes_dev_8) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_topology_changes.dev.8)
> 
> #### Build Details:
> * Duration: 3 hr 25 min
> * Builder: spider4.cloudius-systems.com

Known CI issue:
https://github.com/scylladb/scylladb/issues/21218

2024-12-26 10:36 UTC, mykaul commented
@asias - please resolve conflicts.

2024-12-26 23:53 UTC, asias commented
> @asias - please resolve conflicts.

Rebased. The tests test/topology_experimental_raft/test_tablets.py was renamed in master.

2024-12-27 07:25 UTC, scylladb-promoter commented
#### :red_circle: CI State: FAILURE

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14099/)
:x: - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14099/)
**The following new/updated tests ran 100 times for each mode:**
:small_blue_diamond: boost/file_stream_test
:small_blue_diamond: topology_custom/test_tablets2
:small_blue_diamond: topology_custom/test_tablets_migration
:small_blue_diamond: topology_custom/test_topology_ops_encrypted
#### Failed Tests (31/1654):
- [topology_custom.test_topology_ops_encrypted](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14099/testReport/junit/%28root%29/%28empty%29/topology_custom_test_topology_ops_encrypted) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+topology_custom.test_topology_ops_encrypted)
- [topology_custom.test_topology_ops_encrypted](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14099/testReport/junit/%28root%29/%28empty%29/topology_custom_test_topology_ops_encrypted_2) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+topology_custom.test_topology_ops_encrypted)
- [topology_custom.test_topology_ops_encrypted](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14099/testReport/junit/%28root%29/%28empty%29/topology_custom_test_topology_ops_encrypted_3) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+topology_custom.test_topology_ops_encrypted)
- [topology_custom.test_topology_ops_encrypted](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14099/testReport/junit/%28root%29/%28empty%29/topology_custom_test_topology_ops_encrypted_4) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+topology_custom.test_topology_ops_encrypted)
- [topology_custom.test_topology_ops_encrypted](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14099/testReport/junit/%28root%29/%28empty%29/topology_custom_test_topology_ops_encrypted_5) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+topology_custom.test_topology_ops_encrypted)
- [topology_custom.test_topology_ops_encrypted](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14099/testReport/junit/%28root%29/%28empty%29/topology_custom_test_topology_ops_encrypted_6) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+topology_custom.test_topology_ops_encrypted)
- [topology_custom.test_topology_ops_encrypted](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14099/testReport/junit/%28root%29/%28empty%29/topology_custom_test_topology_ops_encrypted_7) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+topology_custom.test_topology_ops_encrypted)
- [topology_custom.test_topology_ops_encrypted](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14099/testReport/junit/%28root%29/%28empty%29/topology_custom_test_topology_ops_encrypted_8) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+topology_custom.test_topology_ops_encrypted)
- [topology_custom.test_topology_ops_encrypted](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14099/testReport/junit/%28root%29/%28empty%29/topology_custom_test_topology_ops_encrypted_9) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+topology_custom.test_topology_ops_encrypted)
- [topology_custom.test_topology_ops_encrypted](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14099/testReport/junit/%28root%29/%28empty%29/topology_custom_test_topology_ops_encrypted_10) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+topology_custom.test_topology_ops_encrypted)
#### Build Details:
- Duration: 7 hr 23 min
- Builder: spider2.cloudius-systems.com

2024-12-27 16:13 UTC, scylladb-promoter commented
#### :red_circle: CI State: FAILURE

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14104/)
:x: - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14104/)
**The following new/updated tests ran 100 times for each mode:**
:small_blue_diamond: boost/file_stream_test
:small_blue_diamond: topology_custom/test_tablets2
:small_blue_diamond: topology_custom/test_tablets_migration
:small_blue_diamond: topology_custom/test_topology_ops_encrypted
#### Failed Tests (1/5049):
- [test_topology_changes.debug.4](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14104/testReport/junit/topology_custom/test_tablets2/test_topology_changes_debug_4) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_topology_changes.debug.4)
#### Build Details:
- Duration: 7 hr 54 min
- Builder: spider8.cloudius-systems.com

2025-01-02 01:45 UTC, asias commented
> #### 🔴 CI State: FAILURE
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14104/) ❌ - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14104/) **The following new/updated tests ran 100 times for each mode:** 🔹 boost/file_stream_test 🔹 topology_custom/test_tablets2 🔹 topology_custom/test_tablets_migration 🔹 topology_custom/test_topology_ops_encrypted
> 
> #### Failed Tests (1/5049):
> * [test_topology_changes.debug.4](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14104/testReport/junit/topology_custom/test_tablets2/test_topology_changes_debug_4) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_topology_changes.debug.4)
> 
> #### Build Details:
> * Duration: 7 hr 54 min
> * Builder: spider8.cloudius-systems.com

Known CI issue:
https://github.com/scylladb/scylladb/issues/21218

2025-01-02 01:48 UTC, asias commented
Changes in ff37b3ac0dcafb1ccffcd520c7425a30c48a9e5a
- rebased

@scylladb/scylla-maint  Ping for merge.

2025-01-02 03:31 UTC, scylladb-promoter commented
#### :red_circle: CI State: FAILURE

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14162/)
:x: - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14162/)
**The following new/updated tests ran 100 times for each mode:**
:small_blue_diamond: boost/file_stream_test
:small_blue_diamond: topology_custom/test_tablets2
:small_blue_diamond: topology_custom/test_tablets_migration
:small_blue_diamond: topology_custom/test_topology_ops_encrypted
#### Failed Tests (1/1683):
- [test_file_stream](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14162/testReport/junit/boost/file_stream_test/test_file_stream) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_file_stream)
#### Build Details:
- Duration: 1 hr 43 min
- Builder: spider4.cloudius-systems.com

2025-01-02 03:49 UTC, asias commented
> #### 🔴 CI State: FAILURE
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14162/) ❌ - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14162/) **The following new/updated tests ran 100 times for each mode:** 🔹 boost/file_stream_test 🔹 topology_custom/test_tablets2 🔹 topology_custom/test_tablets_migration 🔹 topology_custom/test_topology_ops_encrypted
> 
> #### Failed Tests (1/1683):
> * [test_file_stream](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14162/testReport/junit/boost/file_stream_test/test_file_stream) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_file_stream)

Not sure why the rpc stream was closed in 1 out 30 debug build runs. It passed in all other runs.  
https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14162/consoleFull#-9954733982d64d3cc-9cf1-4f8e-9ae7-050ec58d788c

```
11:24:53  INFO  2025-01-02 04:26:28,280 [shard 0:goss] schema_tables - Creating keyspace ks
11:24:53  INFO  2025-01-02 04:26:28,310 [shard 0:goss] migration_manager - Gossiping my schema version f89d07ac-c8b0-11ef-a62a-f08a519b6fe9
11:24:53  INFO  2025-01-02 04:26:28,310 [shard 0:goss] schema_tables - Schema version changed to f89d07ac-c8b0-11ef-a62a-f08a519b6fe9
11:24:53  WARN  2025-01-02 04:26:28,315 [shard 0:main] create_keyspace - Using Replication Factor replication_factor=1 lower than the minimum_replication_factor_warn_threshold=3 is not recommended.
11:24:53  INFO  2025-01-02 04:26:28,356 [shard 0:comp] compaction - [Compact system.raft f8aab0f0-c8b0-11ef-9cba-61fca8fa1d81] Compacting [/scylladir/testlog/x86_64/debug/scylla-e24b90a1-0634-4fd9-85c6-d5650fc22546/system/raft-3e17774c57f539939625327cbafbf5bb/me-3gml_06s4_1ofxc2dsvsrbfrxu2p-big-Data.db:level=0:origin=memtable,/scylladir/testlog/x86_64/debug/scylla-e24b90a1-0634-4fd9-85c6-d5650fc22546/system/raft-3e17774c57f539939625327cbafbf5bb/me-3gml_06s4_1fnkg2dsvsrbfrxu2p-big-Data.db:level=0:origin=memtable]
11:24:53  INFO  2025-01-02 04:26:28,399 [shard 0:comp] sstable - Rebuilding bloom filter /scylladir/testlog/x86_64/debug/scylla-e24b90a1-0634-4fd9-85c6-d5650fc22546/system/raft-3e17774c57f539939625327cbafbf5bb/me-3gml_06s4_29g3k2dsvsrbfrxu2p-big-Filter.db: resizing bitset from 328 bytes to 8 bytes. sstable origin: compaction
11:24:53  INFO  2025-01-02 04:26:28,439 [shard 0:comp] compaction - [Compact system.raft f8aab0f0-c8b0-11ef-9cba-61fca8fa1d81] Compacted 2 sstables to [/scylladir/testlog/x86_64/debug/scylla-e24b90a1-0634-4fd9-85c6-d5650fc22546/system/raft-3e17774c57f539939625327cbafbf5bb/me-3gml_06s4_29g3k2dsvsrbfrxu2p-big-Data.db:level=0]. 73kB to 67kB (~91% of original) in 78ms = 936kB/s. ~256 total partitions merged to 1.
11:24:53  INFO  2025-01-02 04:26:29,783 [shard 0:main] group0_tombstone_gc_handler - Setting reconcile time to   1735784787 (min id=f89d07ac-c8b0-11ef-a62a-f08a519b6fe9)
11:24:53  WARN  2025-01-02 04:26:42,819 [shard 0:stat] stream_blob - fstream[8cc69d37-1052-4329-a9b1-0ea802ca9fd5] Master failed sending file=/tmp/fileuhQxc3 to targets=[cb3fd193-0d2f-46e2-85c2-bad0043fc01e:0] send_size=9437604 bw=1MB/s error=seastar::rpc::stream_closed (rpc stream was closed by peer)
11:24:53  WARN  2025-01-02 04:26:42,819 [shard 0:stat] stream_blob - fstream[8cc69d37-1052-4329-a9b1-0ea802ca9fd5] Master failed to drain rpc stream source: seastar::rpc::stream_closed (rpc stream was closed by peer)
11:24:53  WARN  2025-01-02 04:26:42,819 [shard 0:stat] stream_blob - fstream[8cc69d37-1052-4329-a9b1-0ea802ca9fd5] Master failed sending files_nr=10 files=[/tmp/file5l6oRn, /tmp/fileBrF42g, /tmp/fileADEhQu, /tmp/fileCuZOWU, /tmp/filejk66cN, /tmp/filenTEcSF, /tmp/fileNgd6H3, /tmp/fileuhQxc3, /tmp/fileRYOeQ8, /tmp/filedz2ydC] targets=[cb3fd193-0d2f-46e2-85c2-bad0043fc01e:0] send_size=31460735 bw=2MB/s error=seastar::rpc::stream_closed (rpc stream was closed by peer)
11:24:53  WARN  2025-01-02 04:26:42,819 [shard 0:stat] testlog - do_test_file_stream[8cc69d37-1052-4329-a9b1-0ea802ca9fd5] status=fail error=seastar::rpc::stream_closed (rpc stream was closed by peer) retry=0
11:24:53  INFO  2025-01-02 04:26:42,819 [shard 0:stat] testlog - Retrying send
11:24:53  INFO  2025-01-02 04:26:42,820 [shard 0:main] batchlog_manager - Asked to stop
11:24:53  INFO  2025-01-02 04:26:42,820 [shard 0:main] batchlog_manager - Asked to drain
11:24:53  INFO  2025-01-02 04:26:42,820 [shard 0:main] batchlog_manager - Drained
11:24:53  INFO  2025-01-02 04:26:42,820 [shard 0:main] batchlog_manager - Stopped
11:24:53  INFO  2025-01-02 04:26:42,820 [shard 1:main] batchlog_manager - Asked to stop
11:24:53  INFO  2025-01-02 04:26:42,820 [shard 1:main] batchlog_manager - Asked to drain
11:24:53  INFO  2025-01-02 04:26:42,820 [shard 1:main] batchlog_manager - Drained
11:24:53  INFO  2025-01-02 04:26:42,820 [shard 1:main] batchlog_manager - Stopped
11:24:53  INFO  2025-01-02 04:26:42,821 [shard 0:main] raft_topology - raft_state_monitor_fiber aborted with seastar::abort_requested_exception (abort requested)
11:24:53  INFO  2025-01-02 04:26:42,821 [shard 0:main] raft_topology - cleanup fiber aborted
11:24:53  INFO  2025-01-02 04:26:42,821 [shard 0:main] view - Stopping view builder
11:24:53  INFO  2025-01-02 04:26:42,821 [shard 0:main] view - Draining view builder
11:24:53  INFO  2025-01-02 04:26:42,822 [shard 1:main] view - Stopping view builder
11:24:53  INFO  2025-01-02 04:26:42,822 [shard 1:main] view - Draining view builder
```

2025-01-02 08:01 UTC, scylladb-promoter commented
#### :red_circle: CI State: FAILURE

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14165/)
:x: - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14165/)
**The following new/updated tests ran 100 times for each mode:**
:small_blue_diamond: boost/file_stream_test
:small_blue_diamond: topology_custom/test_tablets2
:small_blue_diamond: topology_custom/test_tablets_migration
:small_blue_diamond: topology_custom/test_topology_ops_encrypted
#### Failed Tests (1/6732):
- [test_topology_changes.dev.4](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14165/testReport/junit/topology_custom/test_tablets2/test_topology_changes_dev_4) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_topology_changes.dev.4)
#### Build Details:
- Duration: 4 hr 16 min
- Builder: spider4.cloudius-systems.com

2025-01-03 14:37 UTC, kbr-scylla commented
> Known CI issue:
https://github.com/scylladb/scylladb/issues/21218

You're most likely hitting bug https://github.com/scylladb/scylla-enterprise/issues/4894 inside `sstable_stream_sink_impl` (introduced by this PR) which was fixed by @bhalevy in https://github.com/scylladb/scylla-enterprise/commit/39b5a9cc4bdbae1be94e4d25fba1daf2a0574539

2025-01-03 14:38 UTC, kbr-scylla commented
The port should probably include all fixed that came later

2025-01-03 14:41 UTC, kbr-scylla commented
It's a general problem with migrations, we need to be very careful. Otherwise we'll be porting bugs that were already fixed on the `enterprise` branch...

2025-01-04 00:43 UTC, asias commented
> The port should probably include all fixed that came later

Of course we should, the one https://github.com/scylladb/scylla-enterprise/commit/39b5a9cc4bdbae1be94e4d25fba1daf2a0574539 is missed.

2025-01-04 00:43 UTC, asias commented
Changes in 83f8b8019e3c51b7da476ff9ace943692f287fe7
- Added https://github.com/scylladb/scylla-enterprise/commit/39b5a9cc4bdbae1be94e4d25fba1daf2a0574539

2025-01-04 14:34 UTC, scylladb-promoter commented
#### :red_circle: CI State: FAILURE

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14217/)
:white_check_mark: - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14217/)
**The following new/updated tests ran 100 times for each mode:**
:small_blue_diamond: boost/file_stream_test
:small_blue_diamond: topology_custom/test_tablets2
:small_blue_diamond: topology_custom/test_tablets_migration
:small_blue_diamond: topology_custom/test_topology_ops_encrypted
:x: - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/2607/)
:white_check_mark: - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/13733/)
:white_check_mark: - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/5720/)
:white_check_mark: - [Docker Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-docker/980/)
:white_check_mark: - [Offline-installer Artifact Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-offline-installer/384/)
:x: - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14217/)
#### Failed Tests (9/52432):
- [test_truncate_while_migration.debug.1](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14217/testReport/junit/topology_custom/test_truncate_with_tablets/Tests___Unit_Tests___test_truncate_while_migration_debug_1) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_truncate_while_migration.debug.1)
- [test_truncate_while_migration.debug.2](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14217/testReport/junit/topology_custom/test_truncate_with_tablets/Tests___Unit_Tests___test_truncate_while_migration_debug_2) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_truncate_while_migration.debug.2)
- [test_truncate_while_migration.debug.3](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14217/testReport/junit/topology_custom/test_truncate_with_tablets/Tests___Unit_Tests___test_truncate_while_migration_debug_3) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_truncate_while_migration.debug.3)
- [test_truncate_while_migration.dev.1](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14217/testReport/junit/topology_custom/test_truncate_with_tablets/Tests___Unit_Tests___test_truncate_while_migration_dev_1) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_truncate_while_migration.dev.1)
- [test_truncate_while_migration.dev.2](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14217/testReport/junit/topology_custom/test_truncate_with_tablets/Tests___Unit_Tests___test_truncate_while_migration_dev_2) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_truncate_while_migration.dev.2)
- [test_truncate_while_migration.dev.3](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14217/testReport/junit/topology_custom/test_truncate_with_tablets/Tests___Unit_Tests___test_truncate_while_migration_dev_3) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_truncate_while_migration.dev.3)
- [test_tablets_data_is_segregated_after_bootstrap](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14217/testReport/junit/compaction_additional_test/TestTimeWindowDataSegregation/Tests___dtest_with_tablets___test_tablets_data_is_segregated_after_bootstrap) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_tablets_data_is_segregated_after_bootstrap)
- [test_streaming_sstables_with_several_timewindows](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14217/testReport/junit/compaction_additional_test/TestTimeWindowDataSegregation/Tests___dtest_with_tablets___test_streaming_sstables_with_several_timewindows) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_streaming_sstables_with_several_timewindows)
- [test_describering](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14217/testReport/junit/nodetool_additional_test/TestNodetool/Tests___dtest_with_tablets___test_describering) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_describering)
#### Build Details:
- Duration: 13 hr
- Builder: spider4.cloudius-systems.com

2025-01-05 18:09 UTC, bhalevy commented
@asias please investigate CI failures

2025-01-05 20:56 UTC, avikivity commented
Please change the patch subject to be a normal feature introduction, the changelog can mention it's a port from enterprise.

2025-01-05 20:57 UTC, avikivity commented
> It's a general problem with migrations, we need to be very careful. Otherwise we'll be porting bugs that were already fixed on the `enterprise` branch...

The migration ends when `git diff` says there are no differences, so the risk is low.

Still, it's better to generate the patch using diff, since some changes came via merges, not via patches posted to enterprise.

2025-01-06 03:01 UTC, asias commented
> #### 🔴 CI State: FAILURE
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14217/) ✅ - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14217/) **The following new/updated tests ran 100 times for each mode:** 🔹 boost/file_stream_test 🔹 topology_custom/test_tablets2 🔹 topology_custom/test_tablets_migration 🔹 topology_custom/test_topology_ops_encrypted ❌ - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/2607/) ✅ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/13733/) ✅ - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/5720/) ✅ - [Docker Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-docker/980/) ✅ - [Offline-installer Artifact Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-offline-installer/384/) ❌ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14217/)
> 
> #### Failed Tests (9/52432):
> * [test_truncate_while_migration.debug.1](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14217/testReport/junit/topology_custom/test_truncate_with_tablets/Tests___Unit_Tests___test_truncate_while_migration_debug_1) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_truncate_while_migration.debug.1)
> * [test_truncate_while_migration.debug.2](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14217/testReport/junit/topology_custom/test_truncate_with_tablets/Tests___Unit_Tests___test_truncate_while_migration_debug_2) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_truncate_while_migration.debug.2)
> * [test_truncate_while_migration.debug.3](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14217/testReport/junit/topology_custom/test_truncate_with_tablets/Tests___Unit_Tests___test_truncate_while_migration_debug_3) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_truncate_while_migration.debug.3)
> * [test_truncate_while_migration.dev.1](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14217/testReport/junit/topology_custom/test_truncate_with_tablets/Tests___Unit_Tests___test_truncate_while_migration_dev_1) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_truncate_while_migration.dev.1)
> * [test_truncate_while_migration.dev.2](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14217/testReport/junit/topology_custom/test_truncate_with_tablets/Tests___Unit_Tests___test_truncate_while_migration_dev_2) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_truncate_while_migration.dev.2)
> * [test_truncate_while_migration.dev.3](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14217/testReport/junit/topology_custom/test_truncate_with_tablets/Tests___Unit_Tests___test_truncate_while_migration_dev_3) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_truncate_while_migration.dev.3)
> * [test_tablets_data_is_segregated_after_bootstrap](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14217/testReport/junit/compaction_additional_test/TestTimeWindowDataSegregation/Tests___dtest_with_tablets___test_tablets_data_is_segregated_after_bootstrap) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_tablets_data_is_segregated_after_bootstrap)
> * [test_streaming_sstables_with_several_timewindows](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14217/testReport/junit/compaction_additional_test/TestTimeWindowDataSegregation/Tests___dtest_with_tablets___test_streaming_sstables_with_several_timewindows) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_streaming_sstables_with_several_timewindows)
> * [test_describering](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14217/testReport/junit/nodetool_additional_test/TestNodetool/Tests___dtest_with_tablets___test_describering) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_describering)
> 
> #### Build Details:
> * Duration: 13 hr
> * Builder: spider4.cloudius-systems.com

We need to adjust the dtest tests for above CI issues. 

I created: https://github.com/scylladb/scylla-dtest/pull/5453

In order to make https://github.com/scylladb/scylla-dtest/pull/5453 work without file stream PR,  I created

https://github.com/scylladb/scylladb/pull/22176.


So we need to merge https://github.com/scylladb/scylladb/pull/22176 into scylla.git, then merge https://github.com/scylladb/scylla-dtest/pull/5453 to dtest, then merge this PR https://github.com/scylladb/scylladb/pull/22034.

What a dependence!

2025-01-06 03:04 UTC, asias commented
> Please change the patch subject to be a normal feature introduction, the changelog can mention it's a port from enterprise.

OK. Done.

2025-01-06 09:25 UTC, scylladb-promoter commented
#### :red_circle: CI State: FAILURE

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14227/)
:x: - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14227/)
**The following new/updated tests ran 100 times for each mode:**
:small_blue_diamond: boost/file_stream_test
:small_blue_diamond: topology_custom/test_tablets2
:small_blue_diamond: topology_custom/test_tablets_migration
:small_blue_diamond: topology_custom/test_topology_ops_encrypted
#### Failed Tests (1/10098):
- [test_file_stream](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14227/testReport/junit/boost/file_stream_test/test_file_stream) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_file_stream)
#### Build Details:
- Duration: 6 hr 20 min
- Builder: spider4.cloudius-systems.com

2025-01-07 02:32 UTC, asias commented
The dtest change is merged.  No dtest dependence is needed.   Let's see if the CI is happy now. 

Changes in  a624921:
- Reduced file stream test size for debug build

2025-01-07 02:34 UTC, asias commented
> #### 🔴 CI State: FAILURE
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14227/) ❌ - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14227/) **The following new/updated tests ran 100 times for each mode:** 🔹 boost/file_stream_test 🔹 topology_custom/test_tablets2 🔹 topology_custom/test_tablets_migration 🔹 topology_custom/test_topology_ops_encrypted
> 
> #### Failed Tests (1/10098):
> * [test_file_stream](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14227/testReport/junit/boost/file_stream_test/test_file_stream) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_file_stream)

Same as https://github.com/scylladb/scylladb/pull/22034#issuecomment-2567261663,  the debug mode took 600s+ to finish a single run. I reduced the file stream size in debug mode.

2025-01-07 13:49 UTC, scylladb-promoter commented
#### :red_circle: CI State: FAILURE

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14246/)
:white_check_mark: - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14246/)
**The following new/updated tests ran 100 times for each mode:**
:small_blue_diamond: boost/file_stream_test
:small_blue_diamond: topology_custom/test_tablets2
:small_blue_diamond: topology_custom/test_tablets_migration
:small_blue_diamond: topology_custom/test_topology_ops_encrypted
:white_check_mark: - [Docker Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-docker/1012/)
:white_check_mark: - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/2644/)
:white_check_mark: - [Offline-installer Artifact Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-offline-installer/416/)
:x: - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/13771/)
:white_check_mark: - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/5758/)
:x: - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14246/)
#### Failed Tests (3/53667):
- [test_simple_removenode_4](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14246/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/Tests___dtest___test_simple_removenode_4) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_simple_removenode_4)
- [test_simple_removenode_4](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14246/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/Tests___dtest___test_simple_removenode_4_2) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_simple_removenode_4)
- [[empty]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14246/testReport/junit/boost.database_test.test_database_with_data_in_sstables_is_a_mutation_source_reverse_fragments_monotonic_cg1.2.xunit/xml/Tests___Unit_Tests____empty_) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+[empty])
#### Build Details:
- Duration: 14 hr
- Builder: spider5.cloudius-systems.com

2025-01-07 13:57 UTC, asias commented
> #### 🔴 CI State: FAILURE
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14246/) ✅ - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14246/) **The following new/updated tests ran 100 times for each mode:** 🔹 boost/file_stream_test 🔹 topology_custom/test_tablets2 🔹 topology_custom/test_tablets_migration 🔹 topology_custom/test_topology_ops_encrypted ✅ - [Docker Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-docker/1012/) ✅ - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/2644/) ✅ - [Offline-installer Artifact Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-offline-installer/416/) ❌ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/13771/) ✅ - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/5758/) ❌ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14246/)
> 
> #### Failed Tests (3/53667):
> * [test_simple_removenode_4](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14246/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/Tests___dtest___test_simple_removenode_4) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_simple_removenode_4)
> * [test_simple_removenode_4](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14246/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/Tests___dtest___test_simple_removenode_4_2) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_simple_removenode_4)
> * [[empty]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14246/testReport/junit/boost.database_test.test_database_with_data_in_sstables_is_a_mutation_source_reverse_fragments_monotonic_cg1.2.xunit/xml/Tests___Unit_Tests____empty_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+%5Bempty%5D)
> 
> #### Build Details:
> * Duration: 14 hr
> * Builder: spider5.cloudius-systems.com

Existing CI issue: https://github.com/scylladb/scylladb/issues/20814

2025-01-08 07:00 UTC, denesb commented
database_test failed because of:
```
15:36:23  ERROR 2025-01-07 11:48:51,535 [shard 0:main] table - Memtable flush failed due to: storage_io_error (Storage I/O error: 12: Cannot allocate memory). Aborting, at 0x32f86d5 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x469a357 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x4699fa1 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x469bb70 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x469e70f 0xa52236c 0x35c0a86 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x3738b90 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x3744e9d /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x374a33d /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x3748349 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x32999b4 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x329634a /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar_testing.so+0xa3dda /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar_testing.so+0xa36e0 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar_testing.so+0xa35d0 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar_testing.so+0xa303c /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x34f8a58 0x334c198 /lib64/libc.so.6+0x97c16 /lib64/libc.so.6+0x11bb0b
15:36:23     --------
15:36:23     seastar::internal::coroutine_traits_base<void>::promise_type
15:36:23     --------
15:36:23     seastar::internal::coroutine_traits_base<void>::promise_type
15:36:23     --------
15:36:23     seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>, seastar::future<void>::then_wrapped_nrvo<seastar::future<void>, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)> >(seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
15:36:23     --------
15:36:23     seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>, seastar::future<void>::then_wrapped_nrvo<seastar::future<void>, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)> >(seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
15:36:23  Aborting on shard 0, in scheduling group main.
15:36:23  Backtrace:
15:36:23    0x32f86d5
15:36:23    /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x38d3197
15:36:23    /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x38d2e25
15:36:23    /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x371045b
15:36:23    /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x374bab5
15:36:23    /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x3831719
15:36:23    /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x3831a47
15:36:23    /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x383186e
15:36:23    /lib64/libc.so.6+0x40d0f
15:36:23    /lib64/libc.so.6+0x99bd3
15:36:23    /lib64/libc.so.6+0x40c5d
15:36:23    /lib64/libc.so.6+0x28901
15:36:23    0xa5223db
15:36:23    0x35c0a86
15:36:23    /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x3738b90
15:36:23    /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x3744e9d
15:36:23    /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x374a33d
15:36:23    /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x3748349
15:36:23    /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x32999b4
15:36:23    /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x329634a
15:36:23    /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar_testing.so+0xa3dda
15:36:23    /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar_testing.so+0xa36e0
15:36:23    /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar_testing.so+0xa35d0
15:36:23    /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar_testing.so+0xa303c
15:36:23    /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x34f8a58
15:36:23    0x334c198
15:36:23    /lib64/libc.so.6+0x97c16
15:36:23    /lib64/libc.so.6+0x11bb0b
15:36:23  === TEST.PY SUMMARY START ===
15:36:23  Test exited with code -6
```

2025-01-08 07:15 UTC, asias commented
> database_test failed because of:
> 
> ```
> 15:36:23  ERROR 2025-01-07 11:48:51,535 [shard 0:main] table - Memtable flush failed due to: storage_io_error (Storage I/O error: 12: Cannot allocate memory). Aborting, at 0x32f86d5 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x469a357 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x4699fa1 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x469bb70 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x469e70f 0xa52236c 0x35c0a86 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x3738b90 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x3744e9d /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x374a33d /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x3748349 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x32999b4 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x329634a /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar_testing.so+0xa3dda /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar_testing.so+0xa36e0 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar_testing.so+0xa35d0 /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar_testing.so+0xa303c /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x34f8a58 0x334c198 /lib64/libc.so.6+0x97c16 /lib64/libc.so.6+0x11bb0b
> 15:36:23     --------
> 15:36:23     seastar::internal::coroutine_traits_base<void>::promise_type
> 15:36:23     --------
> 15:36:23     seastar::internal::coroutine_traits_base<void>::promise_type
> 15:36:23     --------
> 15:36:23     seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>, seastar::future<void>::then_wrapped_nrvo<seastar::future<void>, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)> >(seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
> 15:36:23     --------
> 15:36:23     seastar::continuation<seastar::internal::promise_base_with_type<void>, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>, seastar::future<void>::then_wrapped_nrvo<seastar::future<void>, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)> >(seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, seastar::noncopyable_function<seastar::future<void> (seastar::future<void>&&)>&, seastar::future_state<seastar::internal::monostate>&&)#1}, void>
> 15:36:23  Aborting on shard 0, in scheduling group main.
> 15:36:23  Backtrace:
> 15:36:23    0x32f86d5
> 15:36:23    /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x38d3197
> 15:36:23    /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x38d2e25
> 15:36:23    /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x371045b
> 15:36:23    /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x374bab5
> 15:36:23    /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x3831719
> 15:36:23    /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x3831a47
> 15:36:23    /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x383186e
> 15:36:23    /lib64/libc.so.6+0x40d0f
> 15:36:23    /lib64/libc.so.6+0x99bd3
> 15:36:23    /lib64/libc.so.6+0x40c5d
> 15:36:23    /lib64/libc.so.6+0x28901
> 15:36:23    0xa5223db
> 15:36:23    0x35c0a86
> 15:36:23    /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x3738b90
> 15:36:23    /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x3744e9d
> 15:36:23    /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x374a33d
> 15:36:23    /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x3748349
> 15:36:23    /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x32999b4
> 15:36:23    /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x329634a
> 15:36:23    /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar_testing.so+0xa3dda
> 15:36:23    /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar_testing.so+0xa36e0
> 15:36:23    /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar_testing.so+0xa35d0
> 15:36:23    /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar_testing.so+0xa303c
> 15:36:23    /jenkins/workspace/scylla-master/scylla-ci/scylla/build/Debug/seastar/libseastar.so+0x34f8a58
> 15:36:23    0x334c198
> 15:36:23    /lib64/libc.so.6+0x97c16
> 15:36:23    /lib64/libc.so.6+0x11bb0b
> 15:36:23  === TEST.PY SUMMARY START ===
> 15:36:23  Test exited with code -6
> ```

Know issue: https://github.com/scylladb/scylladb/issues/21968

2025-01-08 12:32 UTC, scylladb-promoter commented
#### :red_circle: CI State: FAILURE

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14290/)
:x: - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14290/)
**The following new/updated tests ran 100 times for each mode:**
:small_blue_diamond: boost/file_stream_test
:small_blue_diamond: topology_custom/test_tablets2
:small_blue_diamond: topology_custom/test_tablets_migration
:small_blue_diamond: topology_custom/test_topology_ops_encrypted
#### Failed Tests (1/8415):
- [test_file_stream](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14290/testReport/junit/boost/file_stream_test/test_file_stream) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_file_stream)
#### Build Details:
- Duration: 4 hr 59 min
- Builder: spider5.cloudius-systems.com

2025-01-08 12:45 UTC, denesb commented
> [test_file_stream](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14290/testReport/junit/boost/file_stream_test/test_file_stream) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_file_stream)

Failure seems related, @asias please have a look.

2025-01-08 13:51 UTC, asias commented
> > [test_file_stream](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14290/testReport/junit/boost/file_stream_test/test_file_stream) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_file_stream)
> 
> Failure seems related, @asias please have a look.

Same as here:

https://github.com/scylladb/scylladb/pull/22034#issuecomment-2567261663

```
[2025-01-08T12:18:44.481Z] WARN  2025-01-08 13:28:23,539 [shard 0:sl:d] stream_blob - fstream[02a3380d-23ea-44a0-a4f2-84f132cfa176] Master failed sending file=/tmp/file6GdTYQ to targets=[c6acd455-2b16-4093-97c1-2b66386b84cd:0] send_size=4096 bw=390kB/s error=seastar::rpc::stream_closed (rpc stream was closed by peer)
[2025-01-08T12:18:44.482Z] WARN  2025-01-08 13:28:23,540 [shard 0:sl:d] stream_blob - fstream[02a3380d-23ea-44a0-a4f2-84f132cfa176] Master failed to drain rpc stream source: seastar::rpc::stream_closed (rpc stream was closed by peer)
[2025-01-08T12:18:44.482Z] WARN  2025-01-08 13:28:23,540 [shard 0:sl:d] stream_blob - fstream[02a3380d-23ea-44a0-a4f2-84f132cfa176] Master failed sending files_nr=10 files=[/tmp/filelC9ICr, /tmp/filefsDBMa, /tmp/file6GdTYQ, /tmp/fileuSqgvd, /tmp/fileen0vdI, /tmp/fileW1PB56, /tmp/fileMl6d3l, /tmp/filen5XCPt, /tmp/filefS3nYT, /tmp/fileBQclem] targets=[c6acd455-2b16-4093-97c1-2b66386b84cd:0] send_size=14336 bw=228kB/s error=seastar::rpc::stream_closed (rpc stream was closed by peer) 
[2025-01-08T12:18:44.483Z] WARN  2025-01-08 13:28:23,541 [shard 0:sl:d] testlog - do_test_file_stream[02a3380d-23ea-44a0-a4f2-84f132cfa176] status=fail error=seastar::rpc::stream_closed (rpc stream was closed by peer) retry=0
```

The rpc stream sender got rpc stream closed error while there was no error reported on receiver side. I suspect there is a rpc stream bug somewhere. This happens only in debug mode. I never reproduced this locally.

2025-01-08 14:01 UTC, denesb commented
> > > [test_file_stream](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14290/testReport/junit/boost/file_stream_test/test_file_stream) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_file_stream)
> > 
> > 
> > Failure seems related, @asias please have a look.
> 
> Same as here:
> 
> [#22034 (comment)](https://github.com/scylladb/scylladb/pull/22034#issuecomment-2567261663)
> 
> ```
> [2025-01-08T12:18:44.481Z] WARN  2025-01-08 13:28:23,539 [shard 0:sl:d] stream_blob - fstream[02a3380d-23ea-44a0-a4f2-84f132cfa176] Master failed sending file=/tmp/file6GdTYQ to targets=[c6acd455-2b16-4093-97c1-2b66386b84cd:0] send_size=4096 bw=390kB/s error=seastar::rpc::stream_closed (rpc stream was closed by peer)
> [2025-01-08T12:18:44.482Z] WARN  2025-01-08 13:28:23,540 [shard 0:sl:d] stream_blob - fstream[02a3380d-23ea-44a0-a4f2-84f132cfa176] Master failed to drain rpc stream source: seastar::rpc::stream_closed (rpc stream was closed by peer)
> [2025-01-08T12:18:44.482Z] WARN  2025-01-08 13:28:23,540 [shard 0:sl:d] stream_blob - fstream[02a3380d-23ea-44a0-a4f2-84f132cfa176] Master failed sending files_nr=10 files=[/tmp/filelC9ICr, /tmp/filefsDBMa, /tmp/file6GdTYQ, /tmp/fileuSqgvd, /tmp/fileen0vdI, /tmp/fileW1PB56, /tmp/fileMl6d3l, /tmp/filen5XCPt, /tmp/filefS3nYT, /tmp/fileBQclem] targets=[c6acd455-2b16-4093-97c1-2b66386b84cd:0] send_size=14336 bw=228kB/s error=seastar::rpc::stream_closed (rpc stream was closed by peer) 
> [2025-01-08T12:18:44.483Z] WARN  2025-01-08 13:28:23,541 [shard 0:sl:d] testlog - do_test_file_stream[02a3380d-23ea-44a0-a4f2-84f132cfa176] status=fail error=seastar::rpc::stream_closed (rpc stream was closed by peer) retry=0
> ```
> 
> The rpc stream sender got rpc stream closed error while there was no error reported on receiver side. I suspect there is a rpc stream bug somewhere. This happens only in debug mode. I never reproduced this locally.

This means we will have a new flaky test if we merge this as-is. We need to do something to make this test more resilient. Did this never fail in enterprise?

2025-01-08 16:44 UTC, kbr-scylla commented
> We need to do something to make this test more resilient. 

Shouldn't the rpc stream bug get fixed instead?

2025-01-08 16:51 UTC, kbr-scylla commented
The error looks very similar to https://github.com/scylladb/scylla-enterprise/issues/3748
which according to @asias was fixed by
```
commit 28217e1b3b0d336644c55ba088bf537a66a3901f
Author: Asias He <asias@scylladb.com>
Date:   Wed Dec 20 09:24:21 2023 +0800

    streaming: Use new take_storage_snapshot interface
    
    The new take_storage_snapshot returns a file object instead of a file
    name. This allows the file stream sender to read from the file even if
    the file is deleted by compaction.
    
    Closes scylladb/scylla-enterprise#3728
```

2025-01-08 16:53 UTC, kbr-scylla commented
Or maybe it's https://github.com/scylladb/scylla-enterprise/issues/4295 which was opened later, but they look very similar; so maybe scylladb/scylla-enterprise@28217e1b3b0d336644c55ba088bf537a66a3901f didn't fully fix it after all

2025-01-08 17:15 UTC, scylladb-promoter commented
#### :red_circle: CI State: FAILURE

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14311/)
:x: - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14311/)
**The following new/updated tests ran 100 times for each mode:**
:small_blue_diamond: boost/file_stream_test
:small_blue_diamond: topology_custom/test_tablets2
:small_blue_diamond: topology_custom/test_tablets_migration
:small_blue_diamond: topology_custom/test_topology_ops_encrypted
#### Failed Tests (1/5049):
- [test_file_stream](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14311/testReport/junit/boost/file_stream_test/test_file_stream) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_file_stream)
#### Build Details:
- Duration: 3 hr 14 min
- Builder: spider7.cloudius-systems.com

2025-01-09 02:53 UTC, asias commented
I managed to reproduce and figured out what was going on. 

It turns out indeed there is a rpc stream bug.

- rx side:

```
while (!stop) {
    auto opt = source();
    if (opt) {
        break;
    }
    process(opt);
}
```

- tx side
            
```     
while (!done) {                     
    sink(data);
}
sink.close();
```     
 
- tx side finishes sending all the data
- tx side close the sink
- tx side calls source() to get all the data tx sends
- tx side calls source() and gets seastar::rpc::stream_closed before it gets an
  empty opt which indicates there is no more data. (I verifed this happened in
  practice in the test)

This makes rx side think there is a seastar::rpc::stream_closed error incorrectly.

Instead source() should always return an empty opt to indicate there is no more data.

This bug happens only in debug build.

I added code in this PR to ignore the seastar::rpc::stream_closed when the last message is received as a workaround before we fix the rpc stream bug.

After the fix, I could not reproduce the test failure anymore with thousands of runs.

I created seastar bug here: https://github.com/scylladb/seastar/issues/2612

We see the same bug in https://github.com/scylladb/scylla-enterprise/issues/4295.

2025-01-09 04:40 UTC, denesb commented
> > We need to do something to make this test more resilient.
> 
> Shouldn't the rpc stream bug get fixed instead?

Yes, that is what I wanted to say: either fix the bug, or if there is no bug/cannot be fixed, make the test resilient instead.

2025-01-09 08:01 UTC, denesb commented
> I created seastar bug here: [scylladb/seastar#2612](https://github.com/scylladb/seastar/issues/2612)

@asias are you working on a fix for this? Or do you need help from someone?

2025-01-09 09:08 UTC, asias commented
The CI server looks problematic.

Multiple runs failed with the same error. 

```
General pipeline failure

jenkins pipeline failure: Error when executing always post condition:

groovy.lang.MissingPropertyException: No such property: specificTestsList for class: WorkflowScript


[Indication 1](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14319/consoleFull#84773417068d9349a-7ad4-4441-bafe-2346e30da4bd)
```

2025-01-09 13:21 UTC, gleb-cloudius commented
> I managed to reproduce and figured out what was going on.
> 

@asias how can I reproduce locally? I  see a lot of different failures here and not all of then in debug mode. So which test exactly should I try in debug mode to reproduce?

2025-01-09 13:27 UTC, asias commented
> > I managed to reproduce and figured out what was going on.
> 
> @asias how can I reproduce locally? I see a lot of different failures here and not all of then in debug mode. So which test exactly should I try in debug mode to reproduce?

./test.py -s --repeat 500 --mode debug -v  boost/file_stream_test

Add this in the current PR 8768cf5822b6093bec2065c009632f82012406a5
```
--- a/streaming/stream_blob.cc
+++ b/streaming/stream_blob.cc
@@ -210,6 +210,7 @@ future<> stream_blob_handler(replica::database& db,
                 // is the last message from peer, it does not matter if the
                 // source() is closed or not.
                 if (got_end_of_stream) {
+                    // assert here
                     break;
                 } else {
                     throw;
@@ -519,6 +520,7 @@ tablet_stream_files(netw::messaging_service& ms, std::list<stream_blob_info> sou
                             // which is the last message from peer, it does not
                             // matter if the source() is closed or not.
                             if (got_cmd_ok) {
+                                // assert here
                                 break;
                             } else {
                                 throw;
```

2025-01-09 13:33 UTC, asias commented
> > > I managed to reproduce and figured out what was going on.
> > 
> > 
> > @asias how can I reproduce locally? I see a lot of different failures here and not all of then in debug mode. So which test exactly should I try in debug mode to reproduce?
> 
> ./test.py -s --repeat 500 --mode debug -v boost/file_stream_test
> 
> Add this in the current PR [8768cf5](https://github.com/scylladb/scylladb/commit/8768cf5822b6093bec2065c009632f82012406a5)
> 
> ```
> --- a/streaming/stream_blob.cc
> +++ b/streaming/stream_blob.cc
> @@ -210,6 +210,7 @@ future<> stream_blob_handler(replica::database& db,
>                  // is the last message from peer, it does not matter if the
>                  // source() is closed or not.
>                  if (got_end_of_stream) {
> +                    // assert here
>                      break;
>                  } else {
>                      throw;
> @@ -519,6 +520,7 @@ tablet_stream_files(netw::messaging_service& ms, std::list<stream_blob_info> sou
>                              // which is the last message from peer, it does not
>                              // matter if the source() is closed or not.
>                              if (got_cmd_ok) {
> +                                // assert here
>                                  break;
>                              } else {
>                                  throw;
> ```

Try this branch for you:

git@github.com:asias/scylla.git file_stream_source_for_gleb

./test.py -s --repeat 500 --mode debug -v boost/file_stream_test

2025-01-09 22:21 UTC, scylladb-promoter commented
#### :red_circle: CI State: FAILURE

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14328/)
:white_check_mark: - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14328/)
**The following new/updated tests ran 100 times for each mode:**
:small_blue_diamond: boost/file_stream_test
:small_blue_diamond: topology_custom/test_tablets2
:small_blue_diamond: topology_custom/test_tablets_migration
:small_blue_diamond: topology_custom/test_topology_ops_encrypted
:white_check_mark: - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/13828/)
:white_check_mark: - [Docker Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-docker/1069/)
:white_check_mark: - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/2700/)
:white_check_mark: - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/5815/)
:white_check_mark: - [Offline-installer Artifact Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-offline-installer/471/)
:x: - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14328/)
#### Failed Tests (1/53759):
- [test_view_build_status_cleanup_on_remove_node.release.3](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14328/testReport/junit/topology_custom/test_view_build_status/Tests___Unit_Tests___test_view_build_status_cleanup_on_remove_node_release_3) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_view_build_status_cleanup_on_remove_node.release.3)
#### Build Details:
- Duration: 13 hr
- Builder: spider3.cloudius-systems.com

2025-01-10 06:26 UTC, asias commented
> #### 🔴 CI State: FAILURE
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14328/) ✅ - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14328/) **The following new/updated tests ran 100 times for each mode:** 🔹 boost/file_stream_test 🔹 topology_custom/test_tablets2 🔹 topology_custom/test_tablets_migration 🔹 topology_custom/test_topology_ops_encrypted ✅ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/13828/) ✅ - [Docker Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-docker/1069/) ✅ - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/2700/) ✅ - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/5815/) ✅ - [Offline-installer Artifact Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-offline-installer/471/) ❌ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14328/)
> 
> #### Failed Tests (1/53759):
> * [test_view_build_status_cleanup_on_remove_node.release.3](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14328/testReport/junit/topology_custom/test_view_build_status/Tests___Unit_Tests___test_view_build_status_cleanup_on_remove_node_release_3) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_view_build_status_cleanup_on_remove_node.release.3)

Known issue: https://github.com/scylladb/scylladb/issues/21628

This run confirms test_file_stream issue is fixed now.

2025-01-12 14:28 UTC, gleb-cloudius commented
Sent "rpc stream: do not abort stream queue if stream connection was closed without error" to the seastar ML.

2025-01-13 10:19 UTC, mykaul commented
> Sent "rpc stream: do not abort stream queue if stream connection was closed without error" to the seastar ML.

@xemul , @bhalevy , @kbr-scylla - anyone else - please review it on the Seastar ML. Is this critical to get this patch in?

2025-01-16 00:41 UTC, asias commented
Changes in 0af53a444329b7fd92ab3747594d25b3eca14c1e:
- Rebased to fix conflicts in sstables/sstables.hh

2025-01-16 00:42 UTC, asias commented
> > > Sent "rpc stream: do not abort stream queue if stream connection was closed without error" to the seastar ML.
> > 
> > 
> > @xemul , @bhalevy , @kbr-scylla - anyone else - please review it on the Seastar ML. Is this critical to get this patch in?
> 
> If we have a fix already, we might as well wait for it to make it in. CI is unstable enough already.

Yes, we will not wait for the fix in the seastar. The workaround in the PR is good enough.

2025-01-17 01:24 UTC, asias commented
> #### 🔴 CI State: FAILURE
> 
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14495/) ✅ - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14495/) **The following new/updated tests ran 100 times for each mode:** 🔹 boost/file_stream_test 🔹 topology_custom/test_tablets2 🔹 topology_custom/test_tablets_migration 🔹 topology_custom/test_topology_ops_encrypted ❌ - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/2825/) ❌ - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/5945/) ❌ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/13954/) ✅ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14495/)
> #### Failed Tests (31/53915):
> 
>     * [test_data_distribution_balance[3-SizeTieredCompactionStrategy]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14495/testReport/junit/data_distribution_balance_test/TestDataDistribution/Tests___dtest_with_tablets___test_data_distribution_balance_3_SizeTieredCompactionStrategy_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_data_distribution_balance%5B3-SizeTieredCompactionStrategy%5D)
> 
>     * [test_data_distribution_balance[4-LeveledCompactionStrategy]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14495/testReport/junit/data_distribution_balance_test/TestDataDistribution/Tests___dtest_with_tablets___test_data_distribution_balance_4_LeveledCompactionStrategy_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_data_distribution_balance%5B4-LeveledCompactionStrategy%5D)
> 
>     * [test_data_distribution_balance[3-LeveledCompactionStrategy]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14495/testReport/junit/data_distribution_balance_test/TestDataDistribution/Tests___dtest_with_tablets___test_data_distribution_balance_3_LeveledCompactionStrategy_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_data_distribution_balance%5B3-LeveledCompactionStrategy%5D)
> 
>     * [test_hintedhandoff_rebalance](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14495/testReport/junit/hintedhandoff_additional_test/TestHintedHandoff/Tests___dtest_with_tablets___test_hintedhandoff_rebalance) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_hintedhandoff_rebalance)
> 
>     * [test_data_distribution_balance[3-TimeWindowCompactionStrategy]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14495/testReport/junit/data_distribution_balance_test/TestDataDistribution/Tests___dtest_with_tablets___test_data_distribution_balance_3_TimeWindowCompactionStrategy_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_data_distribution_balance%5B3-TimeWindowCompactionStrategy%5D)
> 
>     * [test_repair_option_pr_multi_dc](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14495/testReport/junit/repair_additional_test/TestRepairAdditional/Tests___dtest_with_tablets___test_repair_option_pr_multi_dc) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_repair_option_pr_multi_dc)
> 
>     * [test_concurrent_drain](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14495/testReport/junit/nodetool_additional_test/TestNodetool/Tests___dtest_with_tablets___test_concurrent_drain) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_concurrent_drain)
> 
>     * [test_hintedhandoff_retransmit](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14495/testReport/junit/hintedhandoff_additional_test/TestHintedHandoff/Tests___dtest_with_tablets___test_hintedhandoff_retransmit) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_hintedhandoff_retransmit)
> 
>     * [test_rolling_cluster_replacement_sequentially_live_nodes_multi_dc](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14495/testReport/junit/cluster_replacement_test/TestClusterReplacement/Tests___dtest_with_tablets___test_rolling_cluster_replacement_sequentially_live_nodes_multi_dc) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_rolling_cluster_replacement_sequentially_live_nodes_multi_dc)
> 
>     * [test_repair_option_pr_multi_dc](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14495/testReport/junit/repair_additional_test/TestRepairAdditional/Tests___dtest_with_tablets___test_repair_option_pr_multi_dc_2) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_repair_option_pr_multi_dc)
> 
> 
> #### Build Details:
> 
>     * Duration: 14 hr
> 
>     * Builder: spider3.cloudius-systems.com

I looked the CI errors and created:

CI: data_distribution_balance_test.TestDataDistribution.test_data_distribution_balance self.cluster.stress() timed out #22361
CI: test_hintedhandoff_rebalance and test_hintedhandoff_retransmit failed with node1.stress_object timeout #22360
CI: init - Startup failed: exceptions::read_timeout_exception (Operation timed out for system.roles - received only 0 responses from 1 CL=QUORUM.) #22362
CI: nodetool_additional_test.TestNodetool.test_concurrent_drain failed with general_concurrent #22363
CI: test_rolling_cluster_replacement_sequentially_live_nodes_multi_dc failed with drain rpc failed, proceed to fence old writes: raft::request_aborted #22364
`

2025-01-17 07:56 UTC, denesb commented
> > #### 🔴 CI State: FAILURE
> > ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14495/) ✅ - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14495/) **The following new/updated tests ran 100 times for each mode:** 🔹 boost/file_stream_test 🔹 topology_custom/test_tablets2 🔹 topology_custom/test_tablets_migration 🔹 topology_custom/test_topology_ops_encrypted ❌ - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/2825/) ❌ - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/5945/) ❌ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/13954/) ✅ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14495/)
> > #### Failed Tests (31/53915):
> > ```
> > * [test_data_distribution_balance[3-SizeTieredCompactionStrategy]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14495/testReport/junit/data_distribution_balance_test/TestDataDistribution/Tests___dtest_with_tablets___test_data_distribution_balance_3_SizeTieredCompactionStrategy_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_data_distribution_balance%5B3-SizeTieredCompactionStrategy%5D)
> > 
> > * [test_data_distribution_balance[4-LeveledCompactionStrategy]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14495/testReport/junit/data_distribution_balance_test/TestDataDistribution/Tests___dtest_with_tablets___test_data_distribution_balance_4_LeveledCompactionStrategy_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_data_distribution_balance%5B4-LeveledCompactionStrategy%5D)
> > 
> > * [test_data_distribution_balance[3-LeveledCompactionStrategy]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14495/testReport/junit/data_distribution_balance_test/TestDataDistribution/Tests___dtest_with_tablets___test_data_distribution_balance_3_LeveledCompactionStrategy_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_data_distribution_balance%5B3-LeveledCompactionStrategy%5D)
> > 
> > * [test_hintedhandoff_rebalance](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14495/testReport/junit/hintedhandoff_additional_test/TestHintedHandoff/Tests___dtest_with_tablets___test_hintedhandoff_rebalance) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_hintedhandoff_rebalance)
> > 
> > * [test_data_distribution_balance[3-TimeWindowCompactionStrategy]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14495/testReport/junit/data_distribution_balance_test/TestDataDistribution/Tests___dtest_with_tablets___test_data_distribution_balance_3_TimeWindowCompactionStrategy_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_data_distribution_balance%5B3-TimeWindowCompactionStrategy%5D)
> > 
> > * [test_repair_option_pr_multi_dc](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14495/testReport/junit/repair_additional_test/TestRepairAdditional/Tests___dtest_with_tablets___test_repair_option_pr_multi_dc) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_repair_option_pr_multi_dc)
> > 
> > * [test_concurrent_drain](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14495/testReport/junit/nodetool_additional_test/TestNodetool/Tests___dtest_with_tablets___test_concurrent_drain) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_concurrent_drain)
> > 
> > * [test_hintedhandoff_retransmit](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14495/testReport/junit/hintedhandoff_additional_test/TestHintedHandoff/Tests___dtest_with_tablets___test_hintedhandoff_retransmit) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_hintedhandoff_retransmit)
> > 
> > * [test_rolling_cluster_replacement_sequentially_live_nodes_multi_dc](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14495/testReport/junit/cluster_replacement_test/TestClusterReplacement/Tests___dtest_with_tablets___test_rolling_cluster_replacement_sequentially_live_nodes_multi_dc) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_rolling_cluster_replacement_sequentially_live_nodes_multi_dc)
> > 
> > * [test_repair_option_pr_multi_dc](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14495/testReport/junit/repair_additional_test/TestRepairAdditional/Tests___dtest_with_tablets___test_repair_option_pr_multi_dc_2) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_repair_option_pr_multi_dc)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > #### Build Details:
> > ```
> > * Duration: 14 hr
> > 
> > * Builder: spider3.cloudius-systems.com
> > ```
> 
> I looked the CI errors and created:
> 
> CI: data_distribution_balance_test.TestDataDistribution.test_data_distribution_balance self.cluster.stress() timed out #22361 CI: test_hintedhandoff_rebalance and test_hintedhandoff_retransmit failed with node1.stress_object timeout #22360 CI: init - Startup failed: exceptions::read_timeout_exception (Operation timed out for system.roles - received only 0 responses from 1 CL=QUORUM.) #22362 CI: nodetool_additional_test.TestNodetool.test_concurrent_drain failed with general_concurrent #22363 CI: test_rolling_cluster_replacement_sequentially_live_nodes_multi_dc failed with drain rpc failed, proceed to fence old writes: raft::request_aborted #22364 `

This looks like a complete meltdown, timeouts everywhere. I'm not sure it is worth opening issues for these.

2025-01-17 08:01 UTC, asias commented
> > > #### 🔴 CI State: FAILURE
> > > ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14495/) ✅ - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14495/) **The following new/updated tests ran 100 times for each mode:** 🔹 boost/file_stream_test 🔹 topology_custom/test_tablets2 🔹 topology_custom/test_tablets_migration 🔹 topology_custom/test_topology_ops_encrypted ❌ - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/2825/) ❌ - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/5945/) ❌ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/13954/) ✅ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14495/)
> > > #### Failed Tests (31/53915):
> > > ```
> > > * [test_data_distribution_balance[3-SizeTieredCompactionStrategy]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14495/testReport/junit/data_distribution_balance_test/TestDataDistribution/Tests___dtest_with_tablets___test_data_distribution_balance_3_SizeTieredCompactionStrategy_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_data_distribution_balance%5B3-SizeTieredCompactionStrategy%5D)
> > > 
> > > * [test_data_distribution_balance[4-LeveledCompactionStrategy]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14495/testReport/junit/data_distribution_balance_test/TestDataDistribution/Tests___dtest_with_tablets___test_data_distribution_balance_4_LeveledCompactionStrategy_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_data_distribution_balance%5B4-LeveledCompactionStrategy%5D)
> > > 
> > > * [test_data_distribution_balance[3-LeveledCompactionStrategy]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14495/testReport/junit/data_distribution_balance_test/TestDataDistribution/Tests___dtest_with_tablets___test_data_distribution_balance_3_LeveledCompactionStrategy_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_data_distribution_balance%5B3-LeveledCompactionStrategy%5D)
> > > 
> > > * [test_hintedhandoff_rebalance](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14495/testReport/junit/hintedhandoff_additional_test/TestHintedHandoff/Tests___dtest_with_tablets___test_hintedhandoff_rebalance) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_hintedhandoff_rebalance)
> > > 
> > > * [test_data_distribution_balance[3-TimeWindowCompactionStrategy]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14495/testReport/junit/data_distribution_balance_test/TestDataDistribution/Tests___dtest_with_tablets___test_data_distribution_balance_3_TimeWindowCompactionStrategy_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_data_distribution_balance%5B3-TimeWindowCompactionStrategy%5D)
> > > 
> > > * [test_repair_option_pr_multi_dc](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14495/testReport/junit/repair_additional_test/TestRepairAdditional/Tests___dtest_with_tablets___test_repair_option_pr_multi_dc) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_repair_option_pr_multi_dc)
> > > 
> > > * [test_concurrent_drain](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14495/testReport/junit/nodetool_additional_test/TestNodetool/Tests___dtest_with_tablets___test_concurrent_drain) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_concurrent_drain)
> > > 
> > > * [test_hintedhandoff_retransmit](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14495/testReport/junit/hintedhandoff_additional_test/TestHintedHandoff/Tests___dtest_with_tablets___test_hintedhandoff_retransmit) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_hintedhandoff_retransmit)
> > > 
> > > * [test_rolling_cluster_replacement_sequentially_live_nodes_multi_dc](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14495/testReport/junit/cluster_replacement_test/TestClusterReplacement/Tests___dtest_with_tablets___test_rolling_cluster_replacement_sequentially_live_nodes_multi_dc) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_rolling_cluster_replacement_sequentially_live_nodes_multi_dc)
> > > 
> > > * [test_repair_option_pr_multi_dc](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14495/testReport/junit/repair_additional_test/TestRepairAdditional/Tests___dtest_with_tablets___test_repair_option_pr_multi_dc_2) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_repair_option_pr_multi_dc)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > #### Build Details:
> > > ```
> > > * Duration: 14 hr
> > > 
> > > * Builder: spider3.cloudius-systems.com
> > > ```
> > 
> > 
> > I looked the CI errors and created:
> > CI: data_distribution_balance_test.TestDataDistribution.test_data_distribution_balance self.cluster.stress() timed out #22361 CI: test_hintedhandoff_rebalance and test_hintedhandoff_retransmit failed with node1.stress_object timeout #22360 CI: init - Startup failed: exceptions::read_timeout_exception (Operation timed out for system.roles - received only 0 responses from 1 CL=QUORUM.) #22362 CI: nodetool_additional_test.TestNodetool.test_concurrent_drain failed with general_concurrent #22363 CI: test_rolling_cluster_replacement_sequentially_live_nodes_multi_dc failed with drain rpc failed, proceed to fence old writes: raft::request_aborted #22364 `
> 
> This looks like a complete meltdown, timeouts everywhere. I'm not sure it is worth opening issues for these.

Some of them are timeout and 

> > > #### 🔴 CI State: FAILURE
> > > ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14495/) ✅ - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14495/) **The following new/updated tests ran 100 times for each mode:** 🔹 boost/file_stream_test 🔹 topology_custom/test_tablets2 🔹 topology_custom/test_tablets_migration 🔹 topology_custom/test_topology_ops_encrypted ❌ - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/2825/) ❌ - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/5945/) ❌ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/13954/) ✅ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14495/)
> > > #### Failed Tests (31/53915):
> > > ```
> > > * [test_data_distribution_balance[3-SizeTieredCompactionStrategy]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14495/testReport/junit/data_distribution_balance_test/TestDataDistribution/Tests___dtest_with_tablets___test_data_distribution_balance_3_SizeTieredCompactionStrategy_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_data_distribution_balance%5B3-SizeTieredCompactionStrategy%5D)
> > > 
> > > * [test_data_distribution_balance[4-LeveledCompactionStrategy]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14495/testReport/junit/data_distribution_balance_test/TestDataDistribution/Tests___dtest_with_tablets___test_data_distribution_balance_4_LeveledCompactionStrategy_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_data_distribution_balance%5B4-LeveledCompactionStrategy%5D)
> > > 
> > > * [test_data_distribution_balance[3-LeveledCompactionStrategy]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14495/testReport/junit/data_distribution_balance_test/TestDataDistribution/Tests___dtest_with_tablets___test_data_distribution_balance_3_LeveledCompactionStrategy_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue [...]

2025-01-17 08:13 UTC, asias commented
Rebased to latest master. Hoping the recent CI related fix is making the CI more stable.

2025-01-17 17:14 UTC, scylladb-promoter commented
#### :red_circle: CI State: FAILURE

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14534/)
:x: - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14534/)
**The following new/updated tests ran 100 times for each mode:**
:small_blue_diamond: boost/file_stream_test
:small_blue_diamond: topology_custom/test_tablets2
:small_blue_diamond: topology_custom/test_tablets_migration
:small_blue_diamond: topology_custom/test_topology_ops_encrypted
#### Failed Tests (4/15149):
- [test_topology_ops_encrypted[False].debug.2](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14534/testReport/junit/topology_custom/test_topology_ops_encrypted/test_topology_ops_encrypted_False__debug_2) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_topology_ops_encrypted[False].debug.2)
- [test_topology_ops_encrypted[False].debug.2](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14534/testReport/junit/topology_custom/test_topology_ops_encrypted/test_topology_ops_encrypted_False__debug_2_2) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_topology_ops_encrypted[False].debug.2)
- [test_topology_ops_encrypted[True].debug.2](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14534/testReport/junit/topology_custom/test_topology_ops_encrypted/test_topology_ops_encrypted_True__debug_2) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_topology_ops_encrypted[True].debug.2)
- [test_topology_ops_encrypted[True].debug.2](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14534/testReport/junit/topology_custom/test_topology_ops_encrypted/test_topology_ops_encrypted_True__debug_2_2) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_topology_ops_encrypted[True].debug.2)
#### Build Details:
- Duration: 9 hr 2 min
- Builder: spider6.cloudius-systems.com

2025-01-19 08:54 UTC, bhalevy commented
> #### 🔴 CI State: FAILURE
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14534/) ❌ - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14534/) **The following new/updated tests ran 100 times for each mode:** 🔹 boost/file_stream_test 🔹 topology_custom/test_tablets2 🔹 topology_custom/test_tablets_migration 🔹 topology_custom/test_topology_ops_encrypted
> 
> #### Failed Tests (4/15149):
> * [test_topology_ops_encrypted[False].debug.2](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14534/testReport/junit/topology_custom/test_topology_ops_encrypted/test_topology_ops_encrypted_False__debug_2) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_topology_ops_encrypted%5BFalse%5D.debug.2)
> * [test_topology_ops_encrypted[False].debug.2](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14534/testReport/junit/topology_custom/test_topology_ops_encrypted/test_topology_ops_encrypted_False__debug_2_2) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_topology_ops_encrypted%5BFalse%5D.debug.2)
> * [test_topology_ops_encrypted[True].debug.2](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14534/testReport/junit/topology_custom/test_topology_ops_encrypted/test_topology_ops_encrypted_True__debug_2) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_topology_ops_encrypted%5BTrue%5D.debug.2)
> * [test_topology_ops_encrypted[True].debug.2](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14534/testReport/junit/topology_custom/test_topology_ops_encrypted/test_topology_ops_encrypted_True__debug_2_2) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_topology_ops_encrypted%5BTrue%5D.debug.2)

Look like environmental issue, likely unrelated to this change
respinning.

2025-01-19 22:51 UTC, scylladb-promoter commented
#### :green_circle: CI State: SUCCESS

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14559/)
:white_check_mark: - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14559/)
**The following new/updated tests ran 100 times for each mode:**
:small_blue_diamond: boost/file_stream_test
:small_blue_diamond: topology_custom/test_tablets2
:small_blue_diamond: topology_custom/test_tablets_migration
:small_blue_diamond: topology_custom/test_topology_ops_encrypted
:white_check_mark: - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14559/)
#### Build Details:
- Duration: 13 hr
- Builder: spider1.cloudius-systems.com

2025-01-19 23:31 UTC, asias commented
> #### 🟢 CI State: SUCCESS
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14559/) ✅ - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14559/) **The following new/updated tests ran 100 times for each mode:** 🔹 boost/file_stream_test 🔹 topology_custom/test_tablets2 🔹 topology_custom/test_tablets_migration 🔹 topology_custom/test_topology_ops_encrypted ✅ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14559/)
> 
> #### Build Details:
> * Duration: 13 hr
> * Builder: spider1.cloudius-systems.com

@denesb The CI is green now. Please merge.

2025-01-20 08:21 UTC, gleb-cloudius commented on streaming/stream_blob.cc
> +        gms::inet_address node;
Why is this no host_id based? Can we please do not introduce more ip based code into the master?

2025-01-20 08:24 UTC, gleb-cloudius requested changes
I see that this patch series introduces some new code that works on IPs. I am trying to figure out why and it looks like there is no real reason. May be I am missing something, but if I do not please amend the code to drop IP dependencies before merging.

2025-01-20 08:28 UTC, denesb commented
Dequeued, breaks roll-back test.
https://jenkins.scylladb.com/job/scylla-master/job/next/8717/testReport/junit/enterprise_upgrade_test/TestEnterpriseRollingUpgrade/Build___x86___dtest_with_tablets___test_rolling_upgrade/

2025-01-20 08:29 UTC, asias commented
> I see that this patch series introduces some new code that works on IPs. I am trying to figure out why and it looks like there is no real reason. May be I am missing something, but if I do not please amend the code to drop IP dependencies before merging.

This migrates the file stream code which exists long before your host id conversion patch.  This is a big one, I do not want to introduce more code changes before the initial import. I have already changed the rpc related code to use host id instead of ip.

2025-01-20 08:36 UTC, asias commented
> Dequeued, breaks roll-back test. https://jenkins.scylladb.com/job/scylla-master/job/next/8717/testReport/junit/enterprise_upgrade_test/TestEnterpriseRollingUpgrade/Build___x86___dtest_with_tablets___test_rolling_upgrade/

What  version combination does it test exactly? The test name says it is an enterprise upgrade test.

2025-01-20 08:36 UTC, gleb-cloudius commented
> > I see that this patch series introduces some new code that works on IPs. I am trying to figure out why and it looks like there is no real reason. May be I am missing something, but if I do not please amend the code to drop IP dependencies before merging.
> 
> This migrates the file stream code which exists long before your host id conversion patch. This is a big one, I do not want to introduce more code changes before the initial import. I have already changed the rpc related code to use host id instead of ip.

Was this code ever in production? If not I think is it safe to amend it during migration. And changing the rpc is 90% of the change anyway (thanks for doing it!) the rest is just dropping no longer needed conversions. Or lets at least agree to amend it on top after it merged in as a high prio task. @denesb ?

2025-01-20 08:50 UTC, asias commented
> > > I see that this patch series introduces some new code that works on IPs. I am trying to figure out why and it looks like there is no real reason. May be I am missing something, but if I do not please amend the code to drop IP dependencies before merging.
> > 
> > 
> > This migrates the file stream code which exists long before your host id conversion patch. This is a big one, I do not want to introduce more code changes before the initial import. I have already changed the rpc related code to use host id instead of ip.
> 
> Was this code ever in production? If not I think is it safe to amend it during migration. And changing the rpc is 90% of the change anyway (thanks for doing it!) the rest is just dropping no longer needed conversions. Or lets at least agree to amend it on top after it merged in as a high prio task. @denesb ?

Yes, it is in production. Let's do that after the initial merge as a follow up.

2025-01-20 08:57 UTC, asias commented
> > Dequeued, breaks roll-back test. https://jenkins.scylladb.com/job/scylla-master/job/next/8717/testReport/junit/enterprise_upgrade_test/TestEnterpriseRollingUpgrade/Build___x86___dtest_with_tablets___test_rolling_upgrade/
> 
> What version combination does it test exactly? The test name says it is an enterprise upgrade test.

The test looks problematic. It downgrades from 2024.2.2-0.20241220.4c6e906e2691 (enterprise with FILE_STREAM feature) to 2025.1.0~dev-0.20250119.1ef2d9d07692 (recent master, without FILE_STREAM). This is not supported. 

```
[asias@hjpc2 1737304604348_enterprise_upgrade_test.py::TestEnterpriseRollingUpgrade::test_rolling_upgrade]$ cat node1.log |grep Scylla|grep version
Scylla version 2024.2.2-0.20241220.4c6e906e2691 with build-id 8b8a2f897f7a35695d158dc5d1d649ae1b28e04b starting ...
INFO  2025-01-19 16:36:24,228 [shard 0:main] init - Scylla version 2024.2.2-0.20241220.4c6e906e2691 with build-id 8b8a2f897f7a35695d158dc5d1d649ae1b28e04b starting ...
INFO  2025-01-19 16:36:24,386 [shard 0:main] init - Scylla version 2024.2.2-0.20241220.4c6e906e2691 initialization completed.
INFO  2025-01-19 16:36:39,656 [shard 0:main] init - Scylla version 2024.2.2-0.20241220.4c6e906e2691 shutdown complete.
Scylla version 2025.1.0~dev-0.20250119.1ef2d9d07692 with build-id e16c81a8ccdafe6190a5846930a953c8c8312a12 starting ...
INFO  2025-01-19 16:36:40,841 [shard 0:main] init - Scylla version 2025.1.0~dev-0.20250119.1ef2d9d07692 with build-id e16c81a8ccdafe6190a5846930a953c8c8312a12 starting ...
```

2025-01-20 09:29 UTC, denesb commented
> > > Dequeued, breaks roll-back test. https://jenkins.scylladb.com/job/scylla-master/job/next/8717/testReport/junit/enterprise_upgrade_test/TestEnterpriseRollingUpgrade/Build___x86___dtest_with_tablets___test_rolling_upgrade/
> > 
> > 
> > What version combination does it test exactly? The test name says it is an enterprise upgrade test.
> 
> The test looks problematic. It downgrades from 2024.2.2-0.20241220.4c6e906e2691 (enterprise with FILE_STREAM feature) to 2025.1.0~dev-0.20250119.1ef2d9d07692 (recent master, without FILE_STREAM). This is not supported.
> 
> ```
> [asias@hjpc2 1737304604348_enterprise_upgrade_test.py::TestEnterpriseRollingUpgrade::test_rolling_upgrade]$ cat node1.log |grep Scylla|grep version
> Scylla version 2024.2.2-0.20241220.4c6e906e2691 with build-id 8b8a2f897f7a35695d158dc5d1d649ae1b28e04b starting ...
> INFO  2025-01-19 16:36:24,228 [shard 0:main] init - Scylla version 2024.2.2-0.20241220.4c6e906e2691 with build-id 8b8a2f897f7a35695d158dc5d1d649ae1b28e04b starting ...
> INFO  2025-01-19 16:36:24,386 [shard 0:main] init - Scylla version 2024.2.2-0.20241220.4c6e906e2691 initialization completed.
> INFO  2025-01-19 16:36:39,656 [shard 0:main] init - Scylla version 2024.2.2-0.20241220.4c6e906e2691 shutdown complete.
> Scylla version 2025.1.0~dev-0.20250119.1ef2d9d07692 with build-id e16c81a8ccdafe6190a5846930a953c8c8312a12 starting ...
> INFO  2025-01-19 16:36:40,841 [shard 0:main] init - Scylla version 2025.1.0~dev-0.20250119.1ef2d9d07692 with build-id e16c81a8ccdafe6190a5846930a953c8c8312a12 starting ...
> ```

Ah, so this PR will actually *fix* this problem, instead of breaking the test.

2025-01-20 09:33 UTC, asias commented
On Mon, Jan 20, 2025, 17:29 Botond Dénes ***@***.***> wrote:

> Dequeued, breaks roll-back test.
> https://jenkins.scylladb.com/job/scylla-master/job/next/8717/testReport/junit/enterprise_upgrade_test/TestEnterpriseRollingUpgrade/Build___x86___dtest_with_tablets___test_rolling_upgrade/
>
> What version combination does it test exactly? The test name says it is an
> enterprise upgrade test.
>
> The test looks problematic. It downgrades from
> 2024.2.2-0.20241220.4c6e906e2691 (enterprise with FILE_STREAM feature) to
> 2025.1.0~dev-0.20250119.1ef2d9d07692 (recent master, without FILE_STREAM).
> This is not supported.
>
> ***@***.*** 1737304604348_enterprise_upgrade_test.py::TestEnterpriseRollingUpgrade::test_rolling_upgrade]$ cat node1.log |grep Scylla|grep version
> Scylla version 2024.2.2-0.20241220.4c6e906e2691 with build-id 8b8a2f897f7a35695d158dc5d1d649ae1b28e04b starting ...
> INFO  2025-01-19 16:36:24,228 [shard 0:main] init - Scylla version 2024.2.2-0.20241220.4c6e906e2691 with build-id 8b8a2f897f7a35695d158dc5d1d649ae1b28e04b starting ...
> INFO  2025-01-19 16:36:24,386 [shard 0:main] init - Scylla version 2024.2.2-0.20241220.4c6e906e2691 initialization completed.
> INFO  2025-01-19 16:36:39,656 [shard 0:main] init - Scylla version 2024.2.2-0.20241220.4c6e906e2691 shutdown complete.
> Scylla version 2025.1.0~dev-0.20250119.1ef2d9d07692 with build-id e16c81a8ccdafe6190a5846930a953c8c8312a12 starting ...
> INFO  2025-01-19 16:36:40,841 [shard 0:main] init - Scylla version 2025.1.0~dev-0.20250119.1ef2d9d07692 with build-id e16c81a8ccdafe6190a5846930a953c8c8312a12 starting ...
>
> Ah, so this PR will actually *fix* this problem, instead of breaking the
> test.
>

Yes.

—
> Reply to this email directly, view it on GitHub
> <https://github.com/scylladb/scylladb/pull/22034#issuecomment-2601873746>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACOETBXK6SPAF7QEGBRWT32LS6YXAVCNFSM6AAAAABUD7GLMKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDMMBRHA3TGNZUGY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2025-01-20 09:43 UTC, denesb commented
Ok, re-queued.

2025-01-20 09:44 UTC, denesb commented
How did we get into the situation where that test got promoted to master?

2025-01-20 09:45 UTC, denesb commented
Normally, we should revert whatever caused that test to be running, but in the interest of progress, I think it is more productive to just queue this PR on top to fix it.

2025-01-21 08:34 UTC, denesb commented
> > > I see that this patch series introduces some new code that works on IPs. I am trying to figure out why and it looks like there is no real reason. May be I am missing something, but if I do not please amend the code to drop IP dependencies before merging.
> > 
> > 
> > This migrates the file stream code which exists long before your host id conversion patch. This is a big one, I do not want to introduce more code changes before the initial import. I have already changed the rpc related code to use host id instead of ip.
> 
> Was this code ever in production? If not I think is it safe to amend it during migration. And changing the rpc is 90% of the change anyway (thanks for doing it!) the rest is just dropping no longer needed conversions. Or lets at least agree to amend it on top after it merged in as a high prio task. @denesb ?

Created follow-up task here: https://github.com/scylladb/scylladb/issues/22421 so we don't forget about it.

2025-01-22 06:53 UTC, closed without merging

2025-01-22 07:27 UTC, avikivity commented
This is different from the code in enterprise. How am I supposed to merge it?

Very frustrating, I am tempted to revert it.

2025-01-22 07:39 UTC, denesb commented
Indeed and many of them seem completely unnecessary, like reordering fields.
Would a follow-up which adjusts a code be a sufficient solution?

2025-01-22 07:39 UTC, denesb commented
I should have checked the diff before merging, sorry.

2025-01-22 07:58 UTC, denesb commented
There are functional changes too:
* Using locator::host_id instead of ip in verbs (messaging/messaging_service.{hh,cc})
* extra try-catch in `stream_blob.cc`

2025-01-22 08:10 UTC, piodul commented
> Indeed and many of them seem completely unnecessary, like reordering fields. Would a follow-up which adjusts a code be a sufficient solution?

When porting service levels, my approach was to send an adjustment patch to enterprise (https://github.com/scylladb/scylla-enterprise/pull/5117). Even though I did it before the main PR was merged rather than after, I think the effect will be the same, i.e. it will make it easier for Avi to perform the scylladb.git -> scylla-enterprise.git merge. It will also keep the scylladb.git history cleaner.

2025-01-22 08:14 UTC, mykaul commented
> Indeed and many of them seem completely unnecessary, like reordering fields. Would a follow-up which adjusts a code be a sufficient solution?

Sounds like a substantially better plan than a revert at this point.

2025-01-22 08:15 UTC, denesb commented
Follow-up PR to reduce diff: https://github.com/scylladb/scylladb/pull/22447

2025-01-22 09:07 UTC, asias commented
> This is different from the code in enterprise. How am I supposed to merge it?
> 
> Very frustrating, I am tempted to revert it.

Do you expect the code in this PR to be 100% the same as the code in enterprise? How is this possible with big changes like using hostid in rpc merged in master?

2025-01-22 09:09 UTC, asias commented
> There are functional changes too:
> 
> * Using locator::host_id instead of ip in verbs (messaging/messaging_service.{hh,cc})

This is a must due to the hostid rpc change in master. Without it the PR woudn't even compile. 

> * extra try-catch in `stream_blob.cc`

This is a workaround for the rpc stream bug.

2025-01-22 10:08 UTC, denesb commented
> > This is different from the code in enterprise. How am I supposed to merge it?
> > Very frustrating, I am tempted to revert it.
> 
> Do you expect the code in this PR to be 100% the same as the code in enterprise? How is this possible with big changes like using hostid in rpc merged in master?

Not 100% identical, but as close as possible. Avoiding any unnecessary changes like different place for function body or fields.

2025-01-22 11:26 UTC, avikivity commented
> 
> > * extra try-catch in `stream_blob.cc`
> 
> This is a workaround for the rpc stream bug.


Please send it to enterprise first then. Otherwise I will have a hard time resolving the differences.

2025-01-22 23:29 UTC, asias commented
> > > This is different from the code in enterprise. How am I supposed to merge it?
> > > Very frustrating, I am tempted to revert it.
> > 
> > 
> > Do you expect the code in this PR to be 100% the same as the code in enterprise? How is this possible with big changes like using hostid in rpc merged in master?
> 
> enterprise is also updated to reflect them.

When you merge the ip2hostid change alone from master to enterprise. The code in file stream that uses ip is not going to magically get reflected. The conflicts you see when you merge this PR does the update. 

Why do you merge the big patch set like ip2hostid change when you know there are pending  big enterprise to master migration in the first place.  This is asking for trouble to make everybody's life harder.

2025-01-23 00:05 UTC, asias commented
> > > * extra try-catch in `stream_blob.cc`
> > 
> > 
> > This is a workaround for the rpc stream bug.
> 
> Please send it to enterprise first then. Otherwise I will have a hard time resolving the differences.

There is no way to update the rpc part without merging the ip2hostid change to enterprise.

I added https://github.com/scylladb/scylla-enterprise/pull/5177 to update enterprise to make the merge easier.

2025-01-23 00:10 UTC, asias commented
The new PR to migrate file stream is here: https://github.com/scylladb/scylladb/pull/22467

2025-01-23 00:12 UTC, asias commented
> > > This is different from the code in enterprise. How am I supposed to merge it?
> > > Very frustrating, I am tempted to revert it.
> > 
> > 
> > Do you expect the code in this PR to be 100% the same as the code in enterprise? How is this possible with big changes like using hostid in rpc merged in master?
> 
> enterprise is also updated to reflect them.

Why do we still need to merge master to enterprise branch if we are going to migrate everything to master branch?

2025-01-23 00:21 UTC, asias commented
> > > I see that this patch series introduces some new code that works on IPs. I am trying to figure out why and it looks like there is no real reason. May be I am missing something, but if I do not please amend the code to drop IP dependencies before merging.
> > 
> > 
> > This migrates the file stream code which exists long before your host id conversion patch. This is a big one, I do not want to introduce more code changes before the initial import. I have already changed the rpc related code to use host id instead of ip.
> 
> Was this code ever in production? If not I think is it safe to amend it during migration. And changing the rpc is 90% of the change anyway (thanks for doing it!) the rest is just dropping no longer needed conversions. Or lets at least agree to amend it on top after it merged in as a high prio task. @denesb ?

And luckily I refused the ask to amend the PR to add more difference between enterprise and master.

2025-01-24 03:59 UTC, tchaikov commented
> Why do we still need to merge master to enterprise branch if we are going to migrate everything to master branch?

@asias Avi wants to use the zero difference between enterprise and master branches as a sign that we've done with the source available migration.