everywhere: add skeletal support for the in_memory_tables feature
scylladb/scylladb pull request #22068
Opened 2024-12-27 18:09 UTC by bhalevy

Forward-ported from scylla-enterprise.
Note that the feature has been deprecated and the implementation is provided only for backward compatibility with pre-existing features and schema.

Tested manually after adding the following to feature_service:
```
    gms::feature workload_prioritization { *this, "WORKLOAD_PRIORITIZATION"sv };
```

Launched a single-node cluster running 2023.1.10
```
cqlsh> create KEYSPACE ks WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};
cqlsh> create TABLE ks.test ( pk int PRIMARY KEY, val int ) WITH compaction = {'class': 'InMemoryCompactionStrategy'};
```

log:
```
Scylla version 2023.1.10-0.20241227.21cffccc1ccd with build-id bd65b8399cb13b713a87e57fe333cfcabfd50be7 starting ...
...
INFO  2024-12-27 19:45:16,563 [shard 0] migration_manager - Create new ColumnFamily: org.apache.cassandra.config.CFMetaData@0x600000f1b400[cfId=5529c630-c47a-11ef-bd1d-4295734ce5a8,ksName=ks,cfName=test,cfType=Standard,comparator=org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.UTF8Type),comment=,readRepairChance=0,dcLocalReadRepairChance=0,tombstoneGcOptions={"mode":"timeout","propagation_delay_in_seconds":"3600"},gcGraceSeconds=864000,keyValidator=org.apache.cassandra.db.marshal.Int32Type,minCompactionThreshold=4,maxCompactionThreshold=32,columnMetadata=[ColumnDefinition{name=pk, type=org.apache.cassandra.db.marshal.Int32Type, kind=PARTITION_KEY, componentIndex=0, droppedAt=-9223372036854775808}, ColumnDefinition{name=val, type=org.apache.cassandra.db.marshal.Int32Type, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}],compactionStrategyClass=class org.apache.cassandra.db.compaction.InMemoryCompactionStrategy,compactionStrategyOptions={enabled=true},compressionParameters={sstable_compression=org.apache.cassandra.io.compress.LZ4Compressor},bloomFilterFpChance=0.01,memtableFlushPeriod=0,caching={"keys":"ALL","rows_per_partition":"ALL"},cdc={},defaultTimeToLive=0,minIndexInterval=128,maxIndexInterval=2048,speculativeRetry=99.0PERCENTILE,triggers=[],isDense=false,in_memory=false,version=5529c631-c47a-11ef-bd1d-4295734ce5a8,droppedColumns={},collections={},indices={}]
INFO  2024-12-27 19:45:16,564 [shard 0] schema_tables - Creating ks.test id=5529c630-c47a-11ef-bd1d-4295734ce5a8 version=ec88d510-6aff-344a-914d-541d37081440
```

Upgraded to this branch and started scylla.
Verified that ks.test was successfuly loaded:

log:
```
INFO  2024-12-27 19:48:58,115 [shard 0:main] init - Scylla version 6.3.0~dev-0.20241227.a64c6dfc153e with build-id f9496134a09cf2e55d3865b9e9ff499f672aa7da starting ...
...
WARN  2024-12-27 19:53:02,948 [shard 1:main] CompactionStrategy - InMemoryCompactionStrategy is no longer supported. Defaulting to NullCompactionStrategy.
...
INFO  2024-12-27 19:53:02,948 [shard 0:main] database - Keyspace ks: Reading CF test id=5529c630-c47a-11ef-bd1d-4295734ce5a8 version=ec88d510-6aff-344a-914d-541d37081440 storage=/home/bhalevy/scylladb/data/ks/test-5529c630c47a11efbd1d4295734ce5a8
```

Then, tested:
```
cqlsh> describe KEYSPACE ks;

CREATE KEYSPACE ks WITH replication = {'class': 'org.apache.cassandra.locator.SimpleStrategy', 'replication_factor': '1'} AND durable_writes = true AND tablets = {'enabled': false};

CREATE TABLE ks.test (
    pk int,
    val int,
    PRIMARY KEY (pk)
) WITH bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'InMemoryCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND speculative_retry = '99.0PERCENTILE';

cqlsh> alter TABLE ks.test with compaction = {'class': 'SizeTieredCompactionStrategy'};
cqlsh> describe KEYSPACE ks;

CREATE KEYSPACE ks WITH replication = {'class': 'org.apache.cassandra.locator.SimpleStrategy', 'replication_factor': '1'} AND durable_writes = true AND tablets = {'enabled': false};

CREATE TABLE ks.test (
    pk int,
    val int,
    PRIMARY KEY (pk)
) WITH bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND speculative_retry = '99.0PERCENTILE'
    AND tombstone_gc = {'mode': 'timeout', 'propagation_delay_in_seconds': '3600'};
```

log:
```
INFO  2024-12-27 19:56:40,465 [shard 0:stmt] migration_manager - Update table 'ks.test' From org.apache.cassandra.config.CFMetaData@0x60000362d800[cfId=5529c630-c47a-11ef-bd1d-4295734ce5a8,ksName==ks,cfName=test,cfType=Standard,comparator=org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.UTF8Type),comment=,tombstoneGcOptions={"mode":"timeout","propagation_delay_in_seconds":"3600"},gcGraceSeconds=864000,minCompactionThreshold=4,maxCompactionThreshold=32,columnMetadata=[ColumnDefinition{name=pk, type=org.apache.cassandra.db.marshal.Int32Type, kind=PARTITION_KEY, componentIndex=0, droppedAt=-9223372036854775808}, ColumnDefinition{name=val, type=org.apache.cassandra.db.marshal.Int32Type, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}],compactionStrategyClass=class org.apache.cassandra.db.compaction.InMemoryCompactionStrategy,compactionStrategyOptions={enabled=true},compressionParameters={sstable_compression=org.apache.cassandra.io.compress.LZ4Compressor},bloomFilterFpChance=0.01,memtableFlushPeriod=0,caching={"keys":"ALL","rows_per_partition":"ALL"},cdc={},defaultTimeToLive=0,minIndexInterval=128,maxIndexInterval=2048,speculativeRetry=99.0PERCENTILE,triggers=[],isDense=false,version=ec88d510-6aff-344a-914d-541d37081440,droppedColumns={},collections={},indices={}] To org.apache.cassandra.config.CFMetaData@0x60000336e000[cfId=5529c630-c47a-11ef-bd1d-4295734ce5a8,ksName==ks,cfName=test,cfType=Standard,comparator=org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.UTF8Type),comment=,tombstoneGcOptions={"mode":"timeout","propagation_delay_in_seconds":"3600"},gcGraceSeconds=864000,minCompactionThreshold=4,maxCompactionThreshold=32,columnMetadata=[ColumnDefinition{name=pk, type=org.apache.cassandra.db.marshal.Int32Type, kind=PARTITION_KEY, componentIndex=0, droppedAt=-9223372036854775808}, ColumnDefinition{name=val, type=org.apache.cassandra.db.marshal.Int32Type, kind=REGULAR, componentIndex=null, droppedAt=-9223372036854775808}],compactionStrategyClass=class org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy,compactionStrategyOptions={enabled=true},compressionParameters={sstable_compression=org.apache.cassandra.io.compress.LZ4Compressor},bloomFilterFpChance=0.01,memtableFlushPeriod=0,caching={"keys":"ALL","rows_per_partition":"ALL"},cdc={},defaultTimeToLive=0,minIndexInterval=128,maxIndexInterval=2048,speculativeRetry=99.0PERCENTILE,triggers=[],isDense=false,version=ecccf010-c47b-11ef-b52c-622f2f0e87c4,droppedColumns={},collections={},indices={}]
INFO  2024-12-27 19:56:40,466 [shard 0: gms] schema_tables - Altering ks.test id=5529c630-c47a-11ef-bd1d-4295734ce5a8 version=ecccf010-c47b-11ef-b52c-622f2f0e87c4
```

**Please replace this line with justification for the backport/\* labels added to this PR**

2024-12-27 18:11 UTC, scylladb-promoter commented
## Docs Preview :book:
Docs Preview for this pull request is available [here](http://previews.docs.scylladb.com/scylladb/22068)

**Changed Files:**
- [architecture/sstable/sstable2/sstable-interpretation](http://previews.docs.scylladb.com/scylladb/22068/architecture/sstable/sstable2/sstable-interpretation)

**Note:** This preview will be available for 30 days and will be automatically deleted after that period. You can manually trigger a new build by committing changes.

2024-12-27 22:36 UTC, scylladb-promoter commented
#### :red_circle: CI State: FAILURE

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14113/)
:x: - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/5652/)
:x: - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/13665/)
:x: - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/2538/)
:white_check_mark: - [Offline-installer Artifact Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-offline-installer/314/)
:white_check_mark: - [Docker Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-docker/910/)
:white_check_mark: - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14113/)
#### Failed Tests (3/36466):
- [test_rolling_upgrade](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14113/testReport/junit/rolling_upgrade_test/TestRollingUpgrade/Tests___dtest_with_tablets___test_rolling_upgrade) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_rolling_upgrade)
- [test_rolling_upgrade](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14113/testReport/junit/rolling_upgrade_test/TestRollingUpgrade/Tests___dtest_with_topology_changes___test_rolling_upgrade) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_rolling_upgrade)
- [test_rolling_upgrade](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14113/testReport/junit/rolling_upgrade_test/TestRollingUpgrade/Tests___dtest___test_rolling_upgrade) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_rolling_upgrade)
#### Build Details:
- Duration: 4 hr 26 min
- Builder: spider4.cloudius-systems.com

2024-12-28 07:29 UTC, bhalevy commented on db/schema_tables.cc
> +        m.set_clustered_cell(ckey, *in_memory_cdef, atomic_cell::make_dead(timestamp, gc_clock::now()));
We should do this only if the cluster in_memory_tables feature is enabled.  Or maybe just ignore this column on read and never write it.
The schema compaction strategy class InMemoryCompactionStrategy is enough, so we don't really need this boolean column in the schema table.

2024-12-28 07:30 UTC, bhalevy commented
> #### 🔴 CI State: FAILURE
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14113/) ❌ - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/5652/) ❌ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/13665/) ❌ - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/2538/) ✅ - [Offline-installer Artifact Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-offline-installer/314/) ✅ - [Docker Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-docker/910/) ✅ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14113/)
> 
> #### Failed Tests (3/36466):
> * [test_rolling_upgrade](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14113/testReport/junit/rolling_upgrade_test/TestRollingUpgrade/Tests___dtest_with_tablets___test_rolling_upgrade) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_rolling_upgrade)
> * [test_rolling_upgrade](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14113/testReport/junit/rolling_upgrade_test/TestRollingUpgrade/Tests___dtest_with_topology_changes___test_rolling_upgrade) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_rolling_upgrade)
> * [test_rolling_upgrade](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14113/testReport/junit/rolling_upgrade_test/TestRollingUpgrade/Tests___dtest___test_rolling_upgrade) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_rolling_upgrade)
> 
> #### Build Details:
> * Duration: 4 hr 26 min
> * Builder: spider4.cloudius-systems.com

```
ERROR 2024-12-27 19:10:10,672 [shard 1:stmt] storage_proxy - Exception when communicating with 127.0.96.2, to read from system_schema.scylla_tables: sstables::malformed_sstable_exception (Failed to read partition from SSTable /jenkins/workspace/scylla-master/gating-dtest-release-with-tablets/scylla/.dtest/dtest-9yjxxr1n/test/node2/data/system_schema/scylla_tables-5d912ff1f7593665b2c88042ab5103dd/me-3gmf_1h5d_0857l2t3nondj6n3nc-big-Data.db due to Column in_memory missing in current schema)
```

I'll see if this column can just be ignored on read and never written so it'd exist iff the pre-upgrade version supported in_memory_tables.

2024-12-28 08:35 UTC, bhalevy commented
In v2 ([5654099](https://github.com/scylladb/scylladb/commit/56540992080f98e662dc830f657fb91409372c6c)):
- Ignore the in_memory column in make_scylla_tables_mutation
  - It is not needed, and writing it without considering the IN_MEMORY_TABLE cluster feature breaks rollback to OSS.

2024-12-28 12:43 UTC, scylladb-promoter commented
#### :red_circle: CI State: FAILURE

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14117/)
:white_check_mark: - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/2540/)
:white_check_mark: - [Docker Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-docker/913/)
:white_check_mark: - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/5654/)
:white_check_mark: - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/13667/)
:white_check_mark: - [Offline-installer Artifact Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-offline-installer/317/)
:x: - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14117/)
#### Failed Tests (1/36458):
- [test_snapshot_cursor_is_consistent_with_merging](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14117/testReport/junit/boost/mvcc_test/test_snapshot_cursor_is_consistent_with_merging) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_snapshot_cursor_is_consistent_with_merging)
#### Build Details:
- Duration: 4 hr 6 min
- Builder: spider4.cloudius-systems.com

2024-12-28 12:50 UTC, scylladb-promoter commented
#### :red_circle: CI State: ABORTED

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14116/)
:white_check_mark: - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/5655/)
:white_check_mark: - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/13668/)
:white_check_mark: - [Docker Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-docker/914/)
:white_check_mark: - [Offline-installer Artifact Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-offline-installer/318/)
:white_check_mark: - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/2542/)
:white_check_mark: - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14116/)
#### Build Details:
- Duration: 4 hr 16 min
- Builder: spider2.cloudius-systems.com

2024-12-29 06:54 UTC, bhalevy commented
> #### 🔴 CI State: FAILURE
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14117/) ✅ - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/2540/) ✅ - [Docker Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-docker/913/) ✅ - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/5654/) ✅ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/13667/) ✅ - [Offline-installer Artifact Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-offline-installer/317/) ❌ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14117/)
> 
> #### Failed Tests (1/36458):
> * [test_snapshot_cursor_is_consistent_with_merging](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14117/testReport/junit/boost/mvcc_test/test_snapshot_cursor_is_consistent_with_merging) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_snapshot_cursor_is_consistent_with_merging)

https://github.com/scylladb/scylladb/issues/13642

2025-01-05 18:15 UTC, bhalevy commented
- rebased.

@scylladb/scylla-maint please review and consider merging.

2025-01-05 21:09 UTC, avikivity commented on compaction/compaction_strategy.cc
> +    case compaction_strategy_type::unsupported_in_memory:
This is not a direct port and will cause unnecessary conflicts in the next merge.

Make it a straightforward port without gratuitous changes, either by editing the patch or changing enterprise.

2025-01-05 22:20 UTC, scylladb-promoter commented
#### :red_circle: CI State: FAILURE

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14224/)
:white_check_mark: - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/2616/)
:white_check_mark: - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/13742/)
:white_check_mark: - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/5729/)
:x: - [Offline-installer Artifact Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-offline-installer/388/)
:white_check_mark: - [Docker Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-docker/984/)
:white_check_mark: - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14224/)
#### Build Details:
- Duration: 4 hr 3 min
- Builder: spider6.cloudius-systems.com

2025-01-08 11:10 UTC, bhalevy commented on compaction/compaction_strategy.cc
> +    case compaction_strategy_type::unsupported_in_memory:
ok, let's do the straight forward port first and follow-up with changes

2025-01-08 12:21 UTC, bhalevy commented
In v2 ([e070ba2](https://github.com/scylladb/scylladb/commit/e070ba252c814fb91cef7cc8b6f6e93939211fb3)):
- reduced the diff with scylla-enterprise/enterprise to the bare minimum

The changes that need explanation are:
The only change, which is required unfortunately is:
```diff
bhalevy@lt scylla-enterprise$ git diff -R origin/enterprise..bhalevy-master/forward-port-in-memory-tables db/schema_tables.cc
diff --git b/db/schema_tables.cc a/db/schema_tables.cc
index 644fd30709..70ba9534f7 100644
--- b/db/schema_tables.cc
+++ a/db/schema_tables.cc
@@ -689,9 +689,10 @@ schema_ptr scylla_table_schema_history() {
 static
 mutation
 redact_columns_for_missing_features(mutation&& m, schema_features features) {
-    return std::move(m);
+    if (features.contains(schema_feature::IN_MEMORY_TABLES)) {
+        return std::move(m);
+    }
     // The following code is needed if there are new schema features that require redaction.
-#if 0
     if (m.schema()->cf_name() != SCYLLA_TABLES) {
         return std::move(m);
     }
@@ -700,7 +701,6 @@ redact_columns_for_missing_features(mutation&& m, schema_features features) {
     global_schema_ptr redacted_schema{scylla_tables(features)};
     m.upgrade(redacted_schema);
     return std::move(m);
-#endif
 }
 
```

Code in scylladb/master already has this `#ifdef` to always `return std::move(m)`
so there's no point in the IN_MEMORY_TABLES logic.

and:
```
 /**
@@ -1733,9 +1733,7 @@ mutation make_scylla_tables_mutation(schema_ptr table, api::timestamp_type times
         auto& cdef = *scylla_tables()->get_column_definition("partitioner");
         m.set_clustered_cell(ckey, cdef, atomic_cell::make_dead(timestamp, gc_clock::now()));
     }
-    // In-memory tables are deprecated since scylla-2024.1.0
-    // FIXME: delete the column when there's no live version supporting it anymore.
-    // Writing it here breaks upgrade rollback to versions that do not support the in_memory schema_feature
+    m.set_clustered_cell(ckey, "in_memory", table->is_in_memory(), timestamp);
     return m;
 }
 
```

The `in_memory` column is set unconditionally in enterprise,
but this breaks upgrade rollback when upgrading from non-enterprise version (e.g. 6.2)
since is isn't protected by the clustered schema_feature.
hence the FIXME comment.

Since setting in_memory for a table relies on the compaction strategy type in the schema in any case
the `in_memory` column in scylla_tables is redundant and not required, so there's no point setting it.

2025-01-08 17:12 UTC, scylladb-promoter commented
#### :red_circle: CI State: FAILURE

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14304/)
:white_check_mark: - [Docker Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-docker/1040/)
:x: - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/13798/)
:white_check_mark: - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/2670/)
:white_check_mark: - [Offline-installer Artifact Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-offline-installer/442/)
:white_check_mark: - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/5785/)
:x: - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14304/)
#### Failed Tests (3/36866):
- [test_simple_removenode_4](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14304/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/Tests___dtest___test_simple_removenode_4) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_simple_removenode_4)
- [test_simple_removenode_4](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14304/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/Tests___dtest___test_simple_removenode_4_2) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_simple_removenode_4)
- [test_system_schema_version_is_stable](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14304/testReport/junit/boost/schema_change_test/test_system_schema_version_is_stable) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_system_schema_version_is_stable)
#### Build Details:
- Duration: 4 hr 48 min
- Builder: spider6.cloudius-systems.com

2025-01-09 09:18 UTC, bhalevy commented
> #### 🔴 CI State: FAILURE
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14304/) ✅ - [Docker Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-docker/1040/) ❌ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/13798/) ✅ - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/2670/) ✅ - [Offline-installer Artifact Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-offline-installer/442/) ✅ - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/5785/) ❌ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14304/)
> 
> #### Failed Tests (3/36866):
> * [test_simple_removenode_4](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14304/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/Tests___dtest___test_simple_removenode_4) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_simple_removenode_4)
> * [test_simple_removenode_4](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14304/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/Tests___dtest___test_simple_removenode_4_2) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_simple_removenode_4)

https://github.com/scylladb/scylladb/issues/20814

> * [test_system_schema_version_is_stable](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14304/testReport/junit/boost/schema_change_test/test_system_schema_version_is_stable) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_system_schema_version_is_stable)

This needs fixing to adjust to the changes system schema.
Matching scylla-enterprise value of `3febbbce-8841-304a-abb9-170078ac173d`

2025-01-09 09:20 UTC, bhalevy commented
In v4 ([71e3f42](https://github.com/scylladb/scylladb/commit/71e3f42aba55761280d2ccbfc2c48f50c018ea29)):
- adjusted unit test: test_system_schema_version_is_stable

2025-01-09 11:08 UTC, scylladb-promoter commented
#### :red_circle: CI State: FAILURE

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14329/)
:x: - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14329/)
**The following new/updated tests ran 100 times for each mode:**
:small_blue_diamond: boost/schema_change_test
#### Build Details:
- Duration: 1 hr 47 min
- Builder: i-0af8076de5bb2bb5b (m5ad.8xlarge)

2025-01-09 12:47 UTC, bhalevy commented
> #### 🔴 CI State: FAILURE
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14329/) ❌ - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14329/) **The following new/updated tests ran 100 times for each mode:** 🔹 boost/schema_change_test

https://github.com/scylladb/scylladb/issues/22243

2025-01-10 09:52 UTC, scylladb-promoter commented
#### :red_circle: CI State: FAILURE

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14367/)
:x: - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14367/)
**The following new/updated tests ran 100 times for each mode:**
:small_blue_diamond: boost/schema_change_test
#### Build Details:
- Duration: 1 hr 54 min
- Builder: i-01884637f75090e07 (m5ad.8xlarge)

2025-01-10 12:13 UTC, scylladb-promoter commented
#### :red_circle: CI State: FAILURE

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14365/)
:white_check_mark: - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14365/)
**The following new/updated tests ran 100 times for each mode:**
:small_blue_diamond: boost/schema_change_test
:white_check_mark: - [Docker Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-docker/1080/)
:x: - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/13840/)
:white_check_mark: - [Offline-installer Artifact Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-offline-installer/482/)
:white_check_mark: - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/2712/)
:white_check_mark: - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/5829/)
:white_check_mark: - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14365/)
#### Failed Tests (2/37223):
- [test_simple_removenode_4](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14365/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/Tests___dtest___test_simple_removenode_4) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_simple_removenode_4)
- [test_simple_removenode_4](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14365/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/Tests___dtest___test_simple_removenode_4_2) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_simple_removenode_4)
#### Build Details:
- Duration: 5 hr 4 min
- Builder: spider5.cloudius-systems.com

2025-01-12 07:07 UTC, bhalevy commented
> #### 🔴 CI State: FAILURE
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14365/) ✅ - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14365/) **The following new/updated tests ran 100 times for each mode:** 🔹 boost/schema_change_test ✅ - [Docker Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-docker/1080/) ❌ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/13840/) ✅ - [Offline-installer Artifact Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-offline-installer/482/) ✅ - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/2712/) ✅ - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/5829/) ✅ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14365/)
> 
> #### Failed Tests (2/37223):
> * [test_simple_removenode_4](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14365/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/Tests___dtest___test_simple_removenode_4) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_simple_removenode_4)
> * [test_simple_removenode_4](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14365/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/Tests___dtest___test_simple_removenode_4_2) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_simple_removenode_4)

https://github.com/scylladb/scylladb/issues/20814

@scylladb/scylla-maint it looks like ci is unstable and fails on unrelated stuff.
If @avikivity has no objection I think we can consider merging this change

2025-01-12 07:50 UTC, mykaul commented
> > #### 🔴 CI State: FAILURE
> > ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14365/) ✅ - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14365/) **The following new/updated tests ran 100 times for each mode:** 🔹 boost/schema_change_test ✅ - [Docker Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-docker/1080/) ❌ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/13840/) ✅ - [Offline-installer Artifact Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-offline-installer/482/) ✅ - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/2712/) ✅ - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/5829/) ✅ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14365/)
> > #### Failed Tests (2/37223):
> > 
> > * [test_simple_removenode_4](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14365/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/Tests___dtest___test_simple_removenode_4) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_simple_removenode_4)
> > * [test_simple_removenode_4](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14365/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/Tests___dtest___test_simple_removenode_4_2) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_simple_removenode_4)
> 
> #20814
> 
> @scylladb/scylla-maint it looks like ci is unstable and fails on unrelated stuff. If @avikivity has no objection I think we can consider merging this change

Actually, we are in merge freeze until we resolve the CI instability.
I am in favor of removing this test (CC @temichus , @kostja ) until we stabilize it.

2025-01-12 08:53 UTC, avikivity commented
> > #### 🔴 CI State: FAILURE
> > ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14365/) ✅ - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14365/) **The following new/updated tests ran 100 times for each mode:** 🔹 boost/schema_change_test ✅ - [Docker Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-docker/1080/) ❌ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/13840/) ✅ - [Offline-installer Artifact Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-offline-installer/482/) ✅ - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/2712/) ✅ - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/5829/) ✅ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14365/)
> > 
> > #### Failed Tests (2/37223):
> > * [test_simple_removenode_4](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14365/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/Tests___dtest___test_simple_removenode_4) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_simple_removenode_4)
> > * [test_simple_removenode_4](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14365/testReport/junit/update_cluster_layout_tests/TestUpdateClusterLayout/Tests___dtest___test_simple_removenode_4_2) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_simple_removenode_4)
> 
> https://github.com/scylladb/scylladb/issues/20814
> 
> @scylladb/scylla-maint it looks like ci is unstable and fails on unrelated stuff.
> If @avikivity has no objection I think we can consider merging this change

Adding more stuff while we're in broken state is a good way to guarantee we'll never get out

2025-01-12 09:42 UTC, temichus commented
@mykaul what do you mean uder CI instability? Because this test failed 2 times(2d ago and 3d ago) with the same issue and test even in name has word "simple" so it
probably should be simple and stable. 

Test failed on teardown with "AssertionError: Unexpected errors found:
node2: 1 errors
ERROR 2025-01-08 13:39:52,840 [shard 0:main] init - Startup failed: raft::commit_status_unknown (Commit status of the entry is unknown)"

@bhalevy should test expect this error ad start or this is an issue?

2025-01-12 11:01 UTC, bhalevy commented
> @mykaul what do you mean uder CI instability? Because this test failed 2 times(2d ago and 3d ago) with the same issue and test even in name has word "simple" so it probably should be simple and stable.
> 
> Test failed on teardown with "AssertionError: Unexpected errors found: node2: 1 errors ERROR 2025-01-08 13:39:52,840 [shard 0:main] init - Startup failed: raft::commit_status_unknown (Commit status of the entry is unknown)"
> 
> @bhalevy should test expect this error ad start or this is an issue?

As @kbr-scylla wrote in https://github.com/scylladb/scylladb/issues/20814#issue-2547711683:
> The attempt to become a voter failed with commit_status_unknown. This could happen due to internal behaviors of raft algorithm: for example, a concurrent leader change. But we should not leak commit_status_unknown to the user.

Maybe we can just ignore this error in the test for now to hide the issue from ci, but then it might never get fixed.
I'll defer that decision to @kbr-scylla.

2025-01-14 15:41 UTC, kbr-scylla commented
Fix is currently in review: https://github.com/scylladb/scylladb/pull/22253

2025-01-14 22:02 UTC, scylladb-promoter commented
#### :red_circle: CI State: FAILURE

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14457/)
:x: - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14457/)
**The following new/updated tests ran 100 times for each mode:**
:small_blue_diamond: boost/schema_change_test
#### Build Details:
- Duration: 4 hr 22 min
- Builder: i-05d5d81630ff67e25 (m5ad.8xlarge)

2025-01-15 12:10 UTC, bhalevy commented
> #### 🔴 CI State: FAILURE
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14457/) ❌ - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14457/) **The following new/updated tests ran 100 times for each mode:** 🔹 boost/schema_change_test

Unrelated: https://github.com/scylladb/scylladb/issues/22243

2025-01-16 05:10 UTC, denesb commented
Re-kicked CI.

2025-01-16 08:46 UTC, scylladb-promoter commented
#### :red_circle: CI State: FAILURE

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14500/)
:x: - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14500/)
**The following new/updated tests ran 100 times for each mode:**
:small_blue_diamond: boost/schema_change_test
#### Build Details:
- Duration: 3 hr 36 min
- Builder: i-083796b027cf6bcd3 (m5ad.8xlarge)

2025-01-16 08:51 UTC, denesb commented
This PR consistently makes `schema_change_test` fail, we have to fix the test before merging this PR.

2025-01-16 08:52 UTC, denesb commented
> This PR consistently makes `schema_change_test` fail, we have to fix the test before merging this PR.

Or is this another case of running the test 100X will fail due to a flaky test at least once?

2025-01-16 09:05 UTC, mykaul commented
> > This PR consistently makes `schema_change_test` fail, we have to fix the test before merging this PR.
> 
> Or is this another case of running the test 100X will fail due to a flaky test at least once?

But this means we do not wish to get this PR in without fixing (deflaking) the test. This is a good indication.

2025-01-16 12:14 UTC, mykaul commented
CC @yaronkaikov - please see why we did not get a comment on the failures above.

2025-01-16 12:28 UTC, bhalevy commented
> > This PR consistently makes `schema_change_test` fail, we have to fix the test before merging this PR.
> 
> Or is this another case of running the test 100X will fail due to a flaky test at least once?

It's #22243 again, due to running 100 times because of changes in the area in this PR

The good news is that I submitted a fix today (https://github.com/scylladb/scylladb/pull/22339)

2025-01-19 12:15 UTC, mykaul commented
@scylladb/scylla-maint - please review for merge. The failing test has a fix en route, but is unrelated to this PR. @bhalevy - please post the PR for the test fix here as well.

2025-01-20 09:45 UTC, dani-tweig commented
@denesb, can you have a look, please?

2025-01-20 15:09 UTC, nyh requested changes
Looks good to me, just please undo the incorrect "fix" to one of the documents.

2025-01-20 15:09 UTC, nyh commented on docs/architecture/sstable/sstable2/sstable-interpretation.rst
> +potentially multiple sstables.
This change is wrong :-( This document talks about sstables and memtables - not the "in memory tables" that your patch is about.

2025-01-20 15:10 UTC, nyh commented
Looks like @denesb beat me to the race :-) Please fix the document as a follow up patch.

2025-01-22 06:53 UTC, closed without merging

2025-01-23 09:50 UTC, bhalevy commented on docs/architecture/sstable/sstable2/sstable-interpretation.rst
> +potentially multiple sstables.
Yeah, you're right.
OTOH memtables are irrelevant in the context of this paragraph, so the change isn't that bad either.
For completeness, the process of integrating mutations from multiple readers, including SSTables, memtable, and cache, should be documented elsewhere.