treewide: migrate from boost::adaptors::reversed to std::views::reverse
scylladb/scylladb pull request #22083
Opened 2024-12-31 06:45 UTC by tchaikov

now that we are allowed to use C++23. we now have the luxury of using `std::views::reverse`.

- replace `boost::adaptors::transformed` with `std::views::transform`
- remove unused `#include <boost/range/adaptor/reversed.hpp>`

this change is part of our ongoing effort to modernize our codebase and reduce external dependencies where possible.

---

it's a cleanup, hence no need to backport.

2025-01-01 08:18 UTC, scylladb-promoter commented
#### :red_circle: CI State: FAILURE

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14152/)
:x: - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14152/)
**The following new/updated tests ran 100 times for each mode:**
:small_blue_diamond: boost/cql_query_test
#### Build Details:
- Duration: 42 min
- Builder: spider2.cloudius-systems.com

2025-01-03 01:42 UTC, tchaikov commented
> #### 🔴 CI State: FAILURE
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14152/) ❌ - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14152/) **The following new/updated tests ran 100 times for each mode:** 🔹 boost/cql_query_test
> 


both CI run failed like

```
16:13:32  + bash -c 'set -o pipefail; ./tools/toolchain/dbuild -e ENABLE_KMS_TEST=1 -e ENABLE_GCP_TEST=1 -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e GCP_USER_1_CREDENTIALS=$GCP_USER_1_CREDENTIALS -v $GCP_USER_1_CREDENTIALS:$GCP_USER_1_CREDENTIALS -e GCP_USER_2_CREDENTIALS=$GCP_USER_2_CREDENTIALS -v $GCP_USER_2_CREDENTIALS:$GCP_USER_2_CREDENTIALS -v `pwd`:/scylladir -v /jenkins/coredumps:/jenkins/coredumps -- ./test.py  --tmpdir=/scylladir/testlog/x86_64 --artifacts_dir_url https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14152/artifact --verbose --repeat 10 "boost/cql_query_test::*" --no-gather-metrics 2>&1 | tee tests_console_output_x86_64.txt'
16:13:32  Test boost/cql_query_test::* not found
```

#22086

2025-01-03 08:41 UTC, scylladb-promoter commented
#### :red_circle: CI State: ABORTED

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14197/)
:x: - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14197/)
**The following new/updated tests ran 100 times for each mode:**
:small_blue_diamond: boost/cql_query_test
#### Build Details:
- Duration: 46 min
- Builder: spider2.cloudius-systems.com

2025-01-03 08:46 UTC, scylladb-promoter commented
#### :red_circle: CI State: FAILURE

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14198/)
:x: - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14198/)
**The following new/updated tests ran 100 times for each mode:**
:small_blue_diamond: boost/cql_query_test
#### Build Details:
- Duration: 45 min
- Builder: spider1.cloudius-systems.com

2025-01-06 13:58 UTC, tchaikov commented
> #### 🔴 CI State: FAILURE
> 
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14198/) ❌ - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14198/) **The following new/updated tests ran 100 times for each mode:** 🔹 boost/cql_query_test
> #### Build Details:
> 
>     * Duration: 45 min
> 
```
16:41:05  + bash -c 'set -o pipefail; ./tools/toolchain/dbuild -e ENABLE_KMS_TEST=1 -e ENABLE_GCP_TEST=1 -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e GCP_USER_1_CREDENTIALS=$GCP_USER_1_CREDENTIALS -v $GCP_USER_1_CREDENTIALS:$GCP_USER_1_CREDENTIALS -e GCP_USER_2_CREDENTIALS=$GCP_USER_2_CREDENTIALS -v $GCP_USER_2_CREDENTIALS:$GCP_USER_2_CREDENTIALS -v `pwd`:/scylladir -v /jenkins/coredumps:/jenkins/coredumps -- ./test.py  --tmpdir=/scylladir/testlog/x86_64 --artifacts_dir_url https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14198/artifact --verbose --repeat 10 "boost/cql_query_test::*" --no-gather-metrics 2>&1 | tee tests_console_output_x86_64.txt'
16:41:05  Test boost/cql_query_test::* not found
```

#22086

2025-01-06 21:39 UTC, scylladb-promoter commented
#### :green_circle: CI State: SUCCESS

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14238/)
:white_check_mark: - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14238/)
**The following new/updated tests ran 100 times for each mode:**
:small_blue_diamond: boost/cql_query_test
:white_check_mark: - [Docker Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-docker/1000/)
:white_check_mark: - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/2632/)
:white_check_mark: - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/5745/)
:white_check_mark: - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/13758/)
:white_check_mark: - [Offline-installer Artifact Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-offline-installer/404/)
:white_check_mark: - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14238/)
#### Build Details:
- Duration: 7 hr 43 min
- Builder: i-0fcb30751fb5d4aca (m5d.8xlarge)

2025-01-08 07:36 UTC, denesb requested changes
LGTM, but please fix the commit-log.

2025-01-08 07:36 UTC, denesb commented on compaction/size_tiered_compaction_strategy.cc
>  #include "size_tiered_compaction_strategy.hh"
Commitlog talks about replacing boost::adaptors::transformed.

2025-01-08 07:45 UTC, tchaikov commented
v2:

- correct the copy-pasta in commit message.

2025-01-08 18:49 UTC, scylladb-promoter commented
#### :red_circle: CI State: FAILURE

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14296/)
:white_check_mark: - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14296/)
**The following new/updated tests ran 100 times for each mode:**
:small_blue_diamond: boost/cql_query_test
:white_check_mark: - [Docker Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-docker/1039/)
:white_check_mark: - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/13797/)
:white_check_mark: - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/2669/)
:white_check_mark: - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/5784/)
:white_check_mark: - [Offline-installer Artifact Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-offline-installer/441/)
:x: - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14296/)
#### Failed Tests (1/38142):
- [test_view_build_status_cleanup_on_remove_node.release.1](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14296/testReport/junit/topology_custom/test_view_build_status/Tests___Unit_Tests___test_view_build_status_cleanup_on_remove_node_release_1) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_view_build_status_cleanup_on_remove_node.release.1)
#### Build Details:
- Duration: 10 hr
- Builder: i-0010262a4244dff4c (m5ad.8xlarge)

2025-01-10 02:35 UTC, tchaikov commented
> #### 🔴 CI State: FAILURE
> 
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14296/) ✅ - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14296/) **The following new/updated tests ran 100 times for each mode:** 🔹 boost/cql_query_test ✅ - [Docker Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-docker/1039/) ✅ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/13797/) ✅ - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/2669/) ✅ - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/5784/) ✅ - [Offline-installer Artifact Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-offline-installer/441/) ❌ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14296/)
> #### Failed Tests (1/38142):
> 
>     * [test_view_build_status_cleanup_on_remove_node.release.1](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14296/testReport/junit/topology_custom/test_view_build_status/Tests___Unit_Tests___test_view_build_status_cleanup_on_remove_node_release_1) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_view_build_status_cleanup_on_remove_node.release.1)
> 
> 

#21628

2025-01-10 09:21 UTC, scylladb-promoter commented
#### :green_circle: CI State: SUCCESS

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14362/)
:white_check_mark: - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14362/)
**The following new/updated tests ran 100 times for each mode:**
:small_blue_diamond: boost/cql_query_test
:white_check_mark: - [Docker Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-docker/1076/)
:white_check_mark: - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/2707/)
:white_check_mark: - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/13835/)
:white_check_mark: - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/5822/)
:white_check_mark: - [Offline-installer Artifact Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-offline-installer/478/)
:white_check_mark: - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14362/)
#### Build Details:
- Duration: 5 hr 33 min
- Builder: spider8.cloudius-systems.com

2025-01-14 08:17 UTC, denesb commented
Closed by 353b522ca0.
Somehow the commit didn't get the appropriate `Closes` tag.

2025-01-14 08:17 UTC, closed without merging