Add per-table schema hints
scylladb/scylladb pull request #22090
Opened 2024-12-31 17:19 UTC by bhalevy

This series adds a schema extension for per-table hints.
To be used for tablet allocation on table creation and for split/merge decisions
as the table size changes or more tables are created or dropped - affecting the total number
of tablet replicas per shard.

* New feature, no backport required

2025-01-02 10:46 UTC, mykaul commented
If 'initial' is deprecated, it should be removed from the docs (ddl.rst)

2025-01-02 11:37 UTC, bhalevy commented
> If 'initial' is deprecated, it should be removed from the docs (ddl.rst)

Good question whether is should be removed or just be documented as deprecated.
@annastuchlik what do we usually do in these cases?

2025-01-02 11:40 UTC, bhalevy commented
@tgrabiec one more thing we may want to do is to set min_tablet-count on newly created tables if no other hint is given and the keyspace already has initial_tablets > 0, and maybe also scrub existing tables and set their hint respectively, so that we'll be able to drop support for the the keyspace option in the future, and entirely remove it from the documentation .

2025-01-02 18:59 UTC, raphaelsc commented on docs/cql/ddl.rst
> +                                                It can be set when the table is created to allocate more tablets for it,
you meant the number of tablet replicas, since number of tablets isn't influenced by replication factor.

2025-01-02 19:03 UTC, raphaelsc commented on docs/cql/ddl.rst
> +                                                tablet allocation algorithm should give it higher priority for balancing its tablets.
shouldn't this be shares instead? a binary prevents the possibility of declaring different degrees of hotness. it can become a escape hatch (setting statically) once we have shares calculated dynamically by the balancer.

2025-01-02 19:50 UTC, raphaelsc commented on docs/cql/ddl.rst
> +                                                It can be set when the table is created to allocate more tablets for it,
on a second thought, the description should focus that this controls the number of tablets, not tablet replicas, since the size hint is not the total replicated size. so I'd leave topology out of the description.

2025-01-03 03:31 UTC, bhalevy commented on docs/cql/ddl.rst
> +                                                tablet allocation algorithm should give it higher priority for balancing its tablets.
We discussed having shares as a measure, but it seems more complicated for the user.

Need be, min_per_shard_tablet_count can be used, and it is very similar to shares, just that the maximum number (100) is clearer and would be configurable, even per node, to accommodate heterogeneous nodes with different-capacity shards

2025-01-03 14:36 UTC, tgrabiec commented on docs/cql/ddl.rst
> +                                                of nodes their shards in the datacanter.  It is recommended to use higher-level hints
of nodes their shards -> of nodes and shards ?

2025-01-03 14:36 UTC, tgrabiec commented on docs/cql/ddl.rst
> +                                                The hint is backward compatible with the deprecated keyspace ``initial`` tablets option.
I have doubts whether it should be equivalent to the old `initial` option. Currently, the `initial` option suppresses automatic choice (10 tablets/shard). With `min_tablet_count`, it won't suppress the default `min_per_shard_tablet_count`, it may only bump the count higher. In that case for true compatibility, we would need another per-table `initial_tablet_count` option, which suppresses defaults.

2025-01-05 07:57 UTC, bhalevy commented on db/table_hints.cc
> +                // leave unset
My thinking was that we could have hot_table=false mean it's a cold table, vs. unset meaning normal temperature, but I'm not sure we need this.

Based on @mykaul's input, I'll remove this hint for now, for brevity, and we'll reconsider it in a followup change.

2025-01-05 07:57 UTC, bhalevy commented on db/table_hints.hh
> +    std::optional<ssize_t> min_per_shard_tablet_count;
good idea

2025-01-05 08:00 UTC, bhalevy commented on db/table_hints_extension.hh
> +class table_hints_extension : public schema_extension {
Can rename to `tablet_hints`.
I don't like the idea of regular, independent properties as it will require to extend the schema of schema_tables, no?
If we bundle all hints related to tablet allocation in `tablet_hints` it makes sense to set and alter all of them together since they are not truly independent of each other (like we consider the maximum of per-shard tablet count).

2025-01-05 08:02 UTC, bhalevy commented on docs/cql/ddl.rst
> +                                                determine the minimum number of tablets to allocate for the table.
> It's unclear how replication factor and topology is a factor here. Is this size the size before replication?

Yes, it is.

> If so, then this option wants `tablet count = std::ceil(expected_data_size_in_gb * gb / target_tablet_size_in_bytes)`. We should clarify if it's before replication or with replication. The actual tablet count also depends on other factors and options, but we can just mention that this option gives a hint for how many tablets may be needed due to anticipated table size.

sure, will clarify that.

2025-01-05 08:02 UTC, bhalevy commented on docs/cql/ddl.rst
> +                                                tablet allocation algorithm should give it higher priority for balancing its tablets.
Will be dropped in the next version and be reconsidered in a followup change.

2025-01-05 08:06 UTC, bhalevy commented on docs/cql/ddl.rst
> +                                                of nodes their shards in the datacanter.  It is recommended to use higher-level hints
np

2025-01-05 08:07 UTC, bhalevy commented on docs/cql/ddl.rst
> +                                                The hint is backward compatible with the deprecated keyspace ``initial`` tablets option.
> I have doubts whether it should be equivalent to the old initial option. Currently, the initial option suppresses automatic choice (10 tablets/shard). With min_tablet_count, it won't suppress the default min_per_shard_tablet_count, it may only bump the count higher.

That's a good question.  Why shouldn't it override the default min_per_shard_tablet_count?

> In that case for true compatibility, we would need another per-table initial_tablet_count option, which suppresses defaults.

I'm not sure we should go there.
We can also soften the text to say "based on" rather than "backward compatible" to make room for slight incompatibilities.

2025-01-05 18:03 UTC, bhalevy commented
In v2 (f73bba9):
- Renamed `table_hints` to `tablet_hints`
- Dropped `hot_table` hint
- db: add per-table tablet_hints schema extension
  - Described in more details in commit message
- cql3/create_keyspace_statement: add deprecation warning for initial tablets
  - warn only if initial_tablets != 0
- cql3: data_dictionary: format keyspace_metadata: print "enabled":true when initial_tablets=0
- network_topology_strategy: allocate_tablets_for_new_table: consider tablet hints

2025-01-05 18:04 UTC, scylladb-promoter commented
## Docs Preview :book:
Docs Preview for this pull request is available [here](http://previews.docs.scylladb.com/scylladb/22090)

**Changed Files:**
- [cql/ddl](http://previews.docs.scylladb.com/scylladb/22090/cql/ddl)

**Note:** This preview will be available for 30 days and will be automatically deleted after that period. You can manually trigger a new build by committing changes.

2025-01-05 18:17 UTC, nyh commented on test/cqlpy/test_describe.py
> +def test_desc_table(cql, test_keyspace, random_seed, has_tablets, with_tablet_hints:bool):
I am not thrilled with the dtest-like tests that test everything in one function. 
When you add a new feature ("tablet hints"), I think you should usuallly leave the existing tests alone and create a new test specifically for the new feature. The new test doesn't need to copy _everything_ that the previous test had - it can check just the tablet hints and nothing else.

2025-01-05 18:17 UTC, nyh commented on test/cqlpy/test_describe.py
> +                raise
Please reconsider this change. pytest already shows stack traces beautifully, you shouldn't need to do things like this...

2025-01-05 18:17 UTC, nyh commented on test/cqlpy/test_describe.py
> +            assert tbl_row == new_tbl_row, f"\nold {tbl_row=}\n{new_tbl_row=}"
Also, this change reminds me of Boost tests, not pytest's beautiful "assert rewriting" feature where if tbl_row != new_tbl_row the assert prints out nicely the two values, and even better - if they are long arrays or something, shows exactly where they differ. There is almost never a need to add these "explanation strings" in pytest, and usually (and I think also here) they just add confusion.

2025-01-05 18:17 UTC, nyh commented on test/cqlpy/test_tablets.py
> +    ksdef = "WITH REPLICATION = {'class': 'NetworkTopologyStrategy', 'replication_factor': 1} AND TABLETS = {'enabled': false};"
Please add a comment in front of this test, or in front of this line, explaining what it's trying to. It left me confused - this lines says that tablets are NOT enabled. So what do "tablet hints" do here, and why?

2025-01-05 18:17 UTC, nyh commented on test/cqlpy/test_tablets.py
> +            tablet_hints = "tablet_hints = {'min_per_shard_tablet_count': '3.14'}"
The per_shard_tablet_count is allowed to be a floating point? Is this intentional?

2025-01-06 07:08 UTC, scylladb-promoter commented
#### :red_circle: CI State: FAILURE

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14223/)
:white_check_mark: - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14223/)
**The following new/updated tests ran 100 times for each mode:**
:small_blue_diamond: boost/network_topology_strategy_test
:small_blue_diamond: boost/token_metadata_test
:white_check_mark: - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/13745/)
:white_check_mark: - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/2619/)
:white_check_mark: - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/5732/)
:white_check_mark: - [Docker Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-docker/988/)
:white_check_mark: - [Offline-installer Artifact Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-offline-installer/392/)
:x: - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14223/)
#### Failed Tests (1/35663):
- [scylla_gdb.run.release.3](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14223/testReport/junit/%28root%29/non-boost%20tests/Tests___Unit_Tests___scylla_gdb_run_release_3) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+scylla_gdb.run.release.3)
#### Build Details:
- Duration: 13 hr
- Builder: spider8.cloudius-systems.com

2025-01-06 08:37 UTC, bhalevy commented on docs/cql/ddl.rst
> +                                                of nodes their shards in the datacanter.  It is recommended to use higher-level hints
fixed in v2

2025-01-06 08:38 UTC, bhalevy commented on test/cqlpy/test_describe.py
> +def test_desc_table(cql, test_keyspace, random_seed, has_tablets, with_tablet_hints:bool):
can do

2025-01-06 08:39 UTC, bhalevy commented on test/cqlpy/test_describe.py
> +                raise
I did this since this default stack trace was confusing, but I can revert his hunk.
It was needed for debugging

2025-01-06 08:41 UTC, bhalevy commented on test/cqlpy/test_describe.py
> +            assert tbl_row == new_tbl_row, f"\nold {tbl_row=}\n{new_tbl_row=}"
The default assertion failure message wasn't satisfactory for debugging as it hid some details, hence I added the detailed message.  It's not required when everything passes but it improves debuggability when needed.

2025-01-06 08:42 UTC, bhalevy commented on test/cqlpy/test_tablets.py
> +    ksdef = "WITH REPLICATION = {'class': 'NetworkTopologyStrategy', 'replication_factor': 1} AND TABLETS = {'enabled': false};"
sure

2025-01-06 08:53 UTC, nyh commented on test/cqlpy/test_describe.py
> +            assert tbl_row == new_tbl_row, f"\nold {tbl_row=}\n{new_tbl_row=}"
By "hid some details" I'm guessing you mean that when the two compared values are long arrays, pytest makes an effort to show you exactly which parts of the array differ, and doesn't show you the entire array by default. However, you'll probably notice that when pytest does this it tells you that you can use the "-vv" pytest option to avoid this shortening. So this is exactly what you should do :-) (if your favorite script to run pytest tests doesn't let you pass "-vv", fix that script).

When I started to use pytest, the ease of use and power of its assertion system blew me away. It was a generation ahead of anything we had in Boost or other frameworks we used in Scylla in the past. You just write "assert a=b" and pytest will tell you exactly where and why this assertion failed - even if a and b are complicated objects, and even if the assertion happened in some convenience function. In almost all cases, no simply no need for the "old style" techniques like hand-writing failure message or creating special-purpose comparison functions. We should embrace this convenience. It also makes tests easier to read - in more than one occasion in the past I saw an assertion which seemed to check one thing but the textual message suggested it was checking something else :-)

2025-01-06 08:56 UTC, nyh commented on test/cqlpy/test_tablets.py
> +            tablet_hints = "tablet_hints = {'min_per_shard_tablet_count': '3.14'}"
Maybe you can add a comment saying you're intentionally checking that floating numbers work, to reduce surprise in whoever reads this test in the future.

To be honest, I still don't know what  a minimum of 3.14 tablets per shard actually means :-( Would 3 tablets be allowed on some shard, or it has to be higher than 3.14 so needs to be 4 tablets?

2025-01-06 08:58 UTC, nyh commented on test/cqlpy/test_describe.py
> +                raise
It was "confusing" because it was missing information, or because you're just not used to it?

If it's the latter, we don't need this change. Future developers who look at this test will not necessarily need to debug failures in this specific spot, and wherever the failure happens to be, hopefully pytest's stack trace will be good enough.

2025-01-06 09:11 UTC, bhalevy commented on test/cqlpy/test_tablets.py
> +    ksdef = "WITH REPLICATION = {'class': 'NetworkTopologyStrategy', 'replication_factor': 1} AND TABLETS = {'enabled': false};"
Hmm, that's actually a bug, I think.
tablet_hints should be rejected when tablets are disabled for the keyspace.
To enable them, one has to enable tablets for the keyspace.

2025-01-06 10:09 UTC, bhalevy commented on test/cqlpy/test_tablets.py
> +    ksdef = "WITH REPLICATION = {'class': 'NetworkTopologyStrategy', 'replication_factor': 1} AND TABLETS = {'enabled': false};"
fixed in v3, add a separate negative test

2025-01-06 10:10 UTC, bhalevy commented
In v3 ([81260c8](https://github.com/scylladb/scylladb/commit/81260c8f26eb7e4cc7667373a465a701958fa83c)):
- Added validation for tablet_hints in cf_prop_defs to reject if tablets are disabled for the keyspace
- Fixed review comments for unit test
- Fixed review comments for documentation

2025-01-06 10:10 UTC, bhalevy commented on db/table_hints.hh
> +    std::optional<ssize_t> min_per_shard_tablet_count;
Fixed in v2

2025-01-06 10:11 UTC, bhalevy commented on db/table_hints_extension.hh
> +class table_hints_extension : public schema_extension {
Renamed to tablet_hints in v2

2025-01-06 10:11 UTC, bhalevy commented on docs/cql/ddl.rst
> +                                                determine the minimum number of tablets to allocate for the table.
Fixed in v3

2025-01-06 10:11 UTC, bhalevy commented on docs/cql/ddl.rst
> +                                                It can also be used later in the tablet life cycle to induce tablet splits or merges
Fixed in v3

2025-01-06 10:11 UTC, bhalevy commented on test/cqlpy/test_describe.py
> +def test_desc_table(cql, test_keyspace, random_seed, has_tablets, with_tablet_hints:bool):
Fixed in v3

2025-01-06 10:11 UTC, bhalevy commented on test/cqlpy/test_describe.py
> +                raise
Dropped in v3

2025-01-06 10:12 UTC, bhalevy commented on test/cqlpy/test_describe.py
> +            assert tbl_row == new_tbl_row, f"\nold {tbl_row=}\n{new_tbl_row=}"
Dropped in v3.
Separated new test case and made it focus only on tablet_hints, validated only via DESC TABLE

2025-01-06 14:31 UTC, scylladb-promoter commented
#### :red_circle: CI State: FAILURE

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14230/)
:white_check_mark: - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14230/)
**The following new/updated tests ran 100 times for each mode:**
:small_blue_diamond: boost/network_topology_strategy_test
:small_blue_diamond: boost/token_metadata_test
:white_check_mark: - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/2622/)
:white_check_mark: - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/13748/)
:white_check_mark: - [Docker Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-docker/990/)
:white_check_mark: - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/5735/)
:white_check_mark: - [Offline-installer Artifact Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-offline-installer/394/)
:x: - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14230/)
#### Failed Tests (18/35660):
- [test_create_table_in_nonexistent_keyspace.debug.1](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14230/testReport/junit/cqlpy/test_keyspace/Tests___Unit_Tests___test_create_table_in_nonexistent_keyspace_debug_1) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_create_table_in_nonexistent_keyspace.debug.1)
- [test_create_table_in_nonexistent_keyspace.debug.2](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14230/testReport/junit/cqlpy/test_keyspace/Tests___Unit_Tests___test_create_table_in_nonexistent_keyspace_debug_2) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_create_table_in_nonexistent_keyspace.debug.2)
- [test_create_table_in_nonexistent_keyspace.debug.3](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14230/testReport/junit/cqlpy/test_keyspace/Tests___Unit_Tests___test_create_table_in_nonexistent_keyspace_debug_3) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_create_table_in_nonexistent_keyspace.debug.3)
- [test_create_table_in_nonexistent_keyspace.dev.1](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14230/testReport/junit/cqlpy/test_keyspace/Tests___Unit_Tests___test_create_table_in_nonexistent_keyspace_dev_1) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_create_table_in_nonexistent_keyspace.dev.1)
- [test_create_table_in_nonexistent_keyspace.dev.2](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14230/testReport/junit/cqlpy/test_keyspace/Tests___Unit_Tests___test_create_table_in_nonexistent_keyspace_dev_2) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_create_table_in_nonexistent_keyspace.dev.2)
- [test_create_table_in_nonexistent_keyspace.dev.3](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14230/testReport/junit/cqlpy/test_keyspace/Tests___Unit_Tests___test_create_table_in_nonexistent_keyspace_dev_3) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_create_table_in_nonexistent_keyspace.dev.3)
- [test_create_table_in_nonexistent_keyspace.release.1](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14230/testReport/junit/cqlpy/test_keyspace/Tests___Unit_Tests___test_create_table_in_nonexistent_keyspace_release_1) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_create_table_in_nonexistent_keyspace.release.1)
- [test_create_table_in_nonexistent_keyspace.release.2](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14230/testReport/junit/cqlpy/test_keyspace/Tests___Unit_Tests___test_create_table_in_nonexistent_keyspace_release_2) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_create_table_in_nonexistent_keyspace.release.2)
- [test_create_table_in_nonexistent_keyspace.release.3](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14230/testReport/junit/cqlpy/test_keyspace/Tests___Unit_Tests___test_create_table_in_nonexistent_keyspace_release_3) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_create_table_in_nonexistent_keyspace.release.3)
- [cqlpy.test_keyspace.debug.1](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14230/testReport/junit/%28root%29/non-boost%20tests/Tests___Unit_Tests___cqlpy_test_keyspace_debug_1) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+cqlpy.test_keyspace.debug.1)
#### Build Details:
- Duration: 4 hr 9 min
- Builder: spider2.cloudius-systems.com

2025-01-06 14:47 UTC, avikivity commented
The documentation (and changelog) need to explain how conflicts between different hints, and between hints and actual data, are resolved.

2025-01-07 11:53 UTC, tgrabiec commented on db/table_hints_extension.hh
> +class table_hints_extension : public schema_extension {
> Can rename to `tablet_hints`. I don't like the idea of regular, independent properties as it will require to extend the schema of schema_tables, no? 

Yes, but is it a problem? It's definitely more work to wire the options in code, because you have to change the schema builder, cf props, and schema mutation builder.

> If we bundle all hints related to tablet allocation in `tablet_hints` it makes sense to set and alter all of them together since they are not truly independent of each other (like we consider the maximum of per-shard tablet count).

expected table size is independent of hotness / min-tablets-per-shard. After ingestion, the user may want to drop expected size, but preserve other hints.

2025-01-07 12:00 UTC, tgrabiec commented on test/cqlpy/test_tablets.py
> +            tablet_hints = "tablet_hints = {'min_per_shard_tablet_count': '3.14'}"
`min_per_shard_tablet_count` doesn't mean that each shard should have at least that, it means that the average per-shard tablet count is at least that, so it's really `min_avg_per_shard_tablet_count`

2025-01-09 09:22 UTC, bhalevy commented on test/cqlpy/test_tablets.py
> +            tablet_hints = "tablet_hints = {'min_per_shard_tablet_count': '3.14'}"
> `min_per_shard_tablet_count` doesn't mean that each shard should have at least that, it means that the average per-shard tablet count is at least that, so it's really `min_avg_per_shard_tablet_count`

The question then is why the hint needs to be floating point?
Can't the user just provide the std::floor of that average?

2025-01-09 12:38 UTC, bhalevy commented
In v4 ([3dc7da3](https://github.com/scylladb/scylladb/commit/3dc7da3cc0de0a948f5176d655ed151e9004a8ba)):
- rebased
- fixed exception type thrown by cf_prop_defs::validate when keyspace is not found (caused failure in cqlpyt/test_keyspace.py)
- fixed review comments in docs
- improved documentation for hints, including their mutual interaction, and their interaction with the tablet data size.
- added comments to unit tests about floating point min_per_shard_tablet_count

2025-01-09 15:36 UTC, nyh commented on test/cqlpy/test_tablets.py
> +            tablet_hints = "tablet_hints = {'min_per_shard_tablet_count': '3.14'}"
If min_per_shard_tablet_count isn't the minimum, maybe we shouldn't call it that?
This parameter needs to be something that users will be able to understand (and of course be clearly documented).

2025-01-09 21:19 UTC, scylladb-promoter commented
#### :red_circle: CI State: FAILURE

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14339/)
:white_check_mark: - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14339/)
**The following new/updated tests ran 100 times for each mode:**
:small_blue_diamond: boost/network_topology_strategy_test
:small_blue_diamond: boost/token_metadata_test
:white_check_mark: - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/13820/)
:white_check_mark: - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/2692/)
:white_check_mark: - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/5807/)
:white_check_mark: - [Docker Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-docker/1060/)
:white_check_mark: - [Offline-installer Artifact Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-offline-installer/462/)
:x: - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14339/)
#### Failed Tests (5/37060):
- [test_calculate_tablet_replicas_for_new_rf_default_rf_upsize_by_two](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14339/testReport/junit/boost/tablets_test/test_calculate_tablet_replicas_for_new_rf_default_rf_upsize_by_two) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_calculate_tablet_replicas_for_new_rf_default_rf_upsize_by_two)
- [test_calculate_tablet_replicas_for_new_rf_downsize_one_dc](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14339/testReport/junit/boost/tablets_test/test_calculate_tablet_replicas_for_new_rf_downsize_one_dc) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_calculate_tablet_replicas_for_new_rf_downsize_one_dc)
- [test_calculate_tablet_replicas_for_new_rf_no_change_one_dc](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14339/testReport/junit/boost/tablets_test/test_calculate_tablet_replicas_for_new_rf_no_change_one_dc) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_calculate_tablet_replicas_for_new_rf_no_change_one_dc)
- [test_calculate_tablet_replicas_for_new_rf_not_enough_nodes](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14339/testReport/junit/boost/tablets_test/test_calculate_tablet_replicas_for_new_rf_not_enough_nodes) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_calculate_tablet_replicas_for_new_rf_not_enough_nodes)
- [test_calculate_tablet_replicas_for_new_rf_one_dc_not_enough_nodes](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14339/testReport/junit/boost/tablets_test/test_calculate_tablet_replicas_for_new_rf_one_dc_not_enough_nodes) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_calculate_tablet_replicas_for_new_rf_one_dc_not_enough_nodes)
#### Build Details:
- Duration: 8 hr 42 min
- Builder: i-09a417a62a8144d10 (m5ad.8xlarge)

2025-01-09 22:05 UTC, tgrabiec commented on test/cqlpy/test_tablets.py
> +            tablet_hints = "tablet_hints = {'min_per_shard_tablet_count': '3.14'}"
> > `min_per_shard_tablet_count` doesn't mean that each shard should have at least that, it means that the average per-shard tablet count is at least that, so it's really `min_avg_per_shard_tablet_count`
> 
> The question then is why the hint needs to be floating point? Can't the user just provide the std::floor of that average?

The original reasoning still stands: https://github.com/scylladb/scylladb/pull/22090#discussion_r1901760324

2025-01-09 22:07 UTC, tgrabiec commented on test/cqlpy/test_tablets.py
> +            tablet_hints = "tablet_hints = {'min_per_shard_tablet_count': '3.14'}"
> If min_per_shard_tablet_count isn't the minimum, maybe we shouldn't call it that? This parameter needs to be something that users will be able to understand (and of course be clearly documented).

It is a minimum, just for the average. The count and average count per shared can still be higher due than this parameter tells due to other factors, like table size.

2025-01-10 08:36 UTC, bhalevy commented on test/cqlpy/test_tablets.py
> +            tablet_hints = "tablet_hints = {'min_per_shard_tablet_count': '3.14'}"
> The original reasoning still stands: https://github.com/scylladb/scylladb/pull/22090#discussion_r1901760324

Can you please provide an example demonstrating why it is needed and giving an integer (floor) wouldn't work?

2025-01-10 09:04 UTC, tgrabiec commented on test/cqlpy/test_tablets.py
> +            tablet_hints = "tablet_hints = {'min_per_shard_tablet_count': '3.14'}"
tablet_count = min_per_shard_tablet_count * shard_count

shard_count = 100

min_per_shard_tablet_count = 1
tablet_count = 100 (128, nearest pow2)

min_per_shard_tablet_count = 2
tablet_count = 200 (256)

Impossible to achieve tablet count of 64.

With fractions:

min_per_shard_tablet_count = 0.64
tablet_count = 0.64 * 100 = 64

2025-01-10 09:25 UTC, bhalevy commented on test/cqlpy/test_tablets.py
> +            tablet_hints = "tablet_hints = {'min_per_shard_tablet_count': '3.14'}"
ok, I get your point, though one could use min_tablet count for that too.

2025-01-12 18:17 UTC, bhalevy commented
In v5 ([e304453](https://github.com/scylladb/scylladb/commit/e3044536d044de428d6c194ca9bec8e994913c2a)):
- rebased
- consider keyspace initial tablets before hints (addresses unit test failures reported in https://github.com/scylladb/scylladb/pull/22090#issuecomment-2581265777)
- updated documentation
  - regarding initial_tablets
  - and about min_per_shard_tablet_count being floating point

2025-01-12 18:17 UTC, bhalevy commented
@tgrabiec please re-review

2025-01-12 22:52 UTC, scylladb-promoter commented
#### :green_circle: CI State: SUCCESS

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14390/)
:white_check_mark: - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14390/)
**The following new/updated tests ran 100 times for each mode:**
:small_blue_diamond: boost/network_topology_strategy_test
:white_check_mark: - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/2735/)
:white_check_mark: - [Docker Test](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-docker/1100/)
:white_check_mark: - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/13863/)
:white_check_mark: - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/5852/)
:white_check_mark: - [Offline-installer Artifact Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci-offline-installer/503/)
:white_check_mark: - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14390/)
#### Build Details:
- Duration: 4 hr 41 min
- Builder: spider7.cloudius-systems.com

2025-01-13 13:35 UTC, tgrabiec requested changes

2025-01-13 13:35 UTC, tgrabiec commented on cql3/statements/create_keyspace_statement.cc
> +            if (ksm->initial_tablets().value_or(0)) {
Why this change? It seems to have no effect.

2025-01-13 13:35 UTC, tgrabiec commented on locator/tablets.cc
> +        _tablet_hints = params.tablet_hints;
Replication strategy is per keyspace, while tablet hints are per table. So this is not the right place to store he hints. They should be obtained from schema_ptr.

2025-01-13 13:35 UTC, tgrabiec commented on locator/network_topology_strategy.cc
> +        tablet_count = tablet_hints().min_tablet_count.value_or(0);
I think hints should be obtained from "s", since they are per table, not per replication strategy.

2025-01-13 13:35 UTC, tgrabiec commented on locator/network_topology_strategy.cc
> +        tablet_count = std::max<size_t>(tablet_count, calculate_initial_tablets_from_topology(*s, tm, _dc_rep_factor, tablet_hints().min_per_shard_tablet_count.value_or(0)));
initial_scale is ignored after the patch. I think it should not be for backwards compatibility, some tests will use it instead of hints. The way to integrate it is to use the scale if hint is absent (initial scale = default min_per_shard_tablet_count).

2025-01-14 15:18 UTC, bhalevy commented on cql3/statements/create_keyspace_statement.cc
> +            if (ksm->initial_tablets().value_or(0)) {
sorry, leftover from a previous version.
Will clean that up

2025-01-14 15:21 UTC, bhalevy commented on locator/tablets.cc
> +        _tablet_hints = params.tablet_hints;
Isn't the tablet_aware_replication_strategy per table?

2025-01-14 15:25 UTC, bhalevy commented on locator/tablets.cc
> +        _tablet_hints = params.tablet_hints;
But that said, it appears like we can indeed retrieve them from the schema

2025-01-14 15:26 UTC, bhalevy commented on locator/network_topology_strategy.cc
> +        tablet_count = std::max<size_t>(tablet_count, calculate_initial_tablets_from_topology(*s, tm, _dc_rep_factor, tablet_hints().min_per_shard_tablet_count.value_or(0)));
fixed in v6

2025-01-14 15:27 UTC, tgrabiec commented on locator/tablets.cc
> +        _tablet_hints = params.tablet_hints;
replication strategy is instantiated per keyspace. This one extends `per_table_replication_strategy` but it means that each table has its own erm, replication strategy object is still per keyspace.

2025-01-14 16:54 UTC, bhalevy commented on locator/tablets.cc
> +        _tablet_hints = params.tablet_hints;
Dropped in v7

2025-01-14 16:54 UTC, bhalevy commented on locator/network_topology_strategy.cc
> +        tablet_count = tablet_hints().min_tablet_count.value_or(0);
done in v7

2025-01-14 16:54 UTC, bhalevy commented on cql3/statements/create_keyspace_statement.cc
> +            if (ksm->initial_tablets().value_or(0)) {
dropped in v7

2025-01-14 16:55 UTC, bhalevy commented
In v7 ([55be961](https://github.com/scylladb/scylladb/commit/55be9614beedcffc6eaf8c185c08d597162196ea)):
- network_topology_strategy: allocate_tablets_for_new_table: consider tablet hints
  - simplified.  does not touch the replication strategy params
  - getting tablet_hints only from schema
  - dropped extraneous `value_or` hunk
- tablet_allocator: consider tablet_hints for resize decision
  - fixed unit tests by allowing replication strategy to be non tablet_aware (oddly this is possible in the unit test)

2025-01-14 21:09 UTC, bhalevy commented on locator/tablets.cc
> +        _tablet_hints = params.tablet_hints;
> replication strategy is instantiated per keyspace. This one extends `per_table_replication_strategy` but it means that each table has its own erm, replication strategy object is still per keyspace.

I see.  It makes sense, though the name is a bit misleading.  I hope its documented

2025-01-15 04:03 UTC, scylladb-promoter commented
#### :red_circle: CI State: FAILURE

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14454/)
:white_check_mark: - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14454/)
**The following new/updated tests ran 100 times for each mode:**
:small_blue_diamond: boost/network_topology_strategy_test
:white_check_mark: - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/2785/)
:white_check_mark: - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/5905/)
:white_check_mark: - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/13915/)
:x: - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14454/)
#### Failed Tests (2/37088):
- [test_view_build_status_v2_table.release.1](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14454/testReport/junit/topology_custom/test_view_build_status/Tests___Unit_Tests___test_view_build_status_v2_table_release_1) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_view_build_status_v2_table.release.1)
- [test_view_build_status_v2_table.release.1](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14454/testReport/junit/topology_custom/test_view_build_status/Tests___Unit_Tests___test_view_build_status_v2_table_release_1_2) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_view_build_status_v2_table.release.1)
#### Build Details:
- Duration: 11 hr
- Builder: i-007960c1c8bc34de0 (m5ad.8xlarge)

2025-01-15 07:42 UTC, pehala commented
Could we add more unit tests that would test if those hints functionally work?

2025-01-15 11:32 UTC, bhalevy commented
> Could we add more unit tests that would test if those hints functionally work?

Yes, we can and should.
But I'd like to reach agreement with @tgrabiec on the logic first.

2025-01-15 15:04 UTC, tgrabiec requested changes

2025-01-16 07:14 UTC, bhalevy commented on service/tablet_allocator.cc
> +                continue;
Apparently, similar to the replication strategy, it might be missing in boost tests :-(

2025-01-16 09:11 UTC, tgrabiec commented on service/tablet_allocator.cc
> +                continue;
Ah, ok then. But near term we should fix the tests to create proper environment.

2025-01-16 23:43 UTC, scylladb-promoter commented
#### :red_circle: CI State: FAILURE

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14523/)
:white_check_mark: - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14523/)
**The following new/updated tests ran 100 times for each mode:**
:small_blue_diamond: boost/network_topology_strategy_test
:small_blue_diamond: boost/tablets_test
:x: - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/2836/)
:white_check_mark: - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/13963/)
:white_check_mark: - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/5955/)
:white_check_mark: - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14523/)
#### Build Details:
- Duration: 5 hr 42 min
- Builder: spider1.cloudius-systems.com

2025-01-20 05:22 UTC, bhalevy commented
[898a9ae](https://github.com/scylladb/scylladb/commit/898a9ae07b4244a00d82e75c2b5f42a26c4cbb94): rebased

2025-01-20 05:32 UTC, bhalevy commented
> #### 🔴 CI State: FAILURE
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14523/) ✅ - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14523/) **The following new/updated tests ran 100 times for each mode:** 🔹 boost/network_topology_strategy_test 🔹 boost/tablets_test ❌ - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/2836/) ✅ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/13963/) ✅ - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/5955/) ✅ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14523/)

I opened https://github.com/scylladb/scylladb/issues/22394 for the failures above.
I don't understand the root cause yet for those failures and I suspect it is unrelated to this change.
But let's see how the rerun goes after rebase.

2025-01-20 08:11 UTC, denesb requested changes
Please remove accidental `python3` submodule update.

2025-01-20 11:16 UTC, scylladb-promoter commented
#### :red_circle: CI State: FAILURE

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14571/)
:white_check_mark: - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14571/)
**The following new/updated tests ran 100 times for each mode:**
:small_blue_diamond: boost/network_topology_strategy_test
:small_blue_diamond: boost/tablets_test
:x: - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/2888/)
:x: - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/14016/)
:x: - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/6007/)
:x: - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14571/)
#### Failed Tests (36/37910):
- [test_database_with_data_in_sstables_is_a_mutation_source_reverse_fragments_monotonic_cg0](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14571/testReport/junit/boost/database_test/test_database_with_data_in_sstables_is_a_mutation_source_reverse_fragments_monotonic_cg0) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_database_with_data_in_sstables_is_a_mutation_source_reverse_fragments_monotonic_cg0)
- [test_modify_username_on_ldap](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14571/testReport/junit/ldap_test/TestLdap/Tests___dtest___test_modify_username_on_ldap) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_modify_username_on_ldap)
- [test_modify_username_on_ldap](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14571/testReport/junit/ldap_test/TestLdap/Tests___dtest_with_topology_changes___test_modify_username_on_ldap) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_modify_username_on_ldap)
- [test_modify_username_on_ldap](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14571/testReport/junit/ldap_test/TestLdap/Tests___dtest_with_tablets___test_modify_username_on_ldap) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_modify_username_on_ldap)
- [test_multiple_roles_single_permission](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14571/testReport/junit/ldap_test/TestLdap/Tests___dtest_with_topology_changes___test_multiple_roles_single_permission) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_multiple_roles_single_permission)
- [test_multiple_roles_single_permission](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14571/testReport/junit/ldap_test/TestLdap/Tests___dtest___test_multiple_roles_single_permission) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_multiple_roles_single_permission)
- [test_multiple_users_with_modify_role](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14571/testReport/junit/ldap_test/TestLdap/Tests___dtest___test_multiple_users_with_modify_role) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_multiple_users_with_modify_role)
- [test_multiple_users_with_modify_role](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14571/testReport/junit/ldap_test/TestLdap/Tests___dtest_with_tablets___test_multiple_users_with_modify_role) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_multiple_users_with_modify_role)
- [test_multiple_users_with_modify_role](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14571/testReport/junit/ldap_test/TestLdap/Tests___dtest_with_topology_changes___test_multiple_users_with_modify_role) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_multiple_users_with_modify_role)
- [test_partial_permissions](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14571/testReport/junit/ldap_test/TestLdap/Tests___dtest___test_partial_permissions) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_partial_permissions)
#### Build Details:
- Duration: 5 hr 53 min
- Builder: spider4.cloudius-systems.com

2025-01-20 13:44 UTC, bhalevy commented
> Please remove accidental `python3` submodule update.

Removed in rebased version: [451ab07](https://github.com/scylladb/scylladb/commit/451ab07c0ef374be3c63b25846697a1b4860e6f5)

2025-01-20 15:22 UTC, tgrabiec approved these changes

2025-01-21 01:50 UTC, scylladb-promoter commented
#### :red_circle: CI State: FAILURE

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14592/)
:white_check_mark: - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14592/)
**The following new/updated tests ran 100 times for each mode:**
:small_blue_diamond: boost/network_topology_strategy_test
:small_blue_diamond: boost/tablets_test
:x: - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/2899/)
:x: - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/14027/)
:x: - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/6018/)
:white_check_mark: - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14592/)
#### Failed Tests (36/37939):
- [test_partial_permissions](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14592/testReport/junit/ldap_test/TestLdapSaslAuth/Tests___dtest_with_tablets___test_partial_permissions) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_partial_permissions)
- [test_multiple_roles_single_permission](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14592/testReport/junit/ldap_test/TestLdapSaslAuth/Tests___dtest_with_tablets___test_multiple_roles_single_permission) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_multiple_roles_single_permission)
- [test_multiple_users_with_modify_role](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14592/testReport/junit/ldap_test/TestLdapSaslAuth/Tests___dtest_with_tablets___test_multiple_users_with_modify_role) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_multiple_users_with_modify_role)
- [test_user_login_only](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14592/testReport/junit/ldap_test/TestLdap/Tests___dtest_with_tablets___test_user_login_only) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_user_login_only)
- [test_remove_user_from_ldap](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14592/testReport/junit/ldap_test/TestLdapSaslAuth/Tests___dtest_with_tablets___test_remove_user_from_ldap) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_remove_user_from_ldap)
- [test_modify_username_on_ldap](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14592/testReport/junit/ldap_test/TestLdapSaslAuth/Tests___dtest_with_tablets___test_modify_username_on_ldap) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_modify_username_on_ldap)
- [test_partial_permissions](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14592/testReport/junit/ldap_test/TestLdap/Tests___dtest_with_tablets___test_partial_permissions) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_partial_permissions)
- [test_multiple_roles_single_permission](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14592/testReport/junit/ldap_test/TestLdap/Tests___dtest_with_tablets___test_multiple_roles_single_permission) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_multiple_roles_single_permission)
- [test_multiple_users_with_modify_role](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14592/testReport/junit/ldap_test/TestLdap/Tests___dtest_with_tablets___test_multiple_users_with_modify_role) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_multiple_users_with_modify_role)
- [test_remove_user_from_ldap](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14592/testReport/junit/ldap_test/TestLdap/Tests___dtest_with_tablets___test_remove_user_from_ldap) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_remove_user_from_ldap)
#### Build Details:
- Duration: 12 hr
- Builder: i-04f7738d44b3a7e07 (m5ad.8xlarge)

2025-01-21 08:54 UTC, bhalevy commented
v9 ([93a610d](https://github.com/scylladb/scylladb/commit/93a610d98fcb27f2611a343a689eb4de0915e872)):
- rebased
- Fixed invalid_request exception message in cf_prop_defs::find_keyspace to use the `no_such_keyspace` message since the ldap dtests expect this message in the returned error.

2025-01-21 14:44 UTC, scylladb-promoter commented
#### :green_circle: CI State: SUCCESS

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14611/)
:white_check_mark: - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14611/)
**The following new/updated tests ran 100 times for each mode:**
:small_blue_diamond: boost/network_topology_strategy_test
:small_blue_diamond: boost/tablets_test
:white_check_mark: - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/2910/)
:white_check_mark: - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/14038/)
:white_check_mark: - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/6029/)
:white_check_mark: - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14611/)
#### Build Details:
- Duration: 5 hr 51 min
- Builder: spider8.cloudius-systems.com

2025-01-21 20:14 UTC, mykaul commented
@scylladb/scylla-maint please review for merge

2025-01-21 20:18 UTC, tgrabiec commented
> @scylladb/scylla-maint please review for merge

I approved it, but we're in a merge freeze.

2025-01-21 20:29 UTC, pehala commented
> > Could we add more unit tests that would test if those hints functionally work?
> 
> Yes, we can and should. But I'd like to reach agreement with @tgrabiec on the logic first.

I would still like more unit tests for this functionality before merge. I think this feature deserves more functional tests

2025-01-21 21:17 UTC, mykaul commented
> > > Could we add more unit tests that would test if those hints functionally work?
> > 
> > 
> > Yes, we can and should. But I'd like to reach agreement with @tgrabiec on the logic first.
> 
> I would still like more unit tests for this functionality before merge. I think this feature deserves more functional tests

1. A bit late for such a request.
2. Any specific tests in mind?

2025-01-21 21:18 UTC, mykaul commented
> > @scylladb/scylla-maint please review for merge
> 
> I approved it, but we're in a merge freeze.

@avikivity - when can we unfreeze, given we are well aware of the issues (and I've sent PRs to disable some of the constantly failing tests)?

2025-01-21 21:22 UTC, avikivity commented
Having a promotion would be a good start

2025-01-22 07:33 UTC, pehala commented
> * A bit late for such a request.

I made that request a week ago (in this PR) and was told more tests are on the way once the logic stabilizes
> 
> * Any specific tests in mind?

I would like to see testing if the hints have the effect we expect, current tests only verify that they can be set but do not test the loadbalancer functionality at all (e.g. Given we have three tables with specific hints, check if the tablet distribution is correct)

2025-01-23 08:30 UTC, bhalevy commented
> > * A bit late for such a request.
> 
> I made that request a week ago (in this PR) and was told more tests are on the way once the logic stabilizes
> 
> > * Any specific tests in mind?
> 
> I would like to see testing if the hints have the effect we expect, current tests only verify that they can be set but do not test the loadbalancer functionality at all (e.g. Given we have three tables with specific hints, check if the tablet distribution is correct)

Since @tgrabiec's https://github.com/scylladb/scylladb/pull/22024 PR is going to make further changes in this area, I suggest we follow up with the unit test in his PR, otherwise it'll double the work.

2025-01-27 09:49 UTC, denesb commented
> @denesb any changes still requested? (GH marks you as requesting changes)

I don't recall reviewing this PR. For me, the UI shows "Awaiting requested review from denesb".

2025-01-27 09:50 UTC, denesb commented
> > @denesb any changes still requested? (GH marks you as requesting changes)
> 
> I don't recall reviewing this PR. For me, the UI shows "Awaiting requested review from denesb".

Actually, I did request changes: https://github.com/scylladb/scylladb/pull/22090#pullrequestreview-2561625126

2025-01-27 10:17 UTC, bhalevy commented
> > > > @denesb any changes still requested? (GH marks you as requesting changes)
> > > 
> > > 
> > > I don't recall reviewing this PR. For me, the UI shows "Awaiting requested review from denesb".
> > 
> > 
> > Actually, I did request changes: [#22090 (review)](https://github.com/scylladb/scylladb/pull/22090#pullrequestreview-2561625126)
> 
> It seems to be addressed, so I have no objections against merging.

@denesb can you please approve formally to keep github happy?

2025-01-27 10:20 UTC, denesb approved these changes

2025-01-28 09:53 UTC, mykaul commented
@bhalevy - please address feedback from @avikivity (can it be improved in a follow-up patch?).

2025-01-28 19:07 UTC, bhalevy commented
In v10 ([a2d07a0](https://github.com/scylladb/scylladb/commit/a2d07a0c4b26ffce5d9c95f15b073c7e33a89b81)):
- rebased
- moved new schema column holding tablet_hints to `scylla_tables`
- applied also on materialized views
- added `test_tablet_hints_with_view` to verify that tablet_hints are stored on views as well

2025-01-28 19:17 UTC, raphaelsc commented on locator/network_topology_strategy.cc
> +        if (tm->is_normal_token_owner(n.host_id())) {
tm->for_each_token_owner(). translates into the same.

2025-01-28 19:21 UTC, raphaelsc commented on locator/network_topology_strategy.cc
>      }
it's possible for user to specify tablet_count of 0, feed hints, and expect automatic calculation to still take hints into account, no? so shouldn't we still take the maximum above when tablet_count equals 0?

2025-01-28 19:33 UTC, raphaelsc commented on service/tablet_allocator.cc
> +
I guess the global decision that might want to bypass this limit in order to respect per-shard limit will be addressed by Tomek's work.

2025-01-28 19:36 UTC, raphaelsc commented on service/tablet_allocator.cc
>              };
I guess this min_tablet_count of 1 is needed to satisfy existing split / merge tests.

We need to write tests to stress the new heuristic.

2025-01-28 19:51 UTC, avikivity commented
The cover letter is now incorrect.

The subject could be more specific too, it's about tablet counts, not random schema hints.

2025-01-28 19:52 UTC, avikivity commented on cql3/statements/cf_prop_defs.cc
> +const sstring cf_prop_defs::KW_TABLET_HINTS = "tablet_hints";
It can be "tablets =", and we can gather everything tablet related there.

2025-01-28 19:53 UTC, avikivity commented on cql3/statements/cf_prop_defs.cc
> +        KW_SYNCHRONOUS_UPDATES, KW_TABLET_HINTS,
Like we don't have COMPACTION_HINTS, but COMPACTION.

2025-01-28 19:56 UTC, avikivity commented on db/schema_tables.cc
>      // Writing it here breaks upgrade rollback to versions that do not support the in_memory schema_feature
Comment looks misplaced now.

2025-01-28 19:56 UTC, avikivity commented on db/schema_tables.cc
> +    }
What if the column isn't there?

2025-01-28 20:06 UTC, avikivity commented on locator/tablets.hh
Why do we need to compare these structs to themselves?

2025-01-28 20:12 UTC, avikivity commented on service/tablet_allocator.cc
> +            }
This can't be correct. Merge and split are not symmetric.

It's hard to follow the logic of tablet_count_from_size, it changes meaning if we're below or above.

I suggest to keep the original logic.

2025-01-28 20:13 UTC, avikivity commented on service/tablet_allocator.cc
> +            // FIXME: the table or the replication_strategy might be missing in boost unit tests
What does this mean?

2025-01-28 20:14 UTC, avikivity commented on service/tablet_allocator.cc
> +            }
So the tests allow things that cause a crash in real life?

2025-01-28 20:15 UTC, raphaelsc commented on service/tablet_allocator.cc
> +            }
I agree. It took my some time to figure out what tablet_count_from_size means. It actually means target_tablet_count.

2025-01-28 20:39 UTC, tgrabiec commented on locator/tablets.hh
So that variant<>::operator==() is defined.

2025-01-28 21:10 UTC, bhalevy commented on locator/network_topology_strategy.cc
>      }
> it's possible for user to specify tablet_count of 0

You mean as keyspace `initial` tablet count?
This is processed on the first statement: `tablet_count = get_initial_tablets()`

> feed hints, and expect automatic calculation to still take hints into account, no? so shouldn't we still take the maximum above when tablet_count equals 0?

We do. `tablet_count` in this expression is the automatic variable in this function which is the maximum of all conditions.
This particular block calls `calculate_initial_tablets_from_topology`, which is the automatic calculation in the absence of other hints (initial tablets on keyspace and per-table hints)

2025-01-28 21:11 UTC, bhalevy commented on service/tablet_allocator.cc
> +
it should. @tgrabiec?

2025-01-28 21:12 UTC, bhalevy commented on service/tablet_allocator.cc
>              };
tablet_count for a table must be greater than or equal to 1.

2025-01-28 21:12 UTC, bhalevy commented on cql3/statements/cf_prop_defs.cc
> +const sstring cf_prop_defs::KW_TABLET_HINTS = "tablet_hints";
Can do

2025-01-28 21:14 UTC, bhalevy commented on cql3/statements/cf_prop_defs.cc
> +        KW_SYNCHRONOUS_UPDATES, KW_TABLET_HINTS,
Right.  The `compaction` properties include the `class` which specifies the compaction strategy and the rest are the compaction strategy options.

2025-01-28 21:14 UTC, bhalevy commented on db/schema_tables.cc
>      // Writing it here breaks upgrade rollback to versions that do not support the in_memory schema_feature
Can keep it last, after the functional code

2025-01-28 21:15 UTC, bhalevy commented on db/schema_tables.cc
> +    }
This is done inside `if (auto tablet_hints_cdef = scylla_tables()->get_column_definition("tablet_hints"))` so the column should be there as far as the schema goes, or did you mean something else?

2025-01-28 21:17 UTC, bhalevy commented on docs/cql/ddl.rst
> +             : |
Nope.  I guess that's a typo after dropping the `hot_table` hint that was in the original branch.
Will drop this.

2025-01-28 21:17 UTC, bhalevy commented on docs/cql/ddl.rst
> +                                                It can be set when the table is created to allocate more tablets for it,
okay

2025-01-28 21:19 UTC, bhalevy commented on service/tablet_allocator.cc
> +            // FIXME: the table or the replication_strategy might be missing in boost unit tests
That some boost unit tests forge a synthetic tablet map without populating the database with a respective keyspace, replication strategy, and table(s).

2025-01-28 21:19 UTC, bhalevy commented on service/tablet_allocator.cc
> +            }
yes, unfortunately.

2025-01-28 21:20 UTC, bhalevy commented on service/tablet_allocator.cc
> +            // FIXME: the table or the replication_strategy might be missing in boost unit tests
@tgrabiec, is that fixable in your followup branch?

2025-01-28 22:32 UTC, tgrabiec commented on service/tablet_allocator.cc
> +            }
> This can't be correct. Merge and split are not symmetric.
> 
> It's hard to follow the logic of tablet_count_from_size, it changes meaning if we're below or above.
> 
> I suggest to keep the original logic.

The meaning of `tablet_count_from_size` is "desired tablet count due to average tablet size" and doesn't change. We switched to working with counts instead of resize decisions because we need to combine desired counts due to multiple factors now, and then decide which resize decision split or merge is needed to meet that count. What do you think is incorrect here, and what do you suggest to do instead?

2025-01-28 22:35 UTC, tgrabiec commented on service/tablet_allocator.cc
> +            // FIXME: the table or the replication_strategy might be missing in boost unit tests
> @tgrabiec, is that fixable in your followup branch?

It is, though I planned to fix existing tests in a follow-up.

2025-01-28 23:13 UTC, raphaelsc commented on locator/network_topology_strategy.cc
>      }
Ah I see now that we use tablet_count , not initial_tablets as in the keyspace. Sorry for the noise.

2025-01-28 23:31 UTC, raphaelsc commented on locator/network_topology_strategy.cc
> +        tablet_count = std::max<size_t>(tablet_count, (tablet_hints.expected_data_size_in_gb.value() << 30) / target_tablet_size);
we don't have to round up (expected_size / target_size) here since caller will round up to next power of two, right?

2025-01-29 08:18 UTC, scylladb-promoter commented
#### :red_circle: CI State: FAILURE

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14814/)
:white_check_mark: - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14814/)
**The following new/updated tests ran 100 times for each mode:**
:small_blue_diamond: boost/network_topology_strategy_test
:small_blue_diamond: boost/tablets_test
:x: - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/6188/)
:x: - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/3067/)
:x: - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/14199/)
:white_check_mark: - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14814/)
#### Failed Tests (6/37817):
- [test_rolling_upgrade](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14814/testReport/junit/enterprise_upgrade_test/TestEnterpriseRollingUpgrade/Tests___dtest_with_topology_changes___test_rolling_upgrade) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_rolling_upgrade)
- [test_rolling_upgrade](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14814/testReport/junit/rolling_upgrade_test/TestRollingUpgrade/Tests___dtest_with_topology_changes___test_rolling_upgrade) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_rolling_upgrade)
- [test_rolling_upgrade](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14814/testReport/junit/rolling_upgrade_test/TestRollingUpgrade/Tests___dtest_with_tablets___test_rolling_upgrade) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_rolling_upgrade)
- [test_rolling_upgrade](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14814/testReport/junit/enterprise_upgrade_test/TestEnterpriseRollingUpgrade/Tests___dtest_with_tablets___test_rolling_upgrade) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_rolling_upgrade)
- [test_rolling_upgrade](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14814/testReport/junit/enterprise_upgrade_test/TestEnterpriseRollingUpgrade/Tests___dtest___test_rolling_upgrade) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_rolling_upgrade)
- [test_rolling_upgrade](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14814/testReport/junit/rolling_upgrade_test/TestRollingUpgrade/Tests___dtest___test_rolling_upgrade) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_rolling_upgrade)
#### Build Details:
- Duration: 12 hr
- Builder: i-038ca87daeeabe3b9 (m5ad.8xlarge)

2025-01-29 11:39 UTC, mykaul commented
@bhalevy - do we have failures annotated? What else is missing here?

2025-01-29 12:30 UTC, avikivity commented on db/schema_tables.cc
> +    }
Ah, I'm used to checking the schema feature, not to checking the schema. It's okay.

2025-01-29 12:35 UTC, bhalevy commented on locator/network_topology_strategy.cc
> +        tablet_count = std::max<size_t>(tablet_count, (tablet_hints.expected_data_size_in_gb.value() << 30) / target_tablet_size);
it's not a bad idea to round up here too

2025-01-29 12:39 UTC, raphaelsc commented on locator/network_topology_strategy.cc
> +        tablet_count = std::max<size_t>(tablet_count, (tablet_hints.expected_data_size_in_gb.value() << 30) / target_tablet_size);
yes, it helps for the long run if we ever move away from power-of-two (and forget to update it).

2025-01-29 12:40 UTC, avikivity commented on service/tablet_allocator.cc
> +            }
In the original code, we compare against the tablet size goal * 2 and tablet size goal / 2. There is a factor of 4 in between.

In the new code, target_tablet_count is either *2 or /2 away from the current tablet count, but we compare against *2 for merge and  *1 for split. So there is a factor of 2 between the two thresholds. 2 != 4.

In terms of improvement for readability, I'd generate a set of minimum tablet counts (from each rule/hint), a set of maximum tablet counts (from each rule/hint, the only one that contributes is that we want at most 2.5GB tablets), apply std::max() to the minimums and std::min() to the maximum, discard the maximum if it's smaller than the minimum (with a comment), and then compare the current count to the min/max bounds and generate a decision.

We can even change the tablet size goal rule to use log2(table size / tablet size goal), in the future it can generates splits or merges larger than two.

2025-01-29 12:42 UTC, tgrabiec commented on locator/network_topology_strategy.cc
> +        tablet_count = std::max<size_t>(tablet_count, (tablet_hints.expected_data_size_in_gb.value() << 30) / target_tablet_size);
Please don't, my PR changes this logic. Rounding up here would hurt the logic: two tables which want 130 tablets and 210 tablets would be treated the same before scaling if we round up early, but we want scaling to affect them proportionally to their impact, and post scaling we can have 130*0.4=52 (64) and 210*0.4=84 (128).

2025-01-29 13:06 UTC, raphaelsc commented on locator/network_topology_strategy.cc
> +        tablet_count = std::max<size_t>(tablet_count, (tablet_hints.expected_data_size_in_gb.value() << 30) / target_tablet_size);
the idea here was to only round to the next nearest integer, not to the next power of two. would it still cause a problem? anyway, it's a minor item, so we don't have to do any change here if you prefer.

2025-01-29 14:24 UTC, bhalevy commented
> @bhalevy - do we have failures annotated? What else is missing here?

Not yet.  @avikivity had a bunch of non-trivial review comments that I'm addressing

2025-01-29 14:43 UTC, bhalevy commented on service/tablet_allocator.cc
> +            }
Avi, comparing to the previous algorithm is confusing.
We should scrutinize this algorithm independently to see if it achieves what it's aimed to do.
`target_tablet_count` may indeed be twice or half of the current tablet count (bound below by hint-based min_tablet_count)
The reason merge is considered only if the current tablet count is more than twice the target tablet count is that we want to honor the target tablet count as a minimum and not go below it following the tablets merge.

And let's look at the merge path:
```
        auto tablet_count_from_size = d.tablet_count;
        if (d.avg_tablet_size < d.target_min_tablet_size()) {
            tablet_count_from_size /= 2;
        }
...
            if (d.tablet_count >= 2 * target_tablet_count) {
                decision.way = resize_decision::merge{};
```
If `min_tablet_count=0`, the above means that merge will happen if the average tablet size is less than `target_min_tablet_size` (which equals target_tablet_size / 2)
If `min_tablet_count > tablet_count_from_size`, the condition will not be met, since merging will take tablet_count below `min_tablet_count`.

Split is "easier" since it increases the tablet count, so it won't go below the minimum if the current tablet count is above the minimum.  It may still stay below the minimum though and another split might be needed in the next round.  The latter case would happen if `d.tablet_count < target_tablet_count / 2`.
I agree that in the future we may choose to perform n-way split where `n=2^i, i > 1`

2025-01-29 21:41 UTC, tgrabiec commented on locator/network_topology_strategy.cc
> +        tablet_count = std::max<size_t>(tablet_count, (tablet_hints.expected_data_size_in_gb.value() << 30) / target_tablet_size);
Both std::floor and std::ceil put tablet size within the scheduler's steady state of avg tablet size in the range [target_tablet_size / 2, target_tablet_size * 2]. std::floor prefers fewer and larger tablets, std::ceil prefers more and smaller tablets. I assumed that fewer tablets is preferred.

2025-01-29 21:41 UTC, tgrabiec commented on db/schema_features.hh
> +    TABLET_HINTS,
When do we set this feature?

2025-01-29 21:41 UTC, tgrabiec commented on db/schema_tables.cc
> +    if (auto tablet_hints_cdef = scylla_tables()->get_column_definition("tablet_hints")) {
Hmm, this if is always true because scylla_tablets() works with a full feature set.

2025-01-29 21:41 UTC, tgrabiec commented on db/schema_tables.cc
> +        }
Why not add unconditionally?

feature_service::cluster_schema_features() doesn't set TABLET_HINTS feature, which means that adjust_schema_for_schema_features() will drop writes to "tablet_hints" column, and schema changes via raft call it, so I'm not sure how it works.

2025-02-02 09:28 UTC, bhalevy commented
In v11 (d6b1534a99):
- rebased
- reamed tablet hints to "tablet options"
- moved the options into scylla_tables

2025-02-02 09:32 UTC, bhalevy commented
> We need an empty token in order to be able to clear the map:
>
> ALTER ... WITH tablet_hints = {}

@tgrabiec you're right from the grammar perspective, but maybe for the documentation this is confusing.
I'm not sure.  I've deleted it from ddl.rst, but can bring it back for completeness.
Maybe it'd be clearer to document it at a higher level, like this:
```
   table_options: COMPACT STORAGE [ AND `table_options` ]
                   : | CLUSTERING ORDER BY '(' `clustering_order` ')' [ AND `table_options` ]
                   : | scylla_encryption_options: '=' '{'[`cipher_algorithm` : <hash>]','[`secret_key_strength` : <len>]','[`key_provider`: <provider>]'}'
                   : | caching  '=' ' {'caching_options'}'
                   : | tablets '=' '{' `tablet_options` '}'
                   : | `options`
   
   clustering_order: `column_name` (ASC | DESC) ( ',' `column_name` (ASC | DESC) )*
   
   tablet_options: `tablet_option` [',' `tablet_option`]
             : |
   
   tablet_option: 'expected_data_size_in_gb' ':' <int>
             : | 'min_per_shard_tablet_count' ':' <float>
             : | 'min_tablet_count' ':' <int>
```

2025-02-02 09:36 UTC, bhalevy commented on db/schema_tables.cc
> +        }
hmm, seems like we should fix this.
IIRC I've seen a similar issue with the in_memory column that prevented upgrade rollback to a version that doesn't support in-memory tables.

2025-02-02 10:40 UTC, scylladb-promoter commented
#### :red_circle: CI State: ABORTED

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14895/)
:x: - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14895/)
**The following new/updated tests ran 100 times for each mode:**
:small_blue_diamond: boost/network_topology_strategy_test
:small_blue_diamond: boost/tablets_test
#### Failed Tests (5/65):
- [[empty]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14895/testReport/junit/boost.tablets_test.test_explicit_tablets_enable.2.xunit/xml/_empty_) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+[empty])
- [[empty]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14895/testReport/junit/boost.tablets_test.test_large_tablet_metadata.3.xunit/xml/_empty_) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+[empty])
- [[empty]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14895/testReport/junit/boost.tablets_test.test_mutation_builder.3.xunit/xml/_empty_) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+[empty])
- [[empty]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14895/testReport/junit/boost.tablets_test.test_read_required_hosts.3.xunit/xml/_empty_) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+[empty])
- [[empty]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14895/testReport/junit/boost.tablets_test.test_tablet_metadata_persistence.3.xunit/xml/_empty_) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+[empty])
#### Build Details:
- Duration: 1 hr 18 min
- Builder: spider8.cloudius-systems.com

2025-02-02 10:50 UTC, bhalevy commented
> #### 🔴 CI State: ABORTED
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14895/) ❌ - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14895/) **The following new/updated tests ran 100 times for each mode:** 🔹 boost/network_topology_strategy_test 🔹 boost/tablets_test
> 
> #### Failed Tests (5/65):
> * [[empty]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14895/testReport/junit/boost.tablets_test.test_explicit_tablets_enable.2.xunit/xml/_empty_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+%5Bempty%5D)
> * [[empty]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14895/testReport/junit/boost.tablets_test.test_large_tablet_metadata.3.xunit/xml/_empty_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+%5Bempty%5D)
> * [[empty]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14895/testReport/junit/boost.tablets_test.test_mutation_builder.3.xunit/xml/_empty_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+%5Bempty%5D)
> * [[empty]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14895/testReport/junit/boost.tablets_test.test_read_required_hosts.3.xunit/xml/_empty_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+%5Bempty%5D)
> * [[empty]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14895/testReport/junit/boost.tablets_test.test_tablet_metadata_persistence.3.xunit/xml/_empty_) [🔍](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+%5Bempty%5D)
> 
> #### Build Details:
> * Duration: 1 hr 18 min
> * Builder: spider8.cloudius-systems.com

https://github.com/scylladb/scylladb/issues/22165

2025-02-02 15:20 UTC, scylladb-promoter commented
#### :red_circle: CI State: FAILURE

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14896/)
:white_check_mark: - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14896/)
**The following new/updated tests ran 100 times for each mode:**
:small_blue_diamond: boost/network_topology_strategy_test
:small_blue_diamond: boost/tablets_test
:x: - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/6237/)
:x: - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/3117/)
:x: - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/14249/)
:white_check_mark: - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14896/)
#### Failed Tests (6/38478):
- [test_rolling_upgrade](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14896/testReport/junit/enterprise_upgrade_test/TestEnterpriseRollingUpgrade/Tests___dtest_with_topology_changes___test_rolling_upgrade) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_rolling_upgrade)
- [test_rolling_upgrade](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14896/testReport/junit/rolling_upgrade_test/TestRollingUpgrade/Tests___dtest_with_topology_changes___test_rolling_upgrade) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_rolling_upgrade)
- [test_rolling_upgrade](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14896/testReport/junit/rolling_upgrade_test/TestRollingUpgrade/Tests___dtest_with_tablets___test_rolling_upgrade) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_rolling_upgrade)
- [test_rolling_upgrade](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14896/testReport/junit/enterprise_upgrade_test/TestEnterpriseRollingUpgrade/Tests___dtest_with_tablets___test_rolling_upgrade) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_rolling_upgrade)
- [test_rolling_upgrade](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14896/testReport/junit/enterprise_upgrade_test/TestEnterpriseRollingUpgrade/Tests___dtest___test_rolling_upgrade) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_rolling_upgrade)
- [test_rolling_upgrade](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/14896/testReport/junit/rolling_upgrade_test/TestRollingUpgrade/Tests___dtest___test_rolling_upgrade) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_rolling_upgrade)
#### Build Details:
- Duration: 5 hr 52 min
- Builder: spider7.cloudius-systems.com

2025-02-03 09:10 UTC, bhalevy commented on db/schema_tables.cc
> +        }
Sigh.  https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14896/testReport/junit/enterprise_upgrade_test/TestEnterpriseRollingUpgrade/Tests___dtest_with_topology_changes___test_rolling_upgrade/
```
E   cassandra.cluster.NoHostAvailable: ('Unable to connect to any servers', {'127.0.99.2:9042': ReadFailure('Error from server: code=1300 [Replica(s) failed to execute read] message="Operation failed for system_schema.scylla_tables - received 0 responses and 1 failures from 1 CL=ONE." info={\'consistency\': \'ONE\', \'required_responses\': 1, \'received_responses\': 0, \'failures\': 1}')})
```

2025-02-03 09:11 UTC, bhalevy commented on db/schema_tables.cc
> +        }
I was worry of that when I initially went for implementing the hints as a schema extension

2025-02-03 15:34 UTC, bhalevy commented
In v12 ([f8a525c](https://github.com/scylladb/scylladb/commit/f8a525ce4d97fdaa7221b9f94ec08546ebe59112)):
- added TABLET_OPTIONS cluster schema feature
- applied for validating tablet options in cf_prop_defs::validate
- made the raw schema _tablet_options member optional
  - so it is set only on CREATE/ALTER TABLE, and when the schema is loaded and the `tablets` column in scylla_tables has a value
  - write to the `tablets` column in scylla_tables only if the table schema `has_tablet_options()`, meaning the options are engaged (and could be empty.
  - this makes the change backward compatible as we'd write to the new column only after the cluster feature is enabled.
- fixed ddl.rst regarding empty tablet_options (moved the empty alternative from the single tablet_option to the tablet_options list)
- rebased

2025-02-03 15:35 UTC, bhalevy commented on schema/schema.cc
> +        && x._raw._tablet_hints == y._raw._tablet_hints
Done in v12 ([f8a525c](https://github.com/scylladb/scylladb/commit/f8a525ce4d97fdaa7221b9f94ec08546ebe59112))

2025-02-03 15:35 UTC, bhalevy commented on db/schema_tables.cc
> +    if (auto tablet_hints_cdef = scylla_tables()->get_column_definition("tablet_hints")) {
Gone in v12 ([f8a525c](https://github.com/scylladb/scylladb/commit/f8a525ce4d97fdaa7221b9f94ec08546ebe59112))

2025-02-03 15:35 UTC, bhalevy commented
> > We need an empty token in order to be able to clear the map:
> > ALTER ... WITH tablet_hints = {}
> 
> @tgrabiec you're right from the grammar perspective, but maybe for the documentation this is confusing. I'm not sure. I've deleted it from ddl.rst, but can bring it back for completeness. Maybe it'd be clearer to document it at a higher level, like this:
> 
> ```
>    table_options: COMPACT STORAGE [ AND `table_options` ]
>                    : | CLUSTERING ORDER BY '(' `clustering_order` ')' [ AND `table_options` ]
>                    : | scylla_encryption_options: '=' '{'[`cipher_algorithm` : <hash>]','[`secret_key_strength` : <len>]','[`key_provider`: <provider>]'}'
>                    : | caching  '=' ' {'caching_options'}'
>                    : | tablets '=' '{' `tablet_options` '}'
>                    : | `options`
>    
>    clustering_order: `column_name` (ASC | DESC) ( ',' `column_name` (ASC | DESC) )*
>    
>    tablet_options: `tablet_option` [',' `tablet_option`]
>              : |
>    
>    tablet_option: 'expected_data_size_in_gb' ':' <int>
>              : | 'min_per_shard_tablet_count' ':' <float>
>              : | 'min_tablet_count' ':' <int>
> ```
> 
> Edit: allowing empty single tablet_option is incorrect since technically it will allow specifying empty options like `tablets = {'min_tablet_count':'100',,'min_per_shard_tablet_count':0.75,}`

Done in v12 ([f8a525c](https://github.com/scylladb/scylladb/commit/f8a525ce4d97fdaa7221b9f94ec08546ebe59112))

2025-02-04 03:54 UTC, scylladb-promoter commented
#### :red_circle: CI State: FAILURE

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14927/)
:white_check_mark: - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14927/)
**The following new/updated tests ran 100 times for each mode:**
:small_blue_diamond: boost/network_topology_strategy_test
:small_blue_diamond: boost/tablets_test
:white_check_mark: - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/6268/)
:white_check_mark: - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/14279/)
:x: - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/3147/)
:white_check_mark: - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14927/)
#### Build Details:
- Duration: 12 hr
- Builder: i-0acfa41bc7eb6be1f (m5ad.8xlarge)

2025-02-04 08:44 UTC, bhalevy commented
> #### 🔴 CI State: FAILURE
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14927/) ✅ - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14927/) **The following new/updated tests ran 100 times for each mode:** 🔹 boost/network_topology_strategy_test 🔹 boost/tablets_test ✅ - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/6268/) ✅ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/14279/) ❌ - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/3147/) ✅ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/14927/)
> 
> #### Build Details:
> * Duration: 12 hr
> * Builder: i-0acfa41bc7eb6be1f (m5ad.8xlarge)

https://github.com/scylladb/scylladb/issues/22394

2025-02-04 10:12 UTC, bhalevy commented
https://github.com/scylladb/scylla-dtest/pull/5550 skips those tests with tablets.

2025-02-04 18:52 UTC, tgrabiec requested changes

2025-02-04 18:52 UTC, tgrabiec commented on cql3/statements/cf_prop_defs.cc
> +    if (!tablet_options_map.empty()) {
We should reject `with tablets = {}` too when the feature is not enabled, since it will emit mutations which null out the map.

2025-02-04 18:52 UTC, tgrabiec commented on schema/schema.cc
> +db::tablet_options schema::tablet_options() const noexcept {
This can throw due to copies.

2025-02-05 12:23 UTC, tgrabiec commented on schema/schema.cc
> +db::tablet_options schema::tablet_options() const noexcept {
Actually, not due to copies, but parsing. tablet_options constructor is not marked noexcept, and can throw `syntax_exception`. Maybe that should never happen in practice, but I think it's unsafe that this getter is marked noexcept but calls non-noexcept code. It means unnecessary abort in the future, and no one really relies on it to be noexcept.

2025-02-05 12:51 UTC, bhalevy commented on schema/schema.cc
> +db::tablet_options schema::tablet_options() const noexcept {
right.  I left it by mistake IIRC as originally it returned a reference to the tablet_options member

2025-02-05 13:08 UTC, bhalevy commented on schema/schema.cc
> +db::tablet_options schema::tablet_options() const noexcept {
cf_prop_defs::validate is calling tablet_options::validate that should prevent any parsing errors here, but still let's be more permissive here, just in case.

2025-02-05 13:30 UTC, bhalevy commented
In v13 ([c8b1548](https://github.com/scylladb/scylladb/commit/c8b154835c45cc27b8f0ec87764a9c9d62f455f3)):
- rebased
- Fixed `Pre-table` typo in comment
- `feed_hash(h, r._tablet_options);`
- Changed cf_prop_defs::get_tablet_options to return optional map, so we can reject also an empty map when the tablet_options feature is not enabled
- Dropped noexcept specifier from `schema::tablet_options()`

2025-02-05 13:30 UTC, bhalevy commented on db/schema_features.hh
> +    // Pre-table tablet options
Fixed in v13 ([c8b1548](https://github.com/scylladb/scylladb/commit/c8b154835c45cc27b8f0ec87764a9c9d62f455f3))

2025-02-05 13:30 UTC, bhalevy commented on schema/schema.cc
> +    }
Fixed in v13 ([c8b1548](https://github.com/scylladb/scylladb/commit/c8b154835c45cc27b8f0ec87764a9c9d62f455f3))

2025-02-05 13:30 UTC, bhalevy commented on schema/schema.cc
> +    }
Fixed in v13 ([c8b1548](https://github.com/scylladb/scylladb/commit/c8b154835c45cc27b8f0ec87764a9c9d62f455f3))

2025-02-05 13:30 UTC, bhalevy commented on cql3/statements/cf_prop_defs.cc
> +    if (!tablet_options_map.empty()) {
Fixed in v13 ([c8b1548](https://github.com/scylladb/scylladb/commit/c8b154835c45cc27b8f0ec87764a9c9d62f455f3))

2025-02-05 19:15 UTC, avikivity commented on db/schema_features.hh
> +    // Per-table tablet options
Corrected in the wrong patch

2025-02-05 19:26 UTC, avikivity commented on service/tablet_allocator.cc
> +            }
It's really confusing. Because target_tablet_count_from_size means "a high number if the table is growing, or a low number if the table is shrinking", and you compare against it in both directions. In one case it's a minimum, in another it's a maximum.

I suggest to split it into two variables, one for each direction.

2025-02-05 19:51 UTC, raphaelsc commented on service/tablet_allocator.cc
> +            }
Without diving deep into this today, please make sure we're still applying hysteresis when deciding to cancel an ongoing resize operation.

For example, if merge threshold is 2.5G, then we only cancel merge if avg grows to 5G. If split one is 10G, we only cancel split if avg drops to 5G. That's to avoid oscillations between splits and merges. I saw changes in that area.

2025-02-05 22:49 UTC, scylladb-promoter commented
#### :red_circle: CI State: FAILURE

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/15011/)
:white_check_mark: - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/15011/)
**The following new/updated tests ran 100 times for each mode:**
:small_blue_diamond: boost/network_topology_strategy_test
:small_blue_diamond: boost/tablets_test
:white_check_mark: - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/6330/)
:white_check_mark: - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/3210/)
:white_check_mark: - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/14345/)
:x: - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/15011/)
#### Failed Tests (2/38461):
- [test_system_schema_version_is_stable](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/15011/testReport/junit/boost/schema_change_test/test_system_schema_version_is_stable) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+test_system_schema_version_is_stable)
- [[empty]](https://jenkins.scylladb.com//job/scylla-master/job/scylla-ci/15011/testReport/junit/boost.encryption_at_rest_test.test_kms_network_error.1.xunit/xml/Tests___Unit_Tests____empty_) [:mag:](https://github.com/scylladb/scylladb/issues?q=is:issue+is:open+[empty])
#### Build Details:
- Duration: 9 hr 21 min
- Builder: spider1.cloudius-systems.com

2025-02-06 05:57 UTC, bhalevy commented on db/schema_features.hh
> +    // Per-table tablet options
Oops.  right

2025-02-06 07:15 UTC, bhalevy commented
In v14 ([421c759](https://github.com/scylladb/scylladb/commit/421c7598f7d01c7ef9c669b62b72a8a4b2a0cdd4)):
- rebased
- Moved typo fix in comment to the correct patch
- Updated test_system_schema_version_is_stable

range diff:
```diff
 1:  43393ce156 !  1:  ad8b0649ff feature_service: add TABLET_OPTIONS cluster schema feature
    @@ db/schema_features.hh: enum class schema_feature {
          // Unused.  Defined for backward compatibility only
          IN_MEMORY_TABLES,
     +
    -+    // Pre-table tablet options
    ++    // Per-table tablet options
     +    TABLET_OPTIONS,
      };
      
 2:  1489589d48 !  2:  c5668d99c9 schema: add per-table tablet options
    @@ db/CMakeLists.txt: target_sources(db
        PUBLIC
          ${CMAKE_SOURCE_DIR})
     
    - ## db/schema_features.hh ##
    -@@ db/schema_features.hh: enum class schema_feature {
    -     // Unused.  Defined for backward compatibility only
    -     IN_MEMORY_TABLES,
    - 
    --    // Pre-table tablet options
    -+    // Per-table tablet options
    -     TABLET_OPTIONS,
    - };
    - 
    -
      ## db/schema_tables.cc ##
     @@ db/schema_tables.cc: schema_ptr scylla_tables(schema_features features) {
                  // In this case, for non-system tables, `version` is null and `schema::version()` will be a hash.
    @@ schema/schema_builder.hh: struct schema_builder {
              return default_names(_raw);
          }
     
    + ## test/boost/schema_change_test.cc ##
    +@@ test/boost/schema_change_test.cc: SEASTAR_TEST_CASE(test_system_schema_version_is_stable) {
    + 
    +         // If you changed the schema of system.batchlog then this is expected to fail.
    +         // Just replace expected version with the new version.
    +-        BOOST_REQUIRE_EQUAL(s->version(), table_schema_version(utils::UUID("3febbbce-8841-304a-abb9-170078ac173d")));
    ++        BOOST_REQUIRE_EQUAL(s->version(), table_schema_version(utils::UUID("1f504ac7-350f-37aa-8a9e-105b1325d8e3")));
    +     });
    + }
    + 
    +
      ## test/cqlpy/test_describe.py ##
     @@ test/cqlpy/test_describe.py: def test_desc_table(cql, test_keyspace, random_seed, has_tablets):
              finally:
 3:  34ebde3e5d =  3:  7cd29810a0 test: cqlpy: test_tablets: add tests for per-table tablet options
 4:  991b813bf8 =  4:  1054e05491 cql3/create_keyspace_statement: add deprecation warning for initial tablets
 5:  aacb67e2be =  5:  8aace28397 cql3: data_dictionary: format keyspace_metadata: print "enabled":true when initial_tablets=0
 6:  96c5fcbe3b =  6:  49dacb1d52 network_topology_strategy: calculate_initial_tablets_from_topology: set default rf to 0
 7:  e4e30acbfb !  7:  86bcf4cffe network_topology_strategy: calculate_initial_tablets_from_topology: precalculate shards per dc using for_each_token_owner
    @@ locator/network_topology_strategy.cc: effective_replication_map_ptr network_topo
     -
     -        for (const auto& ep : dc.second) {
     -            const auto* node = tm->get_topology().find_node(ep);
    --            if (node != nullptr) {
    +-            if (node != nullptr && node->is_normal()) {
     -                shards_in_dc += node->get_shard_count();
     -            }
    --        }
    ++    std::unordered_map<sstring, unsigned> shards_per_dc_map;
    ++    tm->for_each_token_owner([&] (const node& node) {
    ++        if (node.is_normal()) {
    ++            shards_per_dc_map[node.dc_rack().dc] += node.get_shard_count();
    +         }
     -
     -        if (auto it = rf.find(dc.first); it != rf.end()) {
     -            rf_in_dc = it->second;
    -+    std::unordered_map<sstring, unsigned> shards_per_dc_map;
    -+    tm->for_each_token_owner([&] (const node& n) {
    -+        shards_per_dc_map[n.dc_rack().dc] += n.get_shard_count();
     +    });
     +    for (const auto& [dc, rf_in_dc] : rf) {
     +        if (!rf_in_dc) {
 8:  4e34fbebdc !  8:  32c2f7579f network_topology_strategy: allocate_tablets_for_new_table: consider tablet options
    @@ locator/network_topology_strategy.cc: effective_replication_map_ptr network_topo
     +static unsigned calculate_initial_tablets_from_topology(const schema& s, token_metadata_ptr tm, const std::unordered_map<sstring, size_t>& rf, double min_per_shard_tablet_count = 0) {
          unsigned initial_tablets = std::numeric_limits<unsigned>::min();
          std::unordered_map<sstring, unsigned> shards_per_dc_map;
    -     tm->for_each_token_owner([&] (const node& n) {
    +     tm->for_each_token_owner([&] (const node& node) {
     @@ locator/network_topology_strategy.cc: static unsigned calculate_initial_tablets_from_topology(const schema& s, token_m
              }
              unsigned shards_in_dc = shards_per_dc_map[dc];
 9:  820786e166 =  9:  559f083dc6 tablet_allocator: load_balancer: table_size_desc: keep target_tablet_size as member
10:  a15d62770c = 10:  3b11c3c408 tablet_allocator: consider tablet options for resize decision
11:  c8b154835c = 11:  421c7598f7 tablets: resize_decision: get rid of initial_decision
```

2025-02-06 07:18 UTC, bhalevy commented
> In v14 ([421c759](https://github.com/scylladb/scylladb/commit/421c7598f7d01c7ef9c669b62b72a8a4b2a0cdd4)):
> 
> * rebased (resolved conflict with 3bb19e9ac98 in calculate_initial_tablets_from_topology)
> * Moved typo fix in comment to the correct patch
> * Updated test_system_schema_version_is_stable
> 
> range diff:
> 
> ```diff
>  1:  43393ce156 !  1:  ad8b0649ff feature_service: add TABLET_OPTIONS cluster schema feature
>     @@ db/schema_features.hh: enum class schema_feature {
>           // Unused.  Defined for backward compatibility only
>           IN_MEMORY_TABLES,
>      +
>     -+    // Pre-table tablet options
>     ++    // Per-table tablet options
>      +    TABLET_OPTIONS,
>       };
>       
>  2:  1489589d48 !  2:  c5668d99c9 schema: add per-table tablet options
>     @@ db/CMakeLists.txt: target_sources(db
>         PUBLIC
>           ${CMAKE_SOURCE_DIR})
>      
>     - ## db/schema_features.hh ##
>     -@@ db/schema_features.hh: enum class schema_feature {
>     -     // Unused.  Defined for backward compatibility only
>     -     IN_MEMORY_TABLES,
>     - 
>     --    // Pre-table tablet options
>     -+    // Per-table tablet options
>     -     TABLET_OPTIONS,
>     - };
>     - 
>     -
>       ## db/schema_tables.cc ##
>      @@ db/schema_tables.cc: schema_ptr scylla_tables(schema_features features) {
>                   // In this case, for non-system tables, `version` is null and `schema::version()` will be a hash.
>     @@ schema/schema_builder.hh: struct schema_builder {
>               return default_names(_raw);
>           }
>      
>     + ## test/boost/schema_change_test.cc ##
>     +@@ test/boost/schema_change_test.cc: SEASTAR_TEST_CASE(test_system_schema_version_is_stable) {
>     + 
>     +         // If you changed the schema of system.batchlog then this is expected to fail.
>     +         // Just replace expected version with the new version.
>     +-        BOOST_REQUIRE_EQUAL(s->version(), table_schema_version(utils::UUID("3febbbce-8841-304a-abb9-170078ac173d")));
>     ++        BOOST_REQUIRE_EQUAL(s->version(), table_schema_version(utils::UUID("1f504ac7-350f-37aa-8a9e-105b1325d8e3")));
>     +     });
>     + }
>     + 
>     +
>       ## test/cqlpy/test_describe.py ##
>      @@ test/cqlpy/test_describe.py: def test_desc_table(cql, test_keyspace, random_seed, has_tablets):
>               finally:
>  3:  34ebde3e5d =  3:  7cd29810a0 test: cqlpy: test_tablets: add tests for per-table tablet options
>  4:  991b813bf8 =  4:  1054e05491 cql3/create_keyspace_statement: add deprecation warning for initial tablets
>  5:  aacb67e2be =  5:  8aace28397 cql3: data_dictionary: format keyspace_metadata: print "enabled":true when initial_tablets=0
>  6:  96c5fcbe3b =  6:  49dacb1d52 network_topology_strategy: calculate_initial_tablets_from_topology: set default rf to 0
>  7:  e4e30acbfb !  7:  86bcf4cffe network_topology_strategy: calculate_initial_tablets_from_topology: precalculate shards per dc using for_each_token_owner
>     @@ locator/network_topology_strategy.cc: effective_replication_map_ptr network_topo
>      -
>      -        for (const auto& ep : dc.second) {
>      -            const auto* node = tm->get_topology().find_node(ep);
>     --            if (node != nullptr) {
>     +-            if (node != nullptr && node->is_normal()) {
>      -                shards_in_dc += node->get_shard_count();
>      -            }
>     --        }
>     ++    std::unordered_map<sstring, unsigned> shards_per_dc_map;
>     ++    tm->for_each_token_owner([&] (const node& node) {
>     ++        if (node.is_normal()) {
>     ++            shards_per_dc_map[node.dc_rack().dc] += node.get_shard_count();
>     +         }
>      -
>      -        if (auto it = rf.find(dc.first); it != rf.end()) {
>      -            rf_in_dc = it->second;
>     -+    std::unordered_map<sstring, unsigned> shards_per_dc_map;
>     -+    tm->for_each_token_owner([&] (const node& n) {
>     -+        shards_per_dc_map[n.dc_rack().dc] += n.get_shard_count();
>      +    });
>      +    for (const auto& [dc, rf_in_dc] : rf) {
>      +        if (!rf_in_dc) {
>  8:  4e34fbebdc !  8:  32c2f7579f network_topology_strategy: allocate_tablets_for_new_table: consider tablet options
>     @@ locator/network_topology_strategy.cc: effective_replication_map_ptr network_topo
>      +static unsigned calculate_initial_tablets_from_topology(const schema& s, token_metadata_ptr tm, const std::unordered_map<sstring, size_t>& rf, double min_per_shard_tablet_count = 0) {
>           unsigned initial_tablets = std::numeric_limits<unsigned>::min();
>           std::unordered_map<sstring, unsigned> shards_per_dc_map;
>     -     tm->for_each_token_owner([&] (const node& n) {
>     +     tm->for_each_token_owner([&] (const node& node) {
>      @@ locator/network_topology_strategy.cc: static unsigned calculate_initial_tablets_from_topology(const schema& s, token_m
>               }
>               unsigned shards_in_dc = shards_per_dc_map[dc];
>  9:  820786e166 =  9:  559f083dc6 tablet_allocator: load_balancer: table_size_desc: keep target_tablet_size as member
> 10:  a15d62770c = 10:  3b11c3c408 tablet_allocator: consider tablet options for resize decision
> 11:  c8b154835c = 11:  421c7598f7 tablets: resize_decision: get rid of initial_decision
> ```

2025-02-06 07:38 UTC, bhalevy commented on service/tablet_allocator.cc
> +            }
> Without diving deep into this today, please make sure we're still applying hysteresis when deciding to cancel an ongoing resize operation.
> 
> For example, if merge threshold is 2.5G, then we only cancel merge if avg grows to 5G. If split one is 10G, we only cancel split if avg drops to 5G. That's to avoid oscillations between splits and merges, and to react less rapidly to changes in avg. I saw changes in that area.

I don't think anything should change with that respect since the split decision vs. the avg tablet size remained the same, while the merge decision was restricted, to respect minimum tablet count derived from the tablet options, so it will happen only if the size-induced merge will not cause the tablet count to go below the minimum, but the size-based considerations are the same.

2025-02-06 07:50 UTC, bhalevy commented on service/tablet_allocator.cc
> +            }
> It's really confusing. Because target_tablet_count_from_size means "a high number if the table is growing, or a low number if the table is shrinking", and you compare against it in both directions. In one case it's a minimum, in another it's a maximum.
> 
> I suggest to split it into two variables, one for each direction.

I'm not sure I like this idea as is...
How about the following:
```c++
            auto target_tablet_count = d.tablet_count;
            if (d.tablet_count < d.min_tablet_count || d.avg_tablet_size > d.target_max_tablet_size()) {
                // Split based on min_tablet_count or avg_tablet_size
                target_tablet_count *= 2;
                decision.way = resize_decision::split{};
            } if (d.avg_tablet_size < d.target_min_tablet_size()) {
                // Consider merge, as long as it doesn't violate min_tablet_count
                target_tablet_count /= 2;
                if (target_tablet_count >= d.min_tablet_count) {
                    decision.way = resize_decision::merge{};
                }
            }
```

2025-02-06 08:31 UTC, bhalevy commented on service/tablet_allocator.cc
> +            }
Implemented the above in v15

2025-02-06 08:32 UTC, bhalevy commented
In v15 ([47735a0](https://github.com/scylladb/scylladb/commit/47735a0c54629081fc0a66cc26c2c63a9dc2ccec)):
- simplified `to_resize_decision`

```diff
diff --git a/service/tablet_allocator.cc b/service/tablet_allocator.cc
index d8e4a27ba5..2cb710d8ce 100644
--- a/service/tablet_allocator.cc
+++ b/service/tablet_allocator.cc
@@ -505,19 +505,18 @@ class load_balancer {
         static locator::resize_decision to_resize_decision(const table_size_desc& d) {
             locator::resize_decision decision;
 
-            auto tablet_count_from_size = d.tablet_count;
-            if (d.avg_tablet_size < d.target_min_tablet_size()) {
-                tablet_count_from_size /= 2;
-            } else if (d.avg_tablet_size > d.target_max_tablet_size()) {
-                tablet_count_from_size *= 2;
-            }
-
-            auto target_tablet_count = std::max(d.min_tablet_count, tablet_count_from_size);
-
-            if (d.tablet_count >= 2 * target_tablet_count) {
-                decision.way = resize_decision::merge{};
-            } else if (d.tablet_count < target_tablet_count) {
+            auto target_tablet_count = d.tablet_count;
+            if (d.tablet_count < d.min_tablet_count || d.avg_tablet_size > d.target_max_tablet_size()) {
+                // Split based on min_tablet_count or avg_tablet_size
+                // TODO: extend to n-way split when needed
+                target_tablet_count *= 2;
                 decision.way = resize_decision::split{};
+            } else if (d.avg_tablet_size < d.target_min_tablet_size()) {
+                // Consider merge, as long as it doesn't violate min_tablet_count
+                target_tablet_count /= 2;
+                if (target_tablet_count >= d.min_tablet_count) {
+                    decision.way = resize_decision::merge{};
+                }
             }
 
             lblogger.debug("to_resize_decision: tablet_count={}, avg_tablet_size={}, min_tablet_count={}, target_tablet_count={}: decision={}",
```

2025-02-06 12:39 UTC, tgrabiec requested changes

2025-02-06 12:39 UTC, tgrabiec commented on service/tablet_allocator.cc
> +            } else if (d.avg_tablet_size < d.target_min_tablet_size()) {
I think @raphaelsc is right that we lose hysteresis here. If we emitted "split" decision because `d.avg_tablet_size` crossed `d.target_max_tablet_size()`, we shouldn't emit none when it moves back below `d.target_max_tablet_size()`, but when it moves back below `d.target_tablet_size()`. So the logic would be:

```
if (d.tablet_count < d.min_tablet_count || d.avg_tablet_size > d.target_max_tablet_size()
  || (d.current_request == split && d.avg_tablet_size > d.target_tablet_size)) {
     decision = split;
}
```

And similar for merge.

2025-02-06 12:47 UTC, raphaelsc commented on service/tablet_allocator.cc
> +            }
> > Without diving deep into this today, please make sure we're still applying hysteresis when deciding to cancel an ongoing resize operation.
> > For example, if merge threshold is 2.5G, then we only cancel merge if avg grows to 5G. If split one is 10G, we only cancel split if avg drops to 5G. That's to avoid oscillations between splits and merges, and to react less rapidly to changes in avg. I saw changes in that area.
> 
> I don't think anything should change with that respect since the split decision vs. the avg tablet size remained the same, while the merge decision was restricted, to respect minimum tablet count derived from the tablet options, so it will happen only if the size-induced merge will not cause the tablet count to go below the minimum, but the size-based considerations are the same.

I think we're no longer applying hysteresis.

cancel is now implemented as:
```
        bool table_needs_resize_cancellation(const table_size_desc& d) const {
            return d.resize_decision.split_or_merge() && to_resize_decision(d).way != d.resize_decision.way;
        }
```

If we decided to split, since we're past 10G, and during split, avg drops to 9.9G. it seems to me that now we'll cancel split, since the decision, returned by to_resize_decision(d) will be none. We want to avoid this rapid reaction through hysteresis. Resize is only canceled when it will cause oscillations between splits and merges.

Please confirm.

2025-02-06 15:08 UTC, scylladb-promoter commented
#### :green_circle: CI State: SUCCESS

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/15030/)
:white_check_mark: - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/15030/)
**The following new/updated tests ran 100 times for each mode:**
:small_blue_diamond: boost/network_topology_strategy_test
:small_blue_diamond: boost/schema_change_test
:small_blue_diamond: boost/tablets_test
:white_check_mark: - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/6352/)
:white_check_mark: - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/3235/)
:white_check_mark: - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/14367/)
:white_check_mark: - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/15030/)
#### Build Details:
- Duration: 6 hr 36 min
- Builder: i-0a36fb530930a09cf (m5d.12xlarge)

2025-02-06 15:47 UTC, bhalevy commented
In v16 ([fea93a8](https://github.com/scylladb/scylladb/commit/fea93a8715456fb8eaa30f6fb869337b40d29bb5):
- added hysteresis for resize decisions

```diff
diff --git a/locator/tablets.hh b/locator/tablets.hh
index 76dbc4b9fc..a7ef2b77fe 100644
--- a/locator/tablets.hh
+++ b/locator/tablets.hh
@@ -333,8 +333,17 @@ struct resize_decision {
 
     resize_decision() = default;
     resize_decision(sstring decision, uint64_t seq_number);
+    bool is_none() const {
+        return std::holds_alternative<resize_decision::none>(way);
+    }
     bool split_or_merge() const {
-        return !std::holds_alternative<resize_decision::none>(way);
+        return !is_none();
+    }
+    bool is_split() const {
+        return std::holds_alternative<resize_decision::split>(way);
+    }
+    bool is_merge() const {
+        return std::holds_alternative<resize_decision::merge>(way);
     }
     bool operator==(const resize_decision&) const;
     sstring type_name() const;
diff --git a/service/tablet_allocator.cc b/service/tablet_allocator.cc
index 2cb710d8ce..cc43228eb6 100644
--- a/service/tablet_allocator.cc
+++ b/service/tablet_allocator.cc
@@ -506,15 +506,21 @@ class load_balancer {
             locator::resize_decision decision;
 
             auto target_tablet_count = d.tablet_count;
-            if (d.tablet_count < d.min_tablet_count || d.avg_tablet_size > d.target_max_tablet_size()) {
-                // Split based on min_tablet_count or avg_tablet_size
+            // Split based on min_tablet_count or avg_tablet_size, or
+            // if the current resize_decision is split, apply hysteresis,
+            // so it would get cancelled only when crossing back the half-way point.
+            if (d.tablet_count < d.min_tablet_count || d.avg_tablet_size > d.target_max_tablet_size() ||
+                (d.resize_decision.is_split() && d.avg_tablet_size >= d.target_tablet_size)) {
                 // TODO: extend to n-way split when needed
                 target_tablet_count *= 2;
                 decision.way = resize_decision::split{};
-            } else if (d.avg_tablet_size < d.target_min_tablet_size()) {
-                // Consider merge, as long as it doesn't violate min_tablet_count
-                target_tablet_count /= 2;
-                if (target_tablet_count >= d.min_tablet_count) {
+            } else {
+                // Consider merge, as long as it doesn't violate min_tablet_count, or
+                // if the current resize_decision is merge, apply hysteresis,
+                // so it would get cancelled only when crossing back the half-way point.
+                if ((d.avg_tablet_size < d.target_min_tablet_size() && target_tablet_count / 2 >= d.min_tablet_count) ||
+                    (d.resize_decision.is_merge() && d.avg_tablet_size <= d.target_tablet_size)) {
+                    target_tablet_count /= 2;
                     decision.way = resize_decision::merge{};
                 }
             }
```

2025-02-06 15:47 UTC, bhalevy commented on service/tablet_allocator.cc
> +            } else if (d.avg_tablet_size < d.target_min_tablet_size()) {
Added hysteresis back in v16 ([fea93a8](https://github.com/scylladb/scylladb/commit/fea93a8715456fb8eaa30f6fb869337b40d29bb5))

2025-02-06 16:07 UTC, tgrabiec commented on service/tablet_allocator.cc
> +            }
Requiring reversal of decision to `merge` for split cancellation is not sensitive enough. The goal is to cancel split if post-split we would trigger a merge immediately. For that, waiting for merge signal is not enough, a merge would be triggered post-split as soon as avg size drops below target_tablet_size, not target_tablet_size / 2 (merge threshold).

2025-02-06 16:15 UTC, tgrabiec requested changes

2025-02-06 16:15 UTC, tgrabiec commented on service/tablet_allocator.cc
> +                    (d.resize_decision.is_merge() && d.avg_tablet_size <= d.target_tablet_size)) {
I think `target_tablet_count / 2 >= d.min_tablet_count` should be a common conjunction term, so that it cancels the hysteresis-induced merge too. Otherwise, post-merge we would split immediately to satisfy min_tablet_count. hints take precedence over size-based count.

2025-02-06 16:36 UTC, bhalevy commented on service/tablet_allocator.cc
> +                    (d.resize_decision.is_merge() && d.avg_tablet_size <= d.target_tablet_size)) {
That's a good point.
If min_tablet_count was changed in the middle of a merge, the new value may indeed cancel it.

2025-02-06 16:44 UTC, bhalevy commented
In v17 ([021fc3c](https://github.com/scylladb/scylladb/commit/021fc3c75626872957c0c844ade108d68b582c3e)):
- Don't allow merge to violate min_tablet_count also in the hyteresis case

```diff
diff --git a/service/tablet_allocator.cc b/service/tablet_allocator.cc
index cc43228eb6..b4355ea4aa 100644
--- a/service/tablet_allocator.cc
+++ b/service/tablet_allocator.cc
@@ -514,11 +514,11 @@ class load_balancer {
                 // TODO: extend to n-way split when needed
                 target_tablet_count *= 2;
                 decision.way = resize_decision::split{};
-            } else {
-                // Consider merge, as long as it doesn't violate min_tablet_count, or
-                // if the current resize_decision is merge, apply hysteresis,
+            } else if (target_tablet_count / 2 >= d.min_tablet_count) {
+                // Consider merge, as long as it wouldn't violate min_tablet_count.
+                // If the current resize_decision is merge, apply hysteresis,
                 // so it would get cancelled only when crossing back the half-way point.
-                if ((d.avg_tablet_size < d.target_min_tablet_size() && target_tablet_count / 2 >= d.min_tablet_count) ||
+                if (d.avg_tablet_size < d.target_min_tablet_size() ||
                     (d.resize_decision.is_merge() && d.avg_tablet_size <= d.target_tablet_size)) {
                     target_tablet_count /= 2;
                     decision.way = resize_decision::merge{};
```

2025-02-06 16:45 UTC, bhalevy commented on service/tablet_allocator.cc
> +                    (d.resize_decision.is_merge() && d.avg_tablet_size <= d.target_tablet_size)) {
Fixed in v17 ([021fc3c](https://github.com/scylladb/scylladb/commit/021fc3c75626872957c0c844ade108d68b582c3e))

2025-02-07 01:47 UTC, scylladb-promoter commented
#### :red_circle: CI State: UNSTABLE

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/15053/)
:white_check_mark: - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/15053/)
**The following new/updated tests ran 100 times for each mode:**
:small_blue_diamond: boost/network_topology_strategy_test
:small_blue_diamond: boost/schema_change_test
:small_blue_diamond: boost/tablets_test
:white_check_mark: - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/3250/)
:white_check_mark: - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/6366/)
:white_check_mark: - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/14381/)
:white_check_mark: - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/15053/)
#### Build Details:
- Duration: 8 hr 56 min
- Builder: spider2.cloudius-systems.com

2025-02-07 12:50 UTC, tgrabiec approved these changes

2025-02-07 14:33 UTC, mykaul commented
@scylladb/scylla-maint - can we merge this?

2025-02-07 15:01 UTC, tgrabiec commented
> #### 🔴 CI State: UNSTABLE
> ✅ - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/15053/) ✅ - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/15053/) **The following new/updated tests ran 100 times for each mode:** 🔹 boost/network_topology_strategy_test 🔹 boost/schema_change_test 🔹 boost/tablets_test ✅ - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/3250/) ✅ - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/6366/) ✅ - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/14381/) ✅ - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/15053/)
> 
> #### Build Details:
> * Duration: 8 hr 56 min
> * Builder: spider2.cloudius-systems.com

https://github.com/scylladb/scylladb/issues/22628

2025-02-07 16:05 UTC, tgrabiec commented
Rekicked CI

2025-02-08 02:32 UTC, scylladb-promoter commented
#### :green_circle: CI State: SUCCESS

:white_check_mark: - [Build](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/15071/)
:white_check_mark: - [Unit Tests Custom](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/15071/)
**The following new/updated tests ran 100 times for each mode:**
:small_blue_diamond: boost/network_topology_strategy_test
:small_blue_diamond: boost/schema_change_test
:small_blue_diamond: boost/tablets_test
:white_check_mark: - [dtest with tablets](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-tablets/3273/)
:white_check_mark: - [dtest](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/14407/)
:white_check_mark: - [dtest with topology changes](https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release-with-consistent-topology-changes/6390/)
:white_check_mark: - [Unit Tests](https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/15071/)
#### Build Details:
- Duration: 11 hr
- Builder: i-031bfc9f039741f94 (m5ad.8xlarge)

2025-02-09 00:30 UTC, merged